### ISSUE TITLE
Versioned migration output appears to be incorrect

### ISSUE THREAD

**Issue by jrmcpeek** [ariga/atlas#1018]
We are exploring atlas for database schema management and migrations.

Setting up a toy model with an `atlas.hcl` and a `schema.hcl` as follows:

```hcl
env "local" {
    src = "schema.hcl"

    url = "postgres://user:pass@localhost:5432/db_name?sslmode=disable"
    dev = "postgres://user:pass@localhost:5432/db_name_shadow?sslmode=disable"

    schemas = ["public"]

    migration {
        dir = "file://migrations"

        format = "atlas"
    }
}
```

```hcl
schema "public" {}

table "users" {
    schema = schema.public

    column "id" {
        type = bigint

        null = false

        identity {
            generated = ALWAYS
        }
    }

    primary_key {
        columns = [column.id]
    }
}
```

Starting with a fresh database, after running only `CREATE DATABASE db_name;` and `CREATE DATABASE db_name_shadow;`.

I then ran the migration command to generate a diff (`atlas migrate diff --env local --schema public`). This completes successfully and generates the following file (xxx5318.sql):

```sql
-- create "users" table
CREATE TABLE "public"."users" ("id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY, PRIMARY KEY ("id"));
```

However, the status command (`atlas migrate status --env local`), shows the following:

```
Migration Status: OK
  -- Current Version:	No version applied yet
  -- Next Version:	Already at latest version
  -- Available:		1
  -- Executed:		0
  -- Pending:		0
```

**First issue:** Should "Next Version" here be the file just generated, named "xxx5318.sql"? If not, what does "Already at latest version" mean in this context, when there is an unapplied migration? Should status be "PENDING" instead of "OK"? Should the counts be Available 1, Executed 0, Pending 1?

I now apply the migration with `atlas migrate apply --env local`, resulting in:

```sql
Migrating to version 20220807075318.sql (1 migrations in total):

  -- migrating version 20220807075318.sql
    -> CREATE TABLE "public"."users" ("id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY, PRIMARY KEY ("id"));
  -- ok (5.929761ms)

  -------------------------
  -- 5.973805ms
  -- 1 migrations
  -- 1 sql statements
```

```
Migration Status: OK
  -- Current Version:	20220807075318.sql
  -- Next Version:	Already at latest version
  -- Available:		1
  -- Executed:		1
  -- Pending:		0
```

Both of these look good. I make a change to the `schema.hcl` file to add a new column:

```diff
schema "public" {}

table "users" {
    schema = schema.public

    column "id" {
        type = bigint

        null = false

        identity {
            generated = ALWAYS
        }
    }
+
+    column "happy" {
+        type = boolean
+
+        null = false
+
+        default = true
+    }

    primary_key {
        columns = [column.id]
    }
}
```

Create a new migration (xxx5934.sql) with `atlas migrate diff --env local --schema public`:

```sql
-- modify "users" table
ALTER TABLE "public"."users" ADD COLUMN "happy" boolean NOT NULL DEFAULT true;
```

And check the status (`atlas migrate status --env local`):

```
Migration Status: PENDING
  -- Current Version:	20220807075934.sql
  -- Next Version:	20220807075934.sql
  -- Available:		2
  -- Executed:		2
  -- Pending:		1
```

**Second issue:** This doesn't look right. What I expected here is that the current version is `xxx5318.sql` and the next version is `xxx5934.sql`. I would also expect this to say Available 2, Executed 1, Pending 1. If the above is correct as-is, could you help me better understand what it's trying to convey?

Nonetheless, we attempt to apply the migration (`atlas migrate apply --env local`):

```sql
Migrating to version 20220807075934.sql from 20220807075318.sql (1 migrations in total):

  -- migrating version 20220807075934.sql
    -> ALTER TABLE "public"."users" ADD COLUMN "happy" boolean NOT NULL DEFAULT true;
  -- ok (3.916609ms)

  -------------------------

  -- 3.961342ms
  -- 1 migrations
  -- 1 sql statements
```

```
Migration Status: OK
  -- Current Version:	20220807075318.sql
  -- Next Version:	Already at latest version
  -- Available:		2
  -- Executed:		1
  -- Pending:		0
```

**Third issue:** I believe the current version here should be `xxx5934.sql` rather than `xxx5318.sql`.

With all of that said, the migration itself appears to have completed just fine, and the end state of the table is as expected:

```sql
# \d+ users

                                                    Table "public.users"

 Column |  Type   | Collation | Nullable |           Default            | Storage | Compression | Stats target | Description 

--------+---------+-----------+----------+------------------------------+---------+-------------+--------------+-------------

 id     | bigint  |           | not null | generated always as identity | plain   |             |              | 

 happy  | boolean |           | not null | true                         | plain   |             |              | 

Indexes:

    "users_pkey" PRIMARY KEY, btree (id)

Access method: heap
```

-----
Tool versions:

```
postgres (PostgreSQL) 14.4 (Ubuntu 14.4-1.pgdg22.04+1)
psql (PostgreSQL) 14.4 (Ubuntu 14.4-1.pgdg22.04+1)

atlas version v0.5.0
https://github.com/ariga/atlas/releases/tag/v0.5.0
```

**Comment by masseelch** [comment]
Hey @jrmcpeek, thank you for raising this issue and for its detailedness <3

> First issue: Should "Next Version" here be the file just generated, named "xxx5318.sql"? If not, what does "Already at latest version" mean in this context, when there is an unapplied migration? Should status be "PENDING" instead of "OK"? Should the counts be Available 1, Executed 0, Pending 1?

You are correct. I will investigate immediately.

> This doesn't look right. What I expected here is that the current version is xxx5318.sql and the next version is xxx5934.sql. I would also expect this to say Available 2, Executed 1, Pending 1. If the above is correct as-is, could you help me better understand what it's trying to convey?

Yes.

> I believe the current version here should be xxx5934.sql rather than xxx5318.sql.

And yes.

It indeed looks like the status command does not work like it should. I will investigate and notify you back once I know whats going on.

**Comment by masseelch** [comment]
@jrmcpeek Quick feedback for you: The latest master has the first and third issue resolved. The second one I will solve today.

**Comment by jrmcpeek** [comment]
Appreciate the update. Since I was grabbing the latest canary release to check #1045, I rechecked here and can confirm that the first and third cases appear good as of 30b4018.
