### ISSUE TITLE
Auto escape the database url `-u`

### ISSUE THREAD

**Issue by xin-hao-awx** [ariga/atlas#1034]
When I using the cli to apply a schema to a database with password which contains special chars,
the cli will throw a URL parse error.
Should we auto escape the url `-u`?

See also https://stackoverflow.com/questions/48671938/go-url-parsestring-fails-with-certain-user-names-or-passwords

**Comment by xin-hao-awx** [comment]
Maybe we can add another approach for the users to input as separate params, such as

```
atlas schema apply --user user --password "$%@#(*%^$%" --url "postgres://host:port/dbname?sslmode=disable" -f schema.hcl
```

So that we can escape the `password` automatically

**Comment by rotemtam** [comment]
Hi @xin-hao-awx,

As the command accepts a URL, the standard way for dealing with odd characters is using URL encoding, see IETF [RFC 1738](https://www.rfc-editor.org/rfc/rfc1738), (see section 2.2) which defines URLs formally. I don't think Atlas should encode the URL for the user as this is a one-time operation (e.g doesn't change unless the password itself changes).
