### ISSUE TITLE
Bug [postgres]: inspected datatype "enum array" not captured correctly in HCL

### ISSUE THREAD

**Issue by ericyd** [ariga/atlas#1036]
**System**

* **Atlas version:** `v0.5.0`
* **OS**: Mac OS 12.4

**Summary**

Postgres allows column types of an array of enums.

When Atlas inspects a schema containing a column with this datatype, it correctly identifies the column type. However, it fails to recognize that the column type is a user-defined type that needs to be captured as well.

This results in a failure to apply the schema properly to a new database.

**Steps to reproduce**

```bash
createdb atlas_test
echo "create type my_enum as enum ('test', 'another'); create table testing ( my_array _my_enum );" | psql -h localhost -d atlas_test
atlas schema inspect --dsn "postgres://localhost:5432/atlas_test?sslmode=disable"
```

**Expected output**

```hcl
table "testing" {
  schema = schema.public
  column "my_array" {
    null = true
    type = sql("my_enum[]")
  }
}
schema "public" {
}
enum "my_enum" {
  schema = schema.public
  values = ["test", "another"]
}
```

**Actual output**

```hcl
table "testing" {
  schema = schema.public
  column "my_array" {
    null = true
    type = sql("my_enum[]")
  }
}
schema "public" {
}
```

**Comment by a8m** [comment]
Hey @ericyd and thanks for reporting this.

I'll handle it soon.

**Comment by a8m** [comment]
Hey @ericyd 👋 

I forgot to update you that the issue was resolved 2 weeks ago. Thanks for reporting this and please let me know if you still face any problems with it 🙏
