### ISSUE TITLE
Feature: Allow environment variables in schema

### ISSUE THREAD

**Issue by jrmcpeek** [ariga/atlas#1038]
We would like to leverage the project capabilities in `atlas.hcl`, using variables to avoid embedding credentials, hosts, etc.

From the documentation, it only appears possible to use this by passing in a `--var` flag. While this works, it can make the commands quite verbose if many flags need to be passed in, which appears to have been a driving reason behind the project file in the first place.

It would further be good if this could be used in the variables block, as that would allow for command line parameters to override environment variables, which is fairly consistent with other tools (at least from my experience).

Something like:

```hcl
variable "db_user" {
  type = string

  mapping = env.CLOUD_DB_USER

  default = "postgres"
}
```

With this, the thought would be:

If `--var db_user` is provided, `var.db_user` is set to the command line flag value.

If `--var db_user` is not provided and if `CLOUD_DB_USER` is present as an environment variable when running, `var.db_user` is set to `CLOUD_DB_USER`, and typing can still be checked via the type declaration.

If neither `--var db_user` nor `CLOUD_DB_USER` is present, use the default.

If neither `--var db_user` nor `CLOUD_DB_USER` is present, and there is no default, throw error about missing required variable as you do today.

**Comment by a8m** [comment]
Hey @jrmcpeek 👋 
@rotemtam and I actually discussed adding an `env` function a few weeks ago, but another solution I thought about is to use the syntax used by [envsubst](https://github.com/a8m/envsubst#docs). We'll work on a proposal for this and update this issue soon. Thanks

**Comment by sunderhaus** [comment]
Hi @a8m, would the `env` function work similarly to HashiCorp's [env](https://developer.hashicorp.com/packer/docs/templates/hcl_templates/functions/contextual/env)?

I also find the `atlas` command to be growing in length where I invoke it in scenarios I need to overwrite input variable default values, which I can script around but would like to avoid.

**Comment by a8m** [comment]
Hey @sunderhaus! The `getenv` function is supported for a long time. See this example: https://atlasgo.io/atlas-schema/projects#input-variables

**Comment by a8m** [comment]
Closed via https://github.com/ariga/atlas/pull/1687
