### ISSUE TITLE
Row level security policies

### ISSUE THREAD

**Issue by fenos** [ariga/atlas#1071]
Hello!

I would love to see [RLS ](https://www.postgresql.org/docs/current/ddl-rowsecurity.html) added to Atlas! 
I currently make a lot of use of them, especially when using Supabase!

The proposal would be to have the following spec:

```hcl
table "example" {

	column "user_id" {
		type = uuid
	}

       row_level_security = true

	policy "admin" {
		select {
			using = "auth.uid() = user_id"
		}
		delete {
			using = "auth.uid() = user_id"
		}
		update {
			check = "auth.uid() = user_id"
			using = "auth.uid() = user_id"
			to = "authentication" // specify schema or default to table schema
		}
		insert {
			check = "auth.uid() == user_id"
		}
	}
}
```

- `row_level_security (bool)` would allow us to enable / disable RLS on the table
- `policy` would be an object that represents the policy rules. There can be many policies on a table

the name of the policy for each operation would be `{table_name}_{policyname}_operation` for instance, given the example above atals should migrate:

```sql
ALTER TABLE example ENABLE ROW LEVEL SECURITY;

CREATE POLICY example_admin_select ON example
    FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY example_admin_delete ON example
    FOR DELETE
    USING (auth.uid() = user_id);

CREATE POLICY example_admin_update ON example
    FOR UPDATE
    WITH CHECK ( auth.uid() = user_id )
    USING (auth.uid() = user_id);

CREATE POLICY example_admin_insert ON example
    FOR INSERT
    WITH CHECK ( auth.uid() = user_id )
```

Any thoughts?

**Comment by rotemtam** [comment]
Hey @fenos 
Thanks for the thorough suggestion. RLS (and more Postgres capabilities) are definitely on our mind. We are still deliberating what’s the best way to extend the drivers in a modular way.  Keeping this issue open for tracking.

**Comment by unaimillan** [comment]
Any updates on this feature?

**Comment by unaimillan** [comment]
Probably it's worth mentioning @supabase here and try to draw attention of anyone interested in this feature and possible integration 🤔

**Comment by kyong0612** [comment]
@rotemtam 
We are eagerly awaiting to migrate RLS 🙏

**Comment by mkarbo** [comment]
We're also missing this, keeping us from migrating to atlas

**Comment by net** [comment]
I would prefer a format like this which more accurately represents how policies are implemented in Postgres:

```hcl
table "users" {
  ...
  policy "user_selects_users" {
    for = [SELECT]
    role = "user"
    using = "id = current_user_id()"
  }
}
```

**Comment by kav** [comment]
One further possible tweak here is it might be worth looking at the pattern for triggers as an excellent template. It's fairly frequently the case that you have a relatively consistent RLS policy across tables so being able to do

```
policy "user_selects_users" {
  for_each = [products, customers, projects]
  on = each.value
  for = [SELECT]
  role = "user"
  using = "user_id = current_user_id()"
}
```

would be really nice.

**Comment by meringu** [comment]
From the RLS docs:
> Each policy has a name and multiple policies can be defined for a table. As policies are table-specific, each policy for a table must have a unique name. Different tables may have policies with the same name.
Not enforcing a naming convention here would be great for supporting existing databases with RLS.

**Comment by a8m** [comment]
Hey! This was added in the latest release and should be officially out later today/tomorrow.

Please, see: https://atlasgo.io/atlas-schema/hcl#row-level-security-policy and https://atlasgo.io/atlas-schema/hcl#row-level-security for examples.
