### ISSUE TITLE
Stored Procedure & Triggers

### ISSUE THREAD

**Issue by fenos** [ariga/atlas#1072]
Stored procedures are widely used in the SQL community. By supporting them we could unlock many more use cases for atlas!

A proposal I have in mind is the following:

```hcl
procedure "insert_user_profile" {
   language = plpgsql

   param {
      name = "user_id"
      type = uuid
   }

   returns = "trigger"
   
   operation = "
       INSERT INTO ....
   "
}

table "user" {
    ....

    trigger "insert_profile_on_create" {
        operations = [   // multiple operations are joined with OR condition
           "AFTER INSERT",
        ]

        for_each = "ROW" // ROW | STATEMENT

        when = "(sql condition)"

       execute = procedure.insert_user_profile
    }
}

table "user_profile" {
   column "user_id" {
     type = uuid
   }
}
```

**Comment by cemo** [comment]
A common use case is updating timestamps such as `last_updated_at`. Unfortunately in Postgres this is not easy as MySQL.

**Comment by adpande** [comment]
This is much required feature. We do use lot of triggers. :)

**Comment by kantum** [comment]
@cemo & @adpande how do you manage it right now? I'm planning to use atlas on an existing database which has triggers and will have procedures, what I need from atlas is the migration generating feature. Do you add your own SQL file to add triggers?

**Comment by andre-bisa** [comment]
This proposal would be much appreciated!

**Comment by rkrishnasanka** [comment]
It would be great to know how we should handle triggers, etc.

**Comment by jsnb** [comment]
+1 on the point of updating timestamps for the `update_at` field. Another important use case is using triggers to automate tracking history on all the tables. I like to have a "history" table for every table in the db and use a trigger to insert a record of every version of the row. It _can_ be done by the application but I prefer having that done in the database.

**Comment by cemo** [comment]
Triggers are officially supported in the latest release. I have not tried yet but you are great guys. ❤️

**Comment by a8m** [comment]
Thanks, @cemo ❤️ 

For reference, here are links to the docs for [functions](https://atlasgo.io/atlas-schema/hcl#function), [procedures](https://atlasgo.io/atlas-schema/hcl#procedure), and [triggers](https://atlasgo.io/atlas-schema/hcl#trigger).
