### ISSUE TITLE
About the latest release

### ISSUE THREAD

**Issue by chenrui333** [ariga/atlas#1090]
It looks like the latest release still points to 0.6.0, shall 0.6.3 get marked as the latest release? Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/108315

**Comment by rotemtam** [comment]
Hi @chenrui333,

0.6.1-0.6.3 are all patches so we didn't want to make a big announcement about them. When we create a release in GitHub our followers are notified so we want to not be spammy by creating noise multiple times a week. 

Hope this makes sense.
