### ISSUE TITLE
Whats the status of the management UI?

### ISSUE THREAD

**Issue by rightisleft** [ariga/atlas#1195]
Whats the status of the management UI?

https://atlasgo.io/ui/intro

**Comment by a8m** [comment]
Hey @rightisleft, and thanks for reaching out. 

We decided to remove the management UI from the released binary a few months ago for a few technical reasons - I can elaborate if you're interested, but the TL;DR is that I believe the Atlas engine and the management UI should be separated. 
Also, from my discussions with multiple users, I found out that all of them are interested in the ERD component, and editing the schema and executing migrations from the management UI are unused features. 

What's the status now? The current incarnation of the management UI is called *Ariga Cloud*. We have silently launched it for feedback from the community, and I'll be really happy if you try it.  The docs are [here](https://atlasgo.io/cloud/getting-started). 

In any case, I would love to hear your thoughts on what you would expect to see in such a product. You can write it here or send me a message on [our Discord](https://discord.gg/zZ6sWVg6NT).
