### ISSUE TITLE
Always tries to create a database with 0.8.0

### ISSUE THREAD

**Issue by shyim** [ariga/atlas#1224]
I want to manage my database from PlanetScale and atlas tries to create always a new database.

I just run:

```
./atlas-cli schema inspect -u "mysql://$(DATABASE_USER):$(DATABASE_PASSWORD)@eu-central.connect.psdb.cloud/shopmon?tls=true" > schema.hcl
./atlas-cli schema apply -f schema.hcl -u "mysql://$(DATABASE_USER):$(DATABASE_PASSWORD)@eu-central.connect.psdb.cloud/shopmon?tls=true"
```
or watch the Planet Scale Tutorial video which does the same https://www.youtube.com/watch?v=UBnEPk2Wbcg

0.8.0 fails with

```
Error: add new schema named "atlas_dev_shopmon_1666439645": Error 1235: create database is not supported
```

0.7.0 works

```
Schema is synced, no changes to be made
A new version of Atlas is available (v0.8.0):
https://github.com/ariga/atlas/releases/tag/v0.8.0
```

**Comment by masseelch** [comment]
Hey @shyim, thank you for reporting this. I will send a fix soon and notify you here once it is fixed. 

We will trigger a patch release after.
