### ISSUE TITLE
Unexpected schema migration interactions

### ISSUE THREAD

**Issue by jrmcpeek** [ariga/atlas#1254]
I ran into the following issue while working on a database schema change. Generally, we use versioned migration for our differences.

Currently, when we set up a new database for development, we issue the following command:

```bash
atlas schema apply --auto-approve --env local
```

This does its thing and bootstraps the database with a straight-to-greatest schema.

This completes successfully. To be sure, running it a second time gives me:

```bash
$ atlas schema apply --auto-approve --env local

Schema is synced, no changes to be made
```

For a triple-check, I confirm that there are now missing changes sitting in a schema file somewhere:

```bash
$ atlas migrate diff --env local --schema public

The migration directory is synced with the desired state, no changes to be made
```

At this point, I make a schema change and generate the new migration file:

```bash
atlas migrate diff --env local --schema public
```

A new file is generated and the `atlas.sum` file is updated as expected.

Checking the migration status is out of sorts, however:

```bash
$ atlas migrate status --env local

Migration Status: PENDING
  -- Current Version: No migration applied yet
  -- Next Version:    20220808074842
  -- Executed Files:  0
  -- Pending Files:   5
```

Prior to the new migration file, there were only 4 files, and the _equivalent_ of those 4 files had been applied.

Indeed, the `atlas migrate diff` command correctly generated only the _expected differences_.

Presumably, this is due to data in the `atlas_schema_revisions` schema not being populated using `atlas schema apply`.

**Question 1: Is this the expected/desired behavior? Should these two modes be able to interact, or must only a single method of schema updates be chosen and adhered to?**

Nevertheless, I proceed on in an attempt to apply the migration:

```bash
$ atlas migrate apply --env local

Error: sql/migrate: connected database is not clean: found schema "public". baseline version or allow-dirty is required
```

No dice. Using `--allow-dirty` won't work, since tables already exist.

Let's check our status again:

```bash
$ atlas migrate status --env local

Error: sql/migrate: connected database is not clean: found schema "public". baseline version or allow-dirty is required
```

Well, that's unexpected. Now the status is broken, even though we were just able to run it two commands ago (albeit, with incorrect results).

**Desire 1: If `atlas migrate diff` can appropriately differentiate just delta changes, then `atlas migrate status` should output proper details.**

**Desire 2: If `atlas migrate diff` can appropriately differentiate just delta changes, then `atlas migrate apply` be able to apply only the unapplied migrations.**

**Desire 3: A failed call to `atlas migrate apply` shouldn't be able to cause subsequent calls to `atlas migrate status` to fail.**

Note: If the above is intentionally an excluded-from-intended use case, we can change our setup to run `atlas migrate apply` rather than `atlas schema apply` - this was done to avoid the overhead of migration application creeping higher as the list of migrations grows.

-----
Tool versions:

```
postgres (PostgreSQL) 14.5 (Ubuntu 14.5-2.pgdg22.04+2)
psql (PostgreSQL) 14.5 (Ubuntu 14.5-2.pgdg22.04+2)

atlas version v0.8.2-571947f-canary
https://github.com/ariga/atlas/releases/latest
```

**Comment by a8m** [comment]
Hey @jrmcpeek, and thanks for the detailed issue.

> Is this the expected/desired behavior? Should these two modes be able to interact, or must only a single method of schema updates be chosen and adhered to? 

The behavior is expected because the two commands represent two different workflows. State-based and versioned-based migrations.

However, you can replace `schema apply` with `migrate apply` (without `N`) to replay all migration files, or set up the `--baseline` flag to the latest version in case you used `schema apply` before.

**Comment by rotemtam** [comment]
Just to add to @a8m 's answer, re:
> this was done to avoid the overhead of migration application creeping higher as the list of migrations grows.

We completely understand this point and are planning to add some cool way to "compact" history in a way that's compatible with Atlas (update the sum file, interoperate with the revisions table cleanly) in the near future.
