### ISSUE TITLE
Empty ...down.sql when drop tables

### ISSUE THREAD

**Issue by turelmert** [ariga/atlas#1332]
**Description**: 
I'm using Atlas in combined with GORM's auto migrate feature as described in docs to generate migration scripts. And i'm running Atlas with "golang-migrate" as the format. But when i drop a table and run "atlas migrate diff", the down.sql that has been generated by the Atlas is empty. This leads golang-migrate to fail when migrating to an older version. 

**Steps To Reproduce**:
- Create DBs _diff_ _gorm_ and _app_.
- Create two entity models _users_ and _admins_.
- Create tables on _gorm_ db by using GORM auto migrate. 
- Run Atlas with the following command.
```shell
atlas migrate diff "init" --dir "./migrations"?format=golang-migrate --dev-url "diff_db_url" --to "gorm_db_url" 
```
- See ..._init.up and ..._init.down SQL files.
- Drop _diff_ and _gorm_ DBs.
- Apply migrations on _app_ DB via golang-migrate.
- Succeed
- Remove _admins_ model. 
- Create DBs _diff_ and _gorm_.
- Create tables on _gorm_ db by using GORM auto migrate. (users only)
- Run Atlas with the following command.
```shell
atlas migrate diff "drop_admins" --dir "./migrations"?format=golang-migrate --dev-url "diff_db_url" --to "gorm_db_url" 
```
- See ..._drop_admins.down.sql is empty.

**Expected**:
**...drop_admins.up.sql**;
```sql
-- drop "admins" table
DROP TABLE "public"."admins";
```

**...drop_admins.down.sql**;
```sql
-- create "admins" table
CREATE TABLE "public"."admins" ("id" text NOT NULL, "name" text NULL, "surname" text NULL, PRIMARY KEY ("id"));
```

**Actual** 
**...drop_admins.up.sql**;
```sql
-- drop "admins" table
DROP TABLE "public"."admins";
```

**...drop_admins.down.sql**:
```sql
```

**Comment by rotemtam** [comment]
Hey 👋 
Thanks for the detailed report! 

Are down-migrations generated properly for you in other cases? (that aren't DROP TABLE changes)

**Comment by turelmert** [comment]
Hi @rotemtam, 
You're welcome :) 

Yes, in other cases i don't have any problems.
I've tried following operations: create TABLE , alter TABLE. 
And their down-migrations has been generated as expected.

**Comment by a8m** [comment]
Thanks for reporting this, @turelmert. The issue was resolved with https://github.com/ariga/atlas/pull/1346.

Please update your Atlas version and let me know if you have any troubles with it 🙏

**Comment by turelmert** [comment]
Hi @a8m, 
Thank you for the response, 

I've updated my Atlas version to the **v0.8.3** via Brew.
But i think this [version](https://github.com/ariga/atlas/releases/tag/v0.8.3) doesn't include your PR (#1346).
Is there any other way to update Atlas to a version which includes your work ?

**Comment by a8m** [comment]
You should get the `latest` build. Can you try this instead?

```sh
brew install ariga/tap/atlas
```

**Comment by turelmert** [comment]
Now i got the **v0.8.4-e53dd27-canary** and it works like a charm.  
Thank you so much 👍
