### ISSUE TITLE
Feature: Add SQLServer support 

### ISSUE THREAD

**Issue by YourTechBud** [ariga/atlas#1343]
Do consider adding support for sql server / mssql.

**Comment by y6vmeq** [comment]
Yes. I am totally agree with you! It would be greate! Or maybe you already have some plan about it?

**Comment by srs** [comment]
We are using SQLServer for our main project, so I have started this effort in a branch. Anyone else started this?

**Comment by celluj34** [comment]
What specifically _isn't_ supported? SQLite and MSSQL are fairly similar, maybe it wouldn't be too difficult to introduce? Or maybe it's about more specific things like JSON support, temporal tables, etc?

**Comment by IvanJosipovic** [comment]
I see a bunch of PRs realting to MSSQL, https://github.com/ariga/atlas/pulls?q=sql%2Fmssql
What is the status of this code?

**Comment by a8m** [comment]
Closing as SQL Server support was added a few months ago. Please, see this blog post for more info: https://atlasgo.io/blog/2023/10/17/automatic-migrations-for-sql-server
