### ISSUE TITLE
Support SQL-VIEWs

### ISSUE THREAD

**Issue by roderm** [ariga/atlas#1373]
I have a schema, which has SQL views. In the HCL export this views look like this:
```hcl
table "view_customer" {
  schema  = schema.testing
  comment = "VIEW"
  column "customer_id" {
    null    = false
    type    = int
    default = 0
  }
  column "user_id" {
    null = true
    type = int
  }
}
```
By creating this schema, the views are created as **tables**. 
* Is it possible to ignore all views and not have to list them in `--exclude` 
* Is support for views planned / possible?

**Comment by uptickmetachu** [comment]
We would also love this functionality as well.

**Comment by kaorukobo** [comment]
+1 :+1:  

I'm in trouble for this issue. When I remove "view_customer" resource from the Atlas schema, `atlas apply` tries to drop the view.
Hope there were `ignore` property for the table resource like as follows:

```hcl
table "view_customer" {
  schema = schema.testing
  ignore = true     # <===
}
```

**Comment by vamshiaruru32** [comment]
+1 for me as well.
Atlas is really well thought out, and I'd love to use it to create materialised views as well :)

**Comment by cemo** [comment]
This is already done.

https://atlasgo.io/blog/2023/08/06/atlas-v-0-13
