### ISSUE TITLE
Error when changing default value for character_varying column in PostgreSQL 14.6

### ISSUE THREAD

**Issue by macdonsp** [ariga/atlas#1407]
I am attempting to change the default value for a `character_varying` column in PostgreSQL 14.6 and getting an error. I have created a test based on the integration test here - https://github.com/ariga/atlas/blob/master/internal/integration/testdata/postgres/column-default.txt which does pass.

For this test, I created two sample files:

```
$ cat schema.1.hcl
schema "public" {}

table "users" {
  schema = schema.public
  column "name" {
    type = character_varying
    default = "unknown"
  }
  column "age" {
    type = int
    default = 1
  }
  column "active" {
    type = boolean
    default = true
  }
}
```

```
$ cat schema.2.hcl
schema "public" {}

table "users" {
  schema = schema.public
  column "name" {
    type = character_varying
    default = "anonymous"
  }
  column "age" {
    type = int
    default = 1
  }
  column "active" {
    type = boolean
    default = true
  }
}
```

```
diff -u schema.1.hcl schema.2.hcl
--- schema.1.hcl	2023-01-17 08:47:29
+++ schema.2.hcl	2023-01-17 12:57:17
@@ -4,7 +4,7 @@
   schema = schema.public
   column "name" {
     type = character_varying
-    default = "unknown"
+    default = "anonymous"
   }
   column "age" {
     type = int
```

Applying the first schema results in the following successful output:

```
$ atlas schema apply -u "postgresql://test:test@localhost:5432/?sslmode=disable" -f schema.1.hcl --auto-approve
-- Planned Changes:
-- Create "users" table
CREATE TABLE "public"."users" ("name" character varying NOT NULL DEFAULT 'unknown', "age" integer NOT NULL DEFAULT 1, "active" boolean NOT NULL DEFAULT true);
```
 
Applying the second schema results in the following error:

```
$ atlas schema apply -u "postgresql://test:test@localhost:5432/?sslmode=disable" -f schema.2.hcl --auto-approve
Error: pq: column "anonymous" does not exist
```

**Comment by macdonsp** [comment]
From some more investigation, it looks like this happens because normalization only takes place when you specify a dev database - https://github.com/ariga/atlas/blob/master/cmd/atlas/internal/cmdapi/cmdapi.go#L512. If I rerun and specify a dev database, the modification takes place as expected.

**Comment by a8m** [comment]
Thanks for reporting this, @macdonsp. The issue was resolved with https://github.com/ariga/atlas/pull/1409.

I'll build a new release now. Please, give it a try and let me know if there's any issue with it 😃
