### ISSUE TITLE
Getting `unsupported type: "name"` & "oid" when `inspect --log "{{ sql . }}"`

### ISSUE THREAD

**Issue by CanRau** [ariga/atlas#1428]
Hey, just stumbled upon this incredible tool 🙏🏼 
Was playing around a little to get a feel for it and did the following

Install via `brew install ariga/tap/atlas`

```
atlas schema inspect -u "postgresql://postgres:[...]" > atlas-infered-schema.hcl
```

```
atlas schema inspect -u "postgresql://postgres:[...]" > atlas-infered-schema-public.hcl --schema public
```

Which worked great, as far as I can tell but then doing

```
atlas schema inspect -u "postgresql://postgres:[...]" > atlas-infered-schema-public.sql --schema public --log "{{ sql . }}"
```

gives me 

```
Error: template: format:1:3: executing "format" at <sql .>: error calling sql: create table "log": postgres: unsupported type: "name", postgres: unsupported type: "name", postgres: unsupported type: "oid"
```

in the `inspect`ed `.hcl` output they're declared as

```
column "table_name" {
  null    = false
  type    = sql("name")
  comment = "Name of the table that caused the trigger invocation"
}
column "oid" {
  null    = false
  type    = sql("oid")
  comment = "Object ID of the table that caused the trigger invocation"
}

**Comment by a8m** [comment]
Thanks for reporting this, @CanRau. I'll give it a look.

**Comment by CanRau** [comment]
Much appreciated, if that works I wanna look into using it for our startup 🤗

**Comment by a8m** [comment]
The issue was fixed @CanRau. Please, try it and let me know if there are any other problems. 
Thanks again for reporting this 🙏

**Comment by CanRau** [comment]
Yes works now as expected, thanks a lot, much appreciated 🥰
