### ISSUE TITLE
crdb: drop unique index error

### ISSUE THREAD

**Issue by matdehaast** [ariga/atlas#1450]
Currently dropping a unique index in cockroach db requires using the `DROP INDEX` syntax.

However atlas driver tries to do an
```
ALTER TABLE DROP CONSTRAINT
```

Which is currently not supported by CRDB. You can see the discussion from them [here](https://github.com/cockroachdb/cockroach/issues/42840)

The full error from atlas is
```json
{"out": "out: -- Planned Changes:\n-- Modify \"authorisation_clients\" table\nALTER TABLE \"public\".\"authorisation_clients\" DROP CONSTRAINT \"url_uniq\"\nError: modify \"authorisation_clients\" table: pq: unimplemented: cannot drop UNIQUE constraint \"url_uniq\" using ALTER TABLE DROP CONSTRAINT, use DROP INDEX CASCADE instead\n"}
```

I assume it needs to be handled [here](https://github.com/ariga/atlas/blob/286906399f5284e2444671cee55a896fa56cd364/sql/postgres/migrate.go#L269). I would be happy to do a PR and add test coverage but I am unsure how that driver actually knows if its doing CRDB stuff versus postgres stuff.

**Comment by a8m** [comment]
Closed with https://github.com/ariga/atlas/pull/2667.


Thanks for reporting this and sorry for the delay 🙏
