### ISSUE TITLE
Feature Wish: Support ClickHouse Database

### ISSUE THREAD

**Issue by skurfuerst** [ariga/atlas#1456]
Hey everybody,

thanks for this great project :) How much work would it be to support https://clickhouse.com/ as a database? Especially for analytical workloads, the schema diff-approach would be very useful IMHO. Any pointers on what would need to be done?

Thanks and all the best,
Sebastian Kurfürst

**Comment by giautm** [comment]
Hello guys, @skurfuerst, @gempir, @HeCorr. We're working on the support for ClickHouse DB. Can you guys please explain some use-cases with us? What's the main feature you're using with ClickHouse and what's the pain?

You guys can contact me (`@giautm`) via our discord, or my email: `giau@ariga.io`.

Thank you so much!

**Comment by gempir** [comment]
I don't particularly have a specific use-case yet. But all my sql environments always come with a schema manager of sorts. If I want to introduce ClickHouse in my company, this is kind of expected.

I use doctrine daily and manage all my tables in code that way. I would like to achieve the same in ClickHouse and just have code to manage my tables in ClickHouse

Specifically managing changes over time is really important to me, so adding a column, new relationships, etc.

**Comment by giautm** [comment]
Hello @gempir, good to see you here. one following question:

which [the table engine](https://clickhouse.com/docs/en/engines/table-engines) (Atomic, Memory, or MySQL integration...) you're using the most at your work?

**Comment by Slach** [comment]
@giautm - Atomic this is not Table engine, this is Database Engine allow us non blocking DDL
Most usefull engine is *MergeTree engines family

**Comment by gempir** [comment]
Do you mean Integration Engines? We don't

I think the most common use case is MergeTree as it is the default for almost everything in ClickHouse, that's what we are aiming to use. But like I said we don't currently run any ClickHouse in production.

We run a big mysql database, but it won't be integrated into ClickHouse in any way. 

Our code will write to ClickHouse.

**Comment by giautm** [comment]
@Slach: My mistake, thank you for your clarify. I'm not an expert with ClickHouse DB yet. But on my way to explorer more about its internal things.

@gempir, @Slach: Thanks you guys for sharing, We will support the MergeTree engine family on the first version

**Comment by spudstr** [comment]
Another vote for clickhouse!

**Comment by FollieHiyuki** [comment]
MergeTree family also has `Replicated` variants (https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replication#table_engines-replication). They work differently compared to the original variants.

**Comment by austin-barrington** [comment]
I wanted to +1 to a clickhouse integration. Happy to answer any questions you have :)

My use case is Database : Atomic or Replicated. Table: MergeTree, ReplacingMergeTree, SummingMergeTree, AggregatingMergeTree. As well as MaterializedView.

**Comment by rotemtam** [comment]
hey @austin-barrington  
are you on our discord? ping me when you have a moment I'm `rotemtam` there also
would love to ask you a few questions and get you on our beta program soon

**Comment by ma7dev** [comment]
Just for anyone who came late to the party. Currently, Atlas supports ClickHouse, but some features are missing, such as Materialized Views. Here is a [quick tutorial](https://github.com/ma7dev/atlasgo-example) that I have made for anyone who wants to test this.

**Comment by rotemtam** [comment]
Hey @jbpin 

The Atlas team is working on supporting materialized views. Hopefully in the next release 🤞 

For each database feature we need to code: inspection (retrieving current state from the database information schema), diffing, planning, etc.. so it takes time and effort to get everything working right.

**Comment by hilakashai** [comment]
Hey everyone! Following @rotemtam's last comment - materialized views for ClickHouse is officially out: 

https://atlasgo.io/blog/2024/02/02/atlas-v-0-19

**Comment by ma7dev** [comment]
I have tested it, and it works! I have updated [my tutorial](https://github.com/ma7dev/atlasgo-example) to include Materialized View with a Python notebook to check the logic. 

Thanks, @rotemtam and the team, for the fantastic work! 🚀 🔥
