### ISSUE TITLE
Can't apply migrations after clean schema

### ISSUE THREAD

**Issue by yasser-sobhy** [ariga/atlas#1469]
I am using Atlas to manage Ent versioned migrations of my app.

I have been using Atlas with no problems, but recently I made changes to my schema and wanted to clear the data and tables before running new migrations. I followed these instructions https://atlasgo.io/versioned/apply#reverting-all-schema-changes to clean the schema and re-run all the migrations

Running `atlas schema clean ...` worked fine but when I try to run `atlas migrate apply ...` I get: `pq: no schema has been selected to create in`

I have tried `docker-compose down -v` and started on a fresh db but still getting the same error. Any Thoughts?

**Comment by a8m** [comment]
Hey @yasser-sobhy 👋🏻
It looks like you forgot adding the schema in your `search_path`. e.g., `postgres://postgres:pass@localhost:5432/database?search_path=public&sslmode=disable`.

Can you try adding `search_path=public` and run it again?

**Comment by yasser-sobhy** [comment]
Thank you @a8m That worked! I didn't see `search_path` before, it would be great if we add it to the docs and/or support it in atlas configuration file`atlas.hcl`

**Comment by a8m** [comment]
Thanks for the feedback, @yasser-sobhy. You can actually add it to your `atlas.hcl` file today using the `schemas` option: https://atlasgo.io/atlas-schema/projects#project-files

Do you want to paste your config here? I can help with this.

**Comment by yasser-sobhy** [comment]
Thank @a8m . I tried it again now without `search_path` but it didn't work. It only works when I add `search_path` to the url

```hcl
env "local" {

    schemas = ["public"]
    url = "postgresql://ddn:ddn_pass@postgres:5432/ddn?sslmode=disable"
    dev = "postgresql://ddn:ddn_pass@postgres:5432/ddn?sslmode=disable"

    migration {
        // URL where the migration directory resides. Only filesystem directories
        // are currently supported but more options will be added in the future.
        dir = "file://database/migrations"
        // Format of the migration directory: atlas | flyway | liquibase | goose | golang-migrate
        format = atlas
    }
}
```

**Comment by a8m** [comment]
Thanks for reporting this, I'll give it a look. BTW, don't use the main database as "dev database". You can use the `docker` driver instead: `"docker://postgres/15/test?search_path=public"`.

**Comment by yasser-sobhy** [comment]
awesome @a8m  I still need to wrap my head around the dev database concept :)

**Comment by a8m** [comment]
I added some docs and examples to https://atlasgo.io/concepts/dev-database. Please, let me know if you have any more questions 🙏 

You can feel free to ping me in our Discord server: https://discord.gg/zZ6sWVg6NT
