### ISSUE TITLE
v0.9.1 not available @ https://release.ariga.io/atlas/atlas-[ostype]-[cputype]-v0.9.1

### ISSUE THREAD

**Issue by jufemaiz** [ariga/atlas#1505]
[v0.9.1](https://github.com/ariga/atlas/releases/tag/v0.9.1) tag added, no release artifacts made available.

Example:

```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>atlas/atlas-linux-amd64-v0.9.1</Key><RequestId>5RWHFBV99MYNAXRC</RequestId><HostId>GzQfidUnHwu/ZAiW+JPf8sx5Ftb5QkQGHkx03TH1Ay1Pu1DefxtnrofBirkEgkskDjfnF6BhVUM=</HostId></Error>
```

**Comment by masseelch** [comment]
Hello @jufemaiz. You are indeed right, our current workflows are scheduled twice a day and release a canary version to the CDN. You are right, that we should automate releasing tagged version, as for now we actually do this manually and I just now triggered a release for the v0.9.1. I will investigate further into automating this.

**Comment by jufemaiz** [comment]
QQ » can we look at having a releases page too?

Ref: https://github.com/ariga/atlas/issues/1498#issuecomment-1452732831

**Comment by masseelch** [comment]
@jufemaiz What are the exact requirements for such a release page? Is it enough to have a release information on GitHub for each tag? With automating the builds for a tag like mentioned above, this should be enough information to download the binary, right?

**Comment by jufemaiz** [comment]
If using the GitHub release, the artifacts will need to form part of the release. 

The alternative is something like the Go release page with well structured links to the versioned releases.

**Comment by masseelch** [comment]
I will discuss this and come back to you once we have a proposal :relaxed:

**Comment by balcieren** [comment]
Same problem, I can not start my project

**Comment by masseelch** [comment]
https://release.ariga.io/atlas/atlas-linux-amd64-v0.9.1 (checked as well for darwin and windows).

The binary does exist. @balcieren What URL did you try?

**Comment by balcieren** [comment]
> https://release.ariga.io/atlas/atlas-linux-amd64-v0.9.1 (checked as well for darwin and windows).
> 
> The binary does exist. @balcieren What URL did you try?
```

#0 70.76 go: ariga.io/atlas@v0.9.1: Get "https://proxy.golang.org/ariga.io/atlas/@v/v0.9.1.mod": dial tcp: lookup proxy.golang.org on 172.17.16.1:53: read udp 172.17.0.2:36279->172.17.16.1:53: i/o timeout
------
failed to solve: process "/bin/sh -c go mod download" did not complete successfully: exit code: 1
```

**Comment by masseelch** [comment]
> https://proxy.golang.org/ariga.io/atlas/@v/v0.9.1.mod

That link does not timeout for me and return the correct mod file. Are you sure there are no misconfgurations on your end? Are you running `go mod download` in a docker container?

**Comment by masseelch** [comment]
![image](https://user-images.githubusercontent.com/12862103/222701885-75349c07-6e01-4992-95a2-f4e9cbcae9fd.png)

Everything seems to be fine. If you can provide me with more context I am happy to help you.

**Comment by balcieren** [comment]
really insteresting problem

**Comment by a8m** [comment]
Closing, as it looks like the issue was resolved. Please, reopen it if you still have trouble with it. Thanks 🙏
