### ISSUE TITLE
Manually adding `CREATE DOMAIN` in SQL schema file with `migrate diff`

### ISSUE THREAD

**Issue by jared-latitud** [ariga/atlas#1512]
As `CREATE DOMAIN` statements are not yet supported by `migrate diff` I was attempting to workaround if by generation the migration files and then manually adding that line. That worked and `migrate apply` worked as expected. However after making a further change to the schema and running `migrate diff` I got the error:

```bash
➜ atlas migrate diff test --env local
Error: sql/migrate: read migration directory state: sql/migrate: execute: executing statement "CREATE DOMAIN ulid AS CHAR(33) CHECK (VALUE ~ '^[a-z]{3,8}_[A-HJKMNP-TV-Z0-9]{26}$');" from version "20230307170108": pq: type "ulid" already exists
```

I could reproduce this by the following:

1. Create directories `./schemas` and `./migrations`
2. Create file `./schemas/public.sql`
```sql
CREATE DOMAIN ulid AS CHAR(33) CHECK (VALUE ~ '^[a-z]{3,8}_[A-HJKMNP-TV-Z0-9]{26}$');

CREATE TABLE test (
  id ulid not null,
  name text not null,
  primary key ("id")
);
```
3. Run `atlas migrate diff test`
4. Edit the generated migration file by prepending the line `CREATE DOMAIN ulid AS CHAR(33) CHECK (VALUE ~ '^[a-z]{3,8}_[A-HJKMNP-TV-Z0-9]{26}$');`
5. Run `atlas migrate hash`
6. Run `atlas migrate apply`
7. Alter `public.sql` by adding a column to the `test` table.
8. Run `atlas migrate diff` again.

Expected Result:
`diff` ignores the `CREATE DOMAIN` statement

Current Result:
`diff` tries running the command which fails as the type already exists

**Comment by lorentzlasson** [comment]
Just run into the same thing. Would love to know if there is a work around for this

**Comment by ilanfrai** [comment]
Is there any ETA for resolving this issue? this problem requires us to use different workarounds when working with domains in postgres

**Comment by a8m** [comment]
Hey all! Domains were added to the last release and are available as a beta feature. See https://atlasgo.io/blog/2023/10/19/atlas-v-0-15#postgres-domains for more info.
