### ISSUE TITLE
Cannot use `DO $$`, `BEGIN` or `EXCEPTION` keywords in migrations.

### ISSUE THREAD

**Issue by oneill-c** [ariga/atlas#1530]
Hey,

I have been trying to wrap some statements in an `Exception` but am not having much luck.

This is what I am adding to my `schema.sql` file:

```
DO $$ BEGIN
    CREATE TYPE some-type AS ENUM ('some-val-1', 'some-val-2);
EXCEPTION
    WHEN duplicate_object THEN null;
END; $$
```

When I try to generate a migration based on this, I get the following error:

```
atlas migrate diff new_migration \
      --dir "file://configs/pgdb/migrations" \
      --to "file://configs/pgdb/schema.sql" \
      --dev-url "docker://postgres?search_path=public"
      
Error: sql/migrate: read migration directory state: sql/migrate: execute: executing statement "DO $$ BEGIN\n    CREATE TYPE some-type AS ENUM ('some-val-1', 'some-val-2');" from version "schema": pq: unterminated dollar-quoted string at or near "$$ BEGIN
    CREATE TYPE some-type AS ENUM ('some-val-1', 'some-val-2');"
make: *** [gen-migrate] Error 1
```
I also tried to run this without the `Do $$` block and I get the following error:

```
Error: sql/migrate: read migration directory state: sql/migrate: execute: executing statement "BEGIN\n    CREATE TYPE some-type AS ENUM ('some-val-1', 'some-val-2');" from version "schema": pq: syntax error at or near "CREATE"
make: *** [gen-migrate] Error 1
```
I guess this syntax is not supported by the SQL parser that you guys use?

I also don't see anything in the docs around support for these keywords, such as `DO $$`, `BEGIN`, `EXCEPTION`.

Can you confirm if this is the case? Is there anything else I can do in the meantime? Do you have a timeframe for when you might support this?

**Comment by a8m** [comment]
Hey, @oneill-c! I will give it a deeper look later today, but I think you can use delimiters for now: https://atlasgo.io/versioned/new#custom-statements-delimiter.

**Comment by a8m** [comment]
Hey! This is called _Dollar-Quoted String Constants_ in PostgreSQL, and I'll add support for this in the upcoming days. 

Thanks for reporting this, @oneill-c 🙏
