### ISSUE TITLE
Error: unsupported driver for Postgres

### ISSUE THREAD

**Issue by ayaanqui** [ariga/atlas#1538]
I'm trying out Atlas on a Postgres DB running inside a Docker container (mapped to port 5433). When I run the command below, I get the following error as output: `Error: unsupported driver ""`.

```
atlas migrate diff migration_name \
    --dir "./ent/migrate/migrations" \
    --to "./ent/schema" \
    --dev-url "postgresql://postgres:postgres@localhost:5433/postgres"
```

I tried looking up on the docs and also on the web but wasn't able to find anything related to this issue. Thanks for taking the time to help out!

**Comment by rotemtam** [comment]
Hi @ayaanqui 

You need to tell Atlas the driver it needs to use for the --dir and --to flags. This is done using a URL scheme that pretends the actual path (`ent://`, `file://`)

```
atlas migrate diff migration_name \
    --dir "file:///ent/migrate/migrations" \
    --to "ent://ent/schema" \
    --dev-url "postgresql://postgres:postgres@localhost:5433/postgres"
```

For more examples: https://atlasgo.io/versioned/diff

**Comment by ayaanqui** [comment]
@rotemtam it wasn't clear what `file` and `ent` were from the Ent docs so I got confused. thanks for the quick response
