### ISSUE TITLE
Missing Driver

### ISSUE THREAD

**Issue by piti118** [ariga/atlas#1541]
I have tried to follow the doc. But none of docker's maria/postgres driver listed in https://atlasgo.io/concepts/dev-database seems to work.

I got ```Error: sql/sqlclient: missing driver. See: https://atlasgo.io/url```

Did I miss something?

<img width="795" alt="image" src="https://user-images.githubusercontent.com/591316/226084264-aefb210f-c482-4f75-b617-67283efadfc4.png">

<img width="693" alt="image" src="https://user-images.githubusercontent.com/591316/226084305-d882ee57-1242-4df5-a779-6a82011b4192.png">

Other info that might be helpful

```
Docker version 20.10.17, build 100c701
OSX Apple Silicon installed via brew
```

my schema.sql

```
CREATE TABLE "Shoes" (
  "id" int PRIMARY KEY,
  "brand" varchar,
  "model" varchar,
  "size" varchar,
  "current_price" float
);

CREATE TABLE "Customers" (
  "id" int PRIMARY KEY,
  "name" varchar,
  "address" varchar
);

CREATE TABLE "Orders" (
  "id" int PRIMARY KEY,
  "customer_id" int
);

CREATE TABLE "OrderItems" (
  "id" int PRIMARY KEY,
  "order_id" int,
  "shoe_id" int,
  "quantity" int,
  "price" float
);

CREATE UNIQUE INDEX ON "Shoes" ("brand", "model", "size");

ALTER TABLE "Orders" ADD FOREIGN KEY ("customer_id") REFERENCES "Customers" ("id");

ALTER TABLE "OrderItems" ADD FOREIGN KEY ("order_id") REFERENCES "Orders" ("id");

ALTER TABLE "OrderItems" ADD FOREIGN KEY ("shoe_id") REFERENCES "Shoes" ("id");
```

**Comment by a8m** [comment]
Hey @piti118 👋🏻
Please, add the `file://` scheme to the desired state as defined in the doc: https://atlasgo.io/versioned/diff#generate-migrations-from-sql-schemas

```
—-to file://schema.sql
```

**Comment by piti118** [comment]
Thank you very much that works.

**Comment by a8m** [comment]
Great, closing 😃
