### ISSUE TITLE
`CREATE EXTENSION` is ignored in schema

### ISSUE THREAD

**Issue by oxilor** [ariga/atlas#1545]
I have a schema that uses PostgreSQL extensions. For example,
```sql
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE companies (
  id serial PRIMARY KEY,
  name varchar(100) NOT NULL,
);

CREATE INDEX companies_name_idx ON companies USING gin (name gin_trgm_ops);
```

When I run `schema apply`, I get an error because the `CREATE EXTENSION` query is not executed.

```
Error: create index "companies_name_idx" to table: "companies": pq: operator class "gin_trgm_ops" does not exist for access method "gin"
```

To solve it, I have to manually run `CREATE EXTENSION` in both databases: dev (--dev-url) and target (--url). It's inconvenient, and sometimes it's impossible, for example, if the dev database is running in a new docker container.

**Comment by a8m** [comment]
Hey @oxilor 👋 
Both views and extensions are not supported by Atlas at the moment, but they are on our roadmap and we plan to address this soon. I'll leave this issue open.

**Comment by oxilor** [comment]
Related issue: [520](https://github.com/ariga/atlas/issues/520). Sorry for duplication of issues, but it's important features, so I decided to create new ones.

**Comment by a8m** [comment]
> Related issue: https://github.com/ariga/atlas/issues/520.

I missed #520. I think we can close this one, then.

I can't estimate this in time, but views, extensions, and domains are features we want to support soon.

**Comment by oxilor** [comment]
I'll be looking forward to these features!

**Comment by a8m** [comment]
@oxilor, I'd love to continue chatting in our [Discord Server](https://discord.com/invite/zZ6sWVg6NT) and hear your feedback on Atlas. Your insights would be much appreciated! ❤️
