### ISSUE TITLE
[BUG, postgres] Fail to drop field and change the composite key because of order of the query.

### ISSUE THREAD

**Issue by wangmir** [ariga/atlas#1551]
This is a complete example of mine. Please check the PR for failure.
https://github.com/wangmir/atlas_sample_demo/pull/6

I'm trying to make an example to ensure that atlas works for all use cases.

And I realized that, when trying to change composite key, it fails because the order is wrong.
Basically, I remove the column, and change the composite key at the ddl.

This is ddl before,

```hcl
table "test_new_composite_table" {
  schema = schema.testschema
  column "name" {
    null = false
    type = character_varying (255)
  }
  column "sample_column_1" {
    null = false
    type = character_varying (255)
  }

  primary_key {
    columns = [column.name, column.sample_column_1]
  }
}

```

and this is after,

```hcl
table "test_new_composite_table" {
  schema = schema.testschema
  column "name" {
    null = false
    type = character_varying (255)
  }
  column "sample_column_2" {
    null = false
    type = character_varying (255)
  }

  primary_key {
    columns = [column.name, column.sample_column_2]
  }
}
```

But because the migration script like this,

```sql
-- Modify "test_new_composite_table" table
ALTER TABLE
    "testschema"."test_new_composite_table" DROP COLUMN "sample_column_1",
ADD
    COLUMN "sample_column_2" character varying(255) NOT NULL,
    DROP CONSTRAINT "test_new_composite_table_pkey",
ADD
    PRIMARY KEY ("name", "sample_column_2");
```

it fails.

The order between `DROP_CONSTRAINT` and `DROP_COLUMN` should be swapped.

**Comment by a8m** [comment]
Thanks for reporting this, @wangmir. I'll give this a look.

**Comment by wangmir** [comment]
@a8m Can I ask the status of this? If u are busy solving this soon, and if u available to guide me on how to fix it, then I can raise PR for this.

**Comment by a8m** [comment]
Fixed https://github.com/ariga/atlas/pull/1566. I'll release a new version later today 😃 

Thanks for reporting this, @wangmir
