### ISSUE TITLE
PostgreSQL: character varying instead of varchar(n)

### ISSUE THREAD

**Issue by umalmyha** [ariga/atlas#1553]
I use [ent](https://entgo.io/) to implement my small project and I have pretty small entity defined as follows:
```go
type Merchant struct {
	ent.Schema
}

func (Merchant) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}).Default(uuid.New),
		field.String("name").MaxLen(128).NotEmpty(),
		field.Text("description").Nillable(),
		field.String("primary_email").MaxLen(254).NotEmpty(),
		field.String("secondary_email").MaxLen(254).Nillable(),
		field.String("primary_number").MaxLen(16).NotEmpty(),
		field.String("secondary_number").MaxLen(16).Nillable(),
		field.UUID("tenant", uuid.UUID{}).Immutable().Unique(),
		field.Bool("active").Default(true),
	}
}

func (Merchant) Edges() []ent.Edge {
	return nil
}
```
Next step is to generate migration file from this definition, so I run command:
```
- go run -mod=mod ariga.io/atlas/cmd/atlas migrate diff initial --dir "file://migrations" --to "ent://internal/ent/schema" --dev-url "docker://postgres/latest/migrations?search_path=public"
```
So I get the following output in migration file:
```SQL
-- Create "merchants" table
CREATE TABLE "merchants" ("id" uuid NOT NULL, "name" character varying NOT NULL, "description" text NOT NULL, "primary_email" character varying NOT NULL, "secondary_email" character varying NOT NULL, "primary_number" character varying NOT NULL, "secondary_number" character varying NOT NULL, "tenant" uuid NOT NULL, "active" boolean NOT NULL DEFAULT true, PRIMARY KEY ("id"));
-- Create index "merchants_tenant_key" to table: "merchants"
CREATE UNIQUE INDEX "merchants_tenant_key" ON "merchants" ("tenant");
```
I want to point out on fields which were defined as `field.String` and have `MaxLen` validator. I see in migration file that it is defined as "character varying", but I assume since there is concrete number of characters limitation, it can be defined as `character varying(n)` or `varchar(n)`.
As as workaround I can add `SchemaType`:
```go
field.String("name").MaxLen(128).NotEmpty().SchemaType(map[string]string{dialect.Postgres: "varchar(128)"})
```
So, now it gonna be declared as `character varying(128)`.

Can you, please, share some insights if such behavior of omitting varchar length has been done intentionally, so we must specify `SchemaType` explicitly or migration generation can be improved with length restriction?

**Comment by a8m** [comment]
Hey @umalmyha 👋 
This behavior was intentional for the reason I mentioned in https://github.com/ent/ent/issues/2712#issuecomment-1173081735.:
> The reason we didn't implement it in PostgreSQL is because it does not improve performance. See:
> 
> ![image](https://user-images.githubusercontent.com/7413593/177040858-0acbac24-68af-4454-815f-6f7348abc6f4.png)
> 
> However, in case you really need it, we can add support for it in Atlas. The [patch](https://github.com/ent/ent/blob/master/dialect/sql/schema/postgres.go#L716-L719) is really simple, so you're welcome to contribute it or one of the team can handle this. See


 The `SchemaType` can be a workaround for this, but we continue the discussion on https://github.com/ent/ent/issues/2712 if you dislike the default behavior. Thanks 🙏
