### ISSUE TITLE
Computed default values

### ISSUE THREAD

**Issue by lorefnon** [ariga/atlas#1565]
Hello again, 

When I use a computed expression as a default value: 

```hcl
table "foo" {
    schema = schema.public
    column "created_at" {
        type = timestamp
        default = "now()"
    }
}
```

The `now()` gets implicitly quoted (Sql contains `SET DEFAULT 'now()'`) and I end up with the output of `now()` at the time of schema apply as the default value for created_at. Not sure if it is a bug, but is it possible to have the default value as the expression itself ? The intent is to have `now()` evaluated at insertion time for every row.

My target database is postgres.

**Comment by a8m** [comment]
Hey @lorefnon 👋🏻
Can you try setting it as an expression: 
`sql("now()")`?

**Comment by lorefnon** [comment]
Ah perfect, the sql function is exactly what I needed. Thank you 🙏🏾
