### ISSUE TITLE
Hi,  id of type "User" (int64 != int)

### ISSUE THREAD

**Issue by Xwudao** [ariga/atlas#1581]
Command: `atlas migrate diff migration_name --dir "file://internal/data/ent/migrations" --to "ent://internal/data/ent/schema" --dev-url "mysql://root:root@:3306/dev-ent"`

Error: `Error: loading schema: entc/gen: set "User" foreign-keys: mismatch field type between edge field "user_id" and id of type "User" (int64 != int)`

In genarete.go：

```
//go:generate go run -mod=mod entgo.io/ent/cmd/ent generate --idtype int64 --feature sql/versioned-migration ./schema
```
it's ok!

but in atlas, got this error.

**Comment by a8m** [comment]
Hey, @Xwudao 👋 

You are using the `int64` type for identifiers, but your edge field (foreign key) is defined as an `int`. You need to define it as a `field.Int64` instead. The error occurs during the migration because MySQL expects the foreign key and its reference to match.

Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/zZ6sWVg6NT) in case you need more help with this 😎

**Comment by Xwudao** [comment]
> Hey, @Xwudao 👋
> 
> You are using the `int64` type for identifiers, but your edge field (foreign key) is defined as an `int`. You need to define it as a `field.Int64` instead. The error occurs during the migration because MySQL expects the foreign key and its reference to match.
> 
> Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/zZ6sWVg6NT) in case you need more help with this 😎

hi a8m!

Thank you for your reply. But, If I use `go generate` it's work on.

```
//go:generate go run -mod=mod entgo.io/ent/cmd/ent generate --idtype int64 --feature sql/versioned-migration ./schema
```


using atlas as below:

```
//go:generate go run -mod=mod entgo.io/ent/cmd/ent generate --idtype int64 --feature sql/versioned-migration ./schema
```

work error.


And I'm sure I use `field.Int64`


![image](https://user-images.githubusercontent.com/31327868/231684307-f8cb0d67-aa2b-4e90-9bae-c881777ea2aa.png)


![image](https://user-images.githubusercontent.com/31327868/231684429-b05bb76f-be57-4206-9af2-2b1d8f4ffe2a.png)

![image](https://user-images.githubusercontent.com/31327868/231684450-b659cb59-5ae1-45e1-b1b2-180183089fd1.png)

**Comment by Xwudao** [comment]
@a8m
