### ISSUE TITLE
cannot connect db using unix socket

### ISSUE THREAD

**Issue by akadoya** [ariga/atlas#1587]
Using a Dockerfile looks like below, trying to initializing the db schema using atlas by drop-in script in `/docker-entrypoint-initdb.d` directory.

```
FROM mariadb

USER root

# install atlas CLI
RUN apt-get update && apt-get install -y curl
RUN curl -sSf https://atlasgo.sh | sh
```

drop-in script contents (in this entry-point stage, tcp connection is not available yet but unix socket is ready) :
```
atlas schema apply \
  -u 'maria://user:password@unix(/run/mysqld/mysql.sock)/db?loc=Local' \
  --to file://schema-local.hcl --auto-approve
```

**Error:**
Error: mysql: query system variables: dial tcp: lookup unix()/run/mysqld/mysqld.sock: no such host

@a8m

**Comment by rotemtam** [comment]
Hey @akadoya 

The error you're seeing is caused by the mariaDB not being up yet at the point where you run Atlas against it. As it is defined in the Dockerfile, this happens during the image build phase.

In most cases I've encountered, applying migrations to a database is a runtime task, that happens just prior to application boot, and not a build time task. Is this your intention?

**Comment by akadoya** [comment]
> Hey @akadoya
> 
> The error you're seeing is caused by the mariaDB not being up yet at the point where you run Atlas against it. As it is defined in the Dockerfile, this happens during the image build phase.

Sorry I should have mentioned a bit more context, the script is not inside of Dockerfile. Dockerfile is only installing the atlas CLI.
MariaDB docker has a feature to run any scripts inside of /docker-entrypoint-initdb.d when the db starts up for the first time (so this is run time).
- https://hub.docker.com/_/mariadb
-- see Initializing a fresh instance section.

Yet this is still during the initialization phase, so tcp connection is not bound at this time. 
However, if I use mycli to connect the db with unix socket, I could connect the db - that is why I thought it'd be great if I could run atlas in the same way so that the production schema management and dev local db can have the same exact schema management structure.

**Comment by akadoya** [comment]
@a8m thank you very much for the quick turnaround, could you double check if the binary was released?
I installed it from `https://atlasgo.sh` but got unknown driver error. (tried both maria+unix and mysql+unix)
app-db-1          | 2023-04-18 00:04:38+00:00 [Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/atlas_init_schema.sh
app-db-1          | Error: sql/sqlclient: unknown driver "mysql+unix". See: https://atlasgo.io/url

**Comment by masseelch** [comment]
I'll check once I am near a computer.

**Comment by a8m** [comment]
@akadoya, I just checked it, and the latest binaries contain this patch. What version do you have?

```
➜  dev git:(master) curl -sSf https://atlasgo.sh | sh
atlas version v0.10.2-db8337c-canary
https://github.com/ariga/atlas/releases/latest
Installation successful!

➜  dev git:(master) atlas version
atlas version v0.10.2-db8337c-canary
https://github.com/ariga/atlas/releases/latest

➜  dev git:(master) atlas schema inspect -u mysql+unix:///var/tmp/mysql.sock
Error: mysql: query system variables: dial unix /var/tmp/mysql.sock: connect: no such file or directory
```

**Comment by akadoya** [comment]
This is the version I got.
atlas version v0.10.2-c9294dc-canary
Do I need to set any environment variable to override the version?

**Comment by masseelch** [comment]
https://github.com/ariga/atlas/tree/c9294dc/

You are in this build somehow. That should not happen. 

Can you show me the output of `curl -sSf https://atlasgo.sh | sh`?

**Comment by akadoya** [comment]
my bad, I was using my locally cached container image.
It is working as expected now!
