### ISSUE TITLE
Dockerfile of arigaio/atlas

### ISSUE THREAD

**Issue by hotrush** [ariga/atlas#1596]
Where i can find it?

**Comment by biederKdo** [comment]
@rotemtam It would be helpful to make the Dockerfile sources used in the internal monorepo publicly available.

I inspected `docker.io/arigaio/atlas:0.31.0` and noticed several Go modules included that are neither referenced in this repository nor in the Dockerfile you shared. These include:

- `github.com/Azure/azure-sdk-for-go/sdk/azcore`
- `github.com/ClickHouse/ch-go`
- `github.com/shopspring/decimal`
- *...and many others*

Could you clarify where these dependencies are coming from?

**Comment by rotemtam** [comment]
Hi,

Thanks for reaching out 

These are dependencies of Atlas, which contains proprietary code and is built on a private repository. For example, github.com/ClickHouse/ch-go is used to provide the [ClickHouse Driver](https://atlasgo.io/guides/clickhouse), which is an Atlas Pro feature - see [pricing](https://atlasgo.io/pricing).

If you want to use a fully open-source version, you are welcome to use the [community edition](https://atlasgo.io/community-edition) - a limited, but Apache 2 licensed release of the tool.
