### ISSUE TITLE
[POSTGRES]Custom Types when using

### ISSUE THREAD

**Issue by raduconst06** [ariga/atlas#1613]
**ATLAS VERSION:** 
[v0.10.1] (@latest)

**GENERAL DESCRIPTION:**
Using _POSTGRES_ extensions (e.g. pgvector) block devs from using _ATLAS_ as the custom types introduced by extensions are unsupported by atlas

**POSSIBLE SOLUTIONS:**
_approach A)_ 
Manually defined needed custom types in the main repository, maybe behind a feature flag
(e.g. --plugins pgvector, postgis)

__aproach B)__
Implement a plug&play plugin system type to allow inserting a per-plugin script to define the missing data types

**LINKED ISSUES**
#1601 
- [https://github.com/ariga/atlas/pull/1601](https://github.com/ariga/atlas/pull/1601) 
@crossworth 

**NOTES**
- willing to contribute if there will be a structured plan to implement anything to allow devs to specify custom SQL types

**Comment by crossworth** [comment]
Hi @raduconst06, can you provide more information about the issue? I tested a few days ago but forget about comment on this issue.

I was able to use the `vector` type using the [`sql` function](https://atlasgo.io/atlas-schema/sql-types#postgresql).

Steps:

```sh
docker run --rm -e POSTGRES_PASSWORD=pass -e POSTGRES_DB=test -p 35432:5432 ankane/pgvector
```

I connected and create an example table:

```sql
CREATE TABLE items (id bigserial PRIMARY KEY, embedding vector(3));
INSERT INTO items (embedding) VALUES ('[1,2,3]'), ('[4,5,6]');
```

**Atlas inspect to HCL:**

```sh
atlas schema inspect --url "postgres://postgres:pass@localhost:35432/test?search_path=public&sslmode=disable" > schema.hcl
```

schema.hcl
```hcl
table "items" {
  schema = schema.public
  column "id" {
    null = false
    type = bigserial
  }
  column "embedding" {
    null = true
    type = sql("vector(3)")
  }
  primary_key {
    columns = [column.id]
  }
}
schema "public" {
}
```

**Atlas inspect to SQL:**

```sh
atlas schema inspect --url "postgres://postgres:pass@localhost:35432/test?search_path=public&sslmode=disable" --format "{{ sql . }}" > schema.sql
```

schema.sql
```sql
-- Create "items" table
CREATE TABLE "items" ("id" bigserial NOT NULL, "embedding" vector(3) NULL, PRIMARY KEY ("id"));
```

I tried applying schema changes (`vector(4)`) as well (table with no data):

<img width="1117" alt="image" src="https://github.com/ariga/atlas/assets/1251151/f1654cfb-37ee-4ab3-b57d-09711a2830e7">


Is there something else that I'm missing?

**Comment by crossworth** [comment]
Hi @raduconst06, thats quite strange, I'm not able to reproduce the issue on my side.

<img width="1784" alt="image" src="https://github.com/ariga/atlas/assets/1251151/0b50e5cd-ce82-4264-a880-a8fe54ec96b3">

Tested with:

```
PostgreSQL 15.3 (Debian 15.3-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
```

```
PostgreSQL 15.1 (Debian 15.1-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
```

Can you try the steps from my last message (using the docker image) and see if that works for you?

I thats works, we have to find what is different from your setup. I'm not familiar with `pgvector`and since I can not reproduce on my side, it's hard to give better advice.
