### ISSUE TITLE
Occasionally, composite foreign key is regenerated with same constraint.

### ISSUE THREAD

**Issue by wangmir** [ariga/atlas#1614]
atlas version is `atlas version v0.10.2-7a85994-canary`

```
-- Create "model_db" table
CREATE TABLE "testschema"."table_1" (
  "model_name" character varying(16) NOT NULL,
  "db_type" character varying(16) NOT NULL,
  "version" character varying(32) NOT NULL,
  "name" character varying(32) NOT NULL,
  "data" text NOT NULL,
  PRIMARY KEY ("model_name", "db_type", "version")
);
-- Create "model_db_signal" table
CREATE TABLE "testschema"."table_2" (
  "model_name" character varying(16) NOT NULL,
  "db_type" character varying(16) NOT NULL,
  "version" character varying(32) NOT NULL,
  PRIMARY KEY ("model_name", "db_type", "version", "signal_name"),
  CONSTRAINT "table_2_model_name_db_type_version_fkey" FOREIGN KEY ("model_name", "db_type", "version") REFERENCES "testschema"."table_1" ("model_name", "db_type", "version") ON UPDATE NO ACTION ON DELETE NO ACTION
);
```

Table is similar to this one. (company private table)
There are no changes in the schema ddl file, and normally atlas does not generate any migration script, but sometime, it generates migration script like this. It's exactly same as before, but just drop existing constraint, and regenerate same constraint again. (normally, 10 times ok, 1 times fail like ratio)

```hcl
ALTER TABLE "testschema"."service_group" DROP CONSTRAINT "model_db_signal_model_name_db_type_version_fkey", ADD
 CONSTRAINT "model_db_signal_model_name_db_type_version_fkey" FOREIGN KEY ("model_name", "db_type", "version") REFERENCES "testschema"."model_db" ("model_name", "db_type", "version") ON UPDATE NO ACTION ON DELETE NO ACTION;
```

Is this known issue? or any clue about this?

The problem is, I cannot regenerate this problem in lightened DB which only has this table.
So, if u need more clue to solve this problem, I think I need to run atlas with debug option, and check the problem. Is this possible?

**Comment by nbenn** [comment]
I might have run into a related (or maybe even the same) issue as @wangmir. For me, however, such dropping/re-creating of composite FK constraints comes with a permutation of columns.

In a sitation like

```sql
CREATE TABLE table_a (
  "id_a" integer,
  "id_b" integer,
  "val" text,
  PRIMARY KEY ("id_a", "id_b")
)

CREATE TABLE table_b (
  "id" serial,
  "id_a" integer,
  "id_b" integer,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("id_a", "id_b") REFERENCES table_a ("id_a", "id_b")
)
```

I might end up with "changes" like

```sql
APTER TABLE table_b DROP CONSTRAINT table_b_id_a_id_b_fkey FOREIGN KEY ("id_b", "id_a") REFERENCES table_a ("id_b", "id_a")
```

i.e. the constraint (afaik) remains unchanged but nevertheless is dropped/re-created.

At least for Postgres I believe this comes down to the ordering of columns not being well-defined by the `ORDER BY` clause during schema inspection:

https://github.com/ariga/atlas/blob/e5c646bc817013b5832680ed7f0a35a5319f1121/sql/postgres/inspect.go#L1198

Given my understanding that the FK specifications `FOREIGN KEY ("a", "b") REFERENCES table_a ("a", "b")` and `FOREIGN KEY ("b", "a") REFERENCES table_a ("b", "a")` are in fact identical, I see two ways out: either fixing column ordering to something arbitrary like lexicographical during inspection or not considering column permutations during schema diffing.

**Comment by nbenn** [comment]
At least for Postgres, you could adapt your query to include something like

https://github.com/cynkra/dm/blob/64449a5fb19c4286eb73a8ac73ccaca54c015091/R/postgres.R#L30-L36

in order to get the correct column ordering out of the `pg_attribute` table. (I haven't tried this out myself.)

**Comment by wangmir** [comment]
@nbenn so, can u make a re-generate env? I cannot regenerate this issue in simple way. It only happens in my company database env with multiple tables. So I think it can be a thread-safe issue (it is not fundamentally, but the reason why the generated script is different at every `atlas migrate diff`).

**Comment by wangmir** [comment]
@a8m Do u have any suggestion on this issue? If the priority of this issue is low, then at least if u give me some hint, then I'll try to resolve this.

**Comment by a8m** [comment]
Fixed with https://github.com/ariga/atlas/pull/1677. A new version should be released later today 

Thank you both for reporting this.
