### ISSUE TITLE
"atlas migrate diff" between schemas with slightly differing names produces: Error: *schema.ModifySchema is not allowed when migration plan is scoped to one schema

### ISSUE THREAD

**Issue by JonJLee2001** [ariga/atlas#1625]
I'm trying to use atlas with schemas that are the same but have different names: i.e. we're hosting our (several) dev schemas and test schema on the same host so they all have slightly different names "project_db_jon", "project_db_alan", "project_db_test". Our staging/production schemas are on separate hosts and they're just called "project_db". 

When I do ```atlas migrate diff ```I get this error ```Error: *schema.ModifySchema is not allowed when migration plan is scoped to one schema``` I assume because it's not happy about the different source/target schema names. 

The only way I could get this to work was to generate HCL schema files and manually change all the schema name references, but is there a better way to make this work?

**Comment by JonJLee2001** [comment]
@a8m tagging as requested on discord

**Comment by a8m** [comment]
Hey @JonJLee2001 👋 
I believe I've identified the problem - could it be that the MySQL dev database has a different collation or charset compared to what's defined in the HCL file? You can confirm this by running `atlas schema inspect -u <dev-url>`.

**Comment by ivanvanderbyl** [comment]
I'm getting the same error when running the exact command mentioned in the docs:

```shell
atlas migrate diff migration_name \
  --dir "file://ent/migrate/migrations" \
  --to "ent://ent/schema" \
  --dev-url "docker://postgres/15/test?search_path=public"

# Error: *schema.ModifySchema is not allowed when migration plan is scoped to one schema
```

**Comment by a8m** [comment]
Hey @ivanvanderbyl, downgrading Atlas to v0.12.0 should solve the issue. I will send a patch to fix this later today.

**Comment by a8m** [comment]
Closing, as this was resolved a few months ago.
