### ISSUE TITLE
incorrect parsing of special characters in database password

### ISSUE THREAD

**Issue by jklafka-rokt** [ariga/atlas#1631]
I'm trying to perform a migration against a PostgreSQL database in AWS RDS, and running into an error due to having a special character (`?`) in the password. The same command works fine as long as there is no `?` special character in the database password.

Password, database name, etc. used are falsified from the originals.

```
$ atlas migrate apply --dir 'file://./pg-ads-api/migrations' --url "postgres://database:slfkjkwi[oer?[$dkks}owow@database.us-west-2.rds.amazonaws.com:5432/database"

Error: sql/sqlclient: parse open url: parse "postgres://database:slfkjkwi[oer?[$dkks}owow@database.us-west-2.rds.amazonaws.com:5432/database": invalid port ":slfkjkwi[oer" after host
error: Recipe `stage-migrate` failed on line 42 with exit code 1
```

**Comment by rotemtam** [comment]
Hi @jklafka-rokt 

Thanks for reaching out. Note that the connection string to the database is a URL therefore the specials chars in the password must be "percent encoded".

If you're interested in the formal definitions you can find it in this IETF spec for URLs:

https://datatracker.ietf.org/doc/html/rfc3986#section-2.1

**Comment by jrmcpeek** [comment]
@jklafka-rokt 

As of `atlas version v0.14.1-078bbe1-canary`, I was able to use built-in atlas features for this issue:

```hcl
env "environment" {
  url = "sqlserver://${var.db_user}:${urlescape(var.db_pass)}@${var.db_host}:1433"
}
```

**Comment by jklafka-rokt** [comment]
Great, thanks @jrmcpeek!
