### ISSUE TITLE
Workflow for continuous deployment of migrations generated offline ?

### ISSUE THREAD

**Issue by lorefnon** [ariga/atlas#1644]
So, the workflow I am trying to adopt is: 

1. Update atlas schema.hcl locally in a feature branch
2. Generate migrations against a dev database
3. Have the migrations be a part of pull review
4. Apply the migrations in other dev databases after merge and the prod databases after deployment 

This enables me to: 

1. Make it easy to review precisely what database changes are going to get applied as part of a specific deployment
2. Prevent any schema diffing against prod database during deployments

It seemed like the versioned workflow outlined in the docs would be ideally suited for the above, but when I attempt to generate migrations after the first invocation of `atlas migrate apply` I get an error as follows: 

```
atlas migrate diff update_schema --dir "file://src/db/migrations" --to "file://src/db/schema/schema.hcl" --dev-url "$PG_DSN"
Error: sql/migrate: taking database snapshot: sql/migrate: connected database is not clean: found schema "atlas_schema_revisions"
```

So I am curious if there is a way to have atlas incrementally generate migrations after updating schema hcl.

**Comment by cayter** [comment]
Just bumped into this, is this tool only meant to be used with Atlas Cloud?

**Comment by a8m** [comment]
Hey @lorefnon and @cayter 👋 

The purpose of the dev-database is explained in this [link](https://atlasgo.io/concepts/dev-database). In short, Atlas uses it to load the **current state** (as defined by the migration directory) by replaying the directory onto the provided dev-database connection. It then compares this **current state** against the **desired state** defined in your HCL schema(s), and might write a new migration file for moving from the current to the desired state, in case they are different. 

In this process, Atlas executes "work" on the dev-database, creating and dropping resources. Therefore, to ensure it doesn't accidentally affect a production or important database, Atlas first inspects the database to ensure it's clean and no resources could potentially be affected by its work. If you're working with Postgres, you can create a separate "dev" database (or schema, it depends on the case) and use it as `dev-url`. 

To simplify this manual process, Atlas also provides built-in integration for Docker. By passing `--dev-url "docker://postgres/15/dev?search_path=public"`, Atlas will create a temporary local Docker container running PostgreSQL 15, perform the necessary work on it, and delete it at the end. 

> Just bumped into this, is this tool only meant to be used with Atlas Cloud?

No, as answered on Discord - all features documented in atlasgo.io are supported by the CLI unless they are explicitly mentioned as cloud features 😃

**Comment by a8m** [comment]
Closing, but please free to reopen or join our [Discord](https://discord.gg/zZ6sWVg6NT) in case you need more help with this.

**Comment by tslater** [comment]
I'm not sure I'm understanding the error. Atlas was working for me until I upgrade from v0.10 to v0.12 and then I got a similar error:
```
Error: sql/migrate: connected database is not clean: found multiple schemas: 57
```
I previously read through and thought I understood the purpose of the dev database. Is this error because I'm using my main db as the dev db as well and it now expects it to be empty?
