### ISSUE TITLE
Possibly wrong versioning - arigaio/atlas:9.9.9

### ISSUE THREAD

**Issue by hotrush** [ariga/atlas#1671]
On the docker hub I can see a version 9.9.9 of atlas docker image which is 10 months old. Was it a mistake and if so - can it be removed?

Reason: it creates issues for software like renovate which automatically updates dependencies.

https://hub.docker.com/layers/arigaio/atlas/9.9.9/images/sha256-fa88600c043c0c1a531027c857b74d0eb19e414f27083af7997f1adaa8649dd0?context=explore

**Comment by rotemtam** [comment]
hey @hotrush 

done ✅ 

Apologies for the confusion.
