### ISSUE TITLE
supporting custom docker images in --dev-url

### ISSUE THREAD

**Issue by krilor** [ariga/atlas#1678]
Hi! And thanks for making this cool tool!

I'm trying to use Atlas on databases where we need to have some extensions enabled and am really excited that #1601 is happening.

While using a [dev database](https://atlasgo.io/concepts/dev-database), it seems like we have to use a "vanilla" postgres docker image, tho. I'm working around that by spinning up a ephemeral database "on the side", and using the standard `postgres://` url.

I'm reading https://github.com/ariga/atlas/blob/master/cmd/atlas/internal/docker/docker.go#L72
and thinking about how to support this within the current docker url format (docker://image/tag)

The only suggestion I can come up with is something similar to the "git+ssh://" format that I sometimes see with git (ref https://github.com/IonicaBizau/git-url-parse/blob/master/test/index.js#L12 ). So say that I compile an extension on top of the official postgres image (that preserves all the env vars, config etc that Atlas requires), then I could do: `docker+postgres://<my-image>/<my-tag>`

Would there be any interest in this or are there other options that would solve the same need?

**Comment by a8m** [comment]
@krilor, thanks for reporting this, and sorry for the delayed response. The issue was resolved with #2249

Please, see https://atlasgo.io/concepts/dev-database#introduction for more info.

**Comment by krilor** [comment]
Very nice :) Thanks for making it happen
