### ISSUE TITLE
Schema diff doesn't observe Project configuration

### ISSUE THREAD

**Issue by robarchibald** [ariga/atlas#1708]
When I run `atlas schema diff`, it doesn't observe any of my project config settings. I would expect that if I run `atlas schema diff --env local --var password=$PGPASSWORD` that it would diff between my schema specified as `file://schema.hcl` and my local database as specified in the `url` in the config. I would also expect it to use my `exclude` settings. It does none of those things.

Some other nits to consider:
- Why do I have to exclude the atlas schema from a diff? That seems like an obvious thing for `atlas schema diff` to exclude automatically.
- Is there any way that I can import environment variables like $PGPASSWORD so that I don't have to add the variable each time? 
- Once I define a variable at the top of the `atlas.hcl`, I'm required to pass it in every time. Is there a way to make a variable scoped to a specific environment? When I'm doing a `atlas schema diff` between my `schema.hcl` and my migration folder I shouldn't have to provide a password
- It would be nice if I could use a bare `env` block to specify global configuration (like the location of my schema.hcl and my exclude options and my dev URL), but there doesn't seem to be any hierarchy and I need to include everything in every environment block.
- Your documentation on project configs is wrong when you click on the `Postgres` button. It shows a value of `src = "./project/schema.hcl"`. If you use that, you'll get an `Error: parse "/path/to/schema.hcl": invalid port "/path/to/schema.hcl" after host` error. The config should be specified as `file://schema.hcl`. Relative path doesn't work.

Here's my `atlas.hcl` project config. It uses my config just fine when I run `atlas migrate diff changeName --env local --var password=%PGPASSWORD%` or `atlas migrate apply --env local`

```HCL
variable "password" {
  type = string
}

 env "local" {
    // Define the URL of the database which is managed
    // in this environment.
    url = "postgres://postgres:${var.password}@localhost:5432/mph?sslmode=disable"

    // Declare where the schema definition resides.
    // Also supported: ["multi.hcl", "file.hcl"].
    src = "file://schema.hcl"

    // Define the URL of the Dev Database for this environment
    // See: https://atlasgo.io/concepts/dev-database
    dev = "docker://postgres/14"

    exclude = ["sqitch*", "atlas_schema_revisions*"]

    migration {
        // URL where the migration directory resides. Only filesystem directories
        // are currently supported but more options will be added in the future.
        dir = "file://migrations"

        // An optional version to start the migration history from. This replicates
        // the sqitch baseline. Read more https://atlasgo.io/versioned/apply#existing-databases
        baseline = "20230530113706"
    }
}
```

**Comment by a8m** [comment]
Hey, @robarchibald 👋 

I've added two PRs to update the documentation + example of using the `exclude` and `dev` options in `atlas.hcl` (both options work with `schema diff`). #1714, #1715

> Is there any way that I can import environment variables like $PGPASSWORD so that I don't have to add the variable each time?

You can get an environment variable like [this](https://github.com/ariga/atlas/blob/cd6354f/cmd/atlas/internal/cmdapi/project_test.go#L74):

```hcl
locals {
  pass = getenv("PGPASSWORD")
}

env "local" {
    url = "postgres://postgres:${local.pass}@localhost:5432/mph?sslmode=disable"
}
```

> It would be nice if I could use a bare env block to specify global configuration (like the location of my schema.hcl and my exclude options and my dev URL), but there doesn't seem to be any hierarchy and I need to include everything in every environment block.

You can use ["unlabeled `env` blocks"](https://atlasgo.io/atlas-schema/projects#flags) in case it helps:

```hcl
env {
  name = atlas.env
  url = local.url
  dev = var.dev
  exclude = local.exclude
}
```

Closing, but feel free to ping me on our [Discord](https://discord.gg/zZ6sWVg6NT) in case you need further help with Atlas.
