### ISSUE TITLE
Test shipped with v0.12.0 fails

### ISSUE THREAD

**Issue by silasdavis** [ariga/atlas#1709]
The tests on the v0.12.0 tag fail with:

```
[1/0/18 built] building atlas-0.12.0 (buildPhase): Building subPackagerror: builder for '/nix/store/y9sh6hn9xrh1sv4m0qbzymcdnf0sp5xx-atlas-0.12.0.drv' failed with exit code 1;
       last 10 log lines:
       >                                   +++ Actual
       >                                     @@ -4,3 +4,3 @@
       >                                  DirName: (string) (len=19) "migrations/v1/mysql",
       >                                    - AtlasVersion: (string) (len=23) "Atlas CLI - development",
       >                                   + AtlasVersion: (string) (len=17) "Atlas CLI v0.12.0",
       >                                   Target: (cloudapi.DeployedTargetInput) {
       >                     Test:           TestMigrate_ApplyCloudReport/NoPendingFiles
       > FAIL
       > FAIL ariga.io/atlas/cmd/atlas/internal/cmdapi        30.202s
       > FAIL
```

I'm trying to package this for NixOS where we run the test by default, any chance you could push a v0.12.1 fixing this test?

**Comment by a8m** [comment]
Hey @silasdavis 👋 
Tests are passed in our master branch. How do you run these `go test`?

**Comment by silasdavis** [comment]
This is an artefact of how is is being built under nixpkgs...

I can produce with the following

```shell
cd cmd/atlas
go test -ldflags "-s -w -X ariga.io/atlas/cmd/atlas/internal/cmdapi.version=v0.12.0" ./...
```

The build I am using is a variant of: https://github.com/NixOS/nixpkgs/pull/201531/files#diff-e3224a516b3c2c5f40d9546e891638b264c80b536f2888e92b5ed164bef2bb23R21-R25 (implemented by: https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/go/package.nix)

So this is a result of injecting the version and running the tests with the version injected.

Clearly this is the right thing to do when building the binary, but arguably not the right thing to do when running the tests. I'm not sure how easy that would be to change in nixpkgs, I suppose the logic is to test with the same `ldflags` are the binary release.

Arguably not a bug, but pushed a 'fix' that would be helpful for our packaging
