### ISSUE TITLE
I get "server does not allow insecure connections, client must use SSL/TLS" when connecting to PlanetScale's MySQL

### ISSUE THREAD

**Issue by 205g0** [ariga/atlas#1717]
Pretty much the title and tried with `atlas schema inspect -u <my db-url>`. FWIW, this url works with other clients.

**Comment by rotemtam** [comment]
Hey @205g0  

Thanks for reaching out.

Not near a keyboard atm, so haven't tested this recently, but looking at Planescale's own blogpost on the topic https://planetscale.com/blog/declarative-mysql-schemas-with-atlas-cli#generate-the-schema-definition-file

Looks like this should work:

"mysql://<USERNAME>:<PASSWORD>@<ACCESS HOST URL>/hotels_db?tls=true"

Let me know if you need further help.
