### ISSUE TITLE
Support SQLite table options - `WITHOUT ROWID` and `STRICT`

### ISSUE THREAD

**Issue by CathalMullan** [ariga/atlas#1724]
SQLite has 2 table-level options that be can set:

- [STRICT](https://www.sqlite.org/stricttables.html)
- [WITHOUT ROWID](https://www.sqlite.org/withoutrowid.html)

It would be nice to be able to enable these through Atlas HCL.

**Comment by ozanmakes** [comment]
Interested in this as well. Is there a workaround for this?

**Comment by a8m** [comment]
Hey! This was resolved a long time ago. You can define a table this way:

```hcl
table "users" {
  schema = schema.main
  column "id" {
    null = false
    type = int
  }
  without_rowid = true
  strict        = true
}
```

Closing, but please reopen if you encounter issues with this.

**Comment by ozanmakes** [comment]
Fantastic, thank you!
