### ISSUE TITLE
Read db url from `.env` file

### ISSUE THREAD

**Issue by 205g0** [ariga/atlas#1742]
Maybe I missed that feature but in many frameworks (especially in the JS/TS space) `.env` files are very common. They have all the local env vars (depending on the production target, sometimes also production vars) in standard Bash notation and these get preloaded by the respective framework. The file doesn't get committed and is ignored by .gitignore.

Is this possible? Instead of passing `-u <some url>`, e.g. something like `--dotenv DB_URL`

The alternative would be to create a atlas.hcl file with the url BUT we wouldn't want to commit this because it contains sensitive data. And the data would be redundant to our .env file. So, when a new dev env is setup the developer needs to manually setup .env and atlas.hcl which is no dealbreaker but having just .env for all would be neat.
```hcl
env "local" {
  url = "mysql://root:pass@:3306/"
}
```

Edit: Or could we make atlas.hcl read from .env? Then we can use atlas.hcl files for further config and commit them without disclosing secrets?

**Comment by silasdavis** [comment]
There is `getenv` function you can use in HCL, for example:

```
variable "DB_URL" {
  type    = string
  default = getenv("DB_URL")
}

env "local" {
  url = var.DB_URL
}
```
This allows you to override on the command line, you can also just do `url = getenv('DB_URL')`

**Comment by masylum** [comment]
I face the same challenge. I don't want to have to pass the variables every single time. Perhaps we could incorporate https://github.com/joho/godotenv to easily add support for `.env`?

**Comment by maslennikov** [comment]
I agree with @205g0 's arguments in #1743 about some node ecosystem patterns missing here. For me, working with full stack javascript projects, `.env` is a very natural way to manage my dev and deployment environments. Almost every popular tool supports it in some way, and I without second thought expected it to 'just work'. 

Combined with the fact, that sometimes I have to manually duplicate variables from global config file into cli args (like `schema diff --from --to`), the plumbing becomes awkward.

For my purposes I came to a wrapper shell script `atlas.sh` with something like this:
```bash
#!/bin/bash

: ${ENV_FILE:=".env"}
: ${ATLAS_SCHEMA_DIR:="schema"}
: ${ATLAS_MIGRATIONS_DIR:="migrations"}

if [[ -f "$ENV_FILE" ]]; then
  export $(cat "$ENV_FILE" | xargs)
fi

# allow devs manually adjusting schemas and migrations without need of hash manipulation
if [[ ${NODE_ENV:-"development"} == "development" ]]; then
  atlas migrate hash --dir "file://${ATLAS_SCHEMA_DIR}"
  atlas migrate hash --dir "file://${ATLAS_MIGRATIONS_DIR}"
fi

atlas "$@"
```

Maybe it will help someone coming with same questions.

**Comment by a8m** [comment]
For anyone revisiting this issue, here's a brief recap. Currently, we have three methods to read environment variables from `.env` files:

1\. Plain HCL - Simple and effective for most cases:
 ```hcl
variable "envfile" {
  type    = string
  default = "/path/to/.env/file"
}

locals {
  envfile = {
    for line in split("\n", file(var.envfile)): split("=", line)[0] => regex("=(.*)", line)[0]
    if !startswith(line, "#") && length(split("=", line)) > 1
  }
}

env {
  name = atlas.env
  url = local.envfile["DATABASE_URL"]
}
```
2\. Using the [`external` data source](https://atlasgo.io/atlas-schema/projects#data-source-external) lets users execute programs to read the `.env` (or any other) info and integrate its output into `atlas.hcl` - This method allows users to choose their favorite `.env` reader/parser:
```hcl
data "external" "envfile" {
  program = [
    "npm",
    "run",
    "envfile.js"
  ]
}

locals {
  envfile = jsondecode(data.external.envfile)
}

env "local" {
  src = local.envfile.DATABASE_URL
}
```
3\. Several `.env` readers, like `dotenv` or `godotenv`, provide a CLI version that can execute commands with the loaded environment variables. For example:
```bash
dotenv -- atlas schema inspect --env dev
```
```hcl
env "dev" {
  src = getenv("DATABASE_URL")
}
```

The reason we don't back any official `.env` readers right now, is because our future plans are to let developers write and publish external data sources, similar to what TF users do with providers. Using this method, we aren't limited to one specific implementation and can potentially support all of them.

Closing, as there's no action to take here, but I'll keep the issue updated with further developments.

**Comment by letavocado** [comment]
If you're encountering an error like:

`Error: postgres: querying system variables: pq: SSL is not enabled on the server`

use 
```hcl
locals {
  envfile = {
    for line in split("\n", file(var.envfile)) :
    trimspace(slice(split("=", line), 0, 1)[0]) => trimspace(join("=", slice(split("=", line), 1, length(split("=", line)))))
    if !startswith(trimspace(line), "#") && length(split("=", line)) > 1
  }
}
```
in your `atlas.hcl`


`full example`
```hcl
variable "envfile" {
  type    = string
  default = "./.env.local"
}

locals {
  envfile = {
    for line in split("\n", file(var.envfile)) :
    trimspace(slice(split("=", line), 0, 1)[0]) => trimspace(join("=", slice(split("=", line), 1, length(split("=", line)))))
    if !startswith(trimspace(line), "#") && length(split("=", line)) > 1
  }
}

env "local" {
  name = atlas.env
  src = "file://data/db/schema.sql"

  url  = local.envfile["DATABASE_URL"]
  dev = "docker://postgres/16/dev"

  migration {
    dir = "file://data/db/migrations"
  }
}
```
