### ISSUE TITLE
Add an option to "atlas migrate lint" to lint all migrations

### ISSUE THREAD

**Issue by mortenson** [ariga/atlas#1744]
Since linting is fairly fast, it seems like it'd be nice to have the default behavior be to lint all migrations, or to add a new option like `--all`.

**Comment by mortenson** [comment]
Ah, I didn't realize it wasn't completely static, feel free to close this if it's not possible.

**Comment by a8m** [comment]
Hey @mortenson 👋 

The `migrate lint` command accepts the `--latest` flag. You can give it a high number or just the number of SQL files in the migration directory. 

```bash
atlas migrate lint \
  --env local \
  --latest $(ls migrations/*.sql | wc -l)
```

BTW, I saw your tweet and just wanted to update you that Atlas works both with sqlc and goose (using the `?format=goose` / `format=goose` option), in case it's still relevant. https://atlasgo.io/guides/frameworks/sqlc-versioned

Closing, but please feel free to reopen or join our [Discord](https://discord.gg/zZ6sWVg6NT) in case you need more help with this.
