### ISSUE TITLE
`atlas schema inspect` DX for SQL output could be improved, it feels like a 2nd-class citizen

### ISSUE THREAD

**Issue by 205g0** [ariga/atlas#1750]
Some nice-to-haves:
- Why this cumbersome `--log '{{ sql . }}'` flag and not just `--format sql` or `-f sql`?
- I'd even make `-f sql` the default but guess it's because I haven't hit any uses case where I'd need HCL
- Then, please format the SQL output, while HCL comes with nice line-breaks, SQL queries come in one line; users need to install an SQL formatter which is no big deal but sometimes you just want to check quickly the current state with the CLI and get those miles-long strings; and you need to save the exported file everytime in your editor again to get it properly formatted

**Comment by a8m** [comment]
Hey @205g0! You can format the SQL indented with additional argument: `{{ sql . "  " }}`.

**Comment by 205g0** [comment]
Wow, nice, this also works with json! Thanks. Since this was the most import thing in the list, I close now. The rest is as said nice-to-have but not really needed because one can call the scripts via aliases and/or package.json scripts and npm run.
