### ISSUE TITLE
COLLATE is missing in the JSON inspect output

### ISSUE THREAD

**Issue by 205g0** [ariga/atlas#1752]
e.g., you have this SQL:
```
CREATE TABLE `products` (
  `id` char(20) NOT NULL COLLATE utf8mb4_bin, 
  ...
```
COLLATE will be in the output if the format is HCL and SQL but not JSON.

**Comment by chrisxiao** [comment]
I had a similar problem，the "CHARACTER SET" and "COLLATE" of column definition will be lost in SQL format

version information:
atlas:
atlas community version v0.12.1-98bb7b9-canary
MySQL:
8.0.33 MySQL Community Server

**Comment by a8m** [comment]
The charset/collate/comment attributes were added to the JSON format in https://github.com/ariga/atlas/pull/2020. A new binary will be available after the PR is merged.

> I had a similar problem，the "CHARACTER SET" and "COLLATE" of column definition will be lost in SQL format

The collation and the charset attributes are not added to the format if the default settings are used.
