### ISSUE TITLE
/atlas: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /atlas)

### ISSUE THREAD

**Issue by joekrill** [ariga/atlas#1759]
The latest Docker image is giving me this error:

```
/atlas: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /atlas)
```

I'm on an M1 Mac, running MacOS 13.4, using Docker Desktop 4.20.1 (110738), Docker Engine 24.0.2, and Docker Compose v2.18.1.

Explicitly using the  previous image - `arigaio/atlas:0.12.0` - fixes the problem. Looks like this may be a regression of #1324?

**Comment by a8m** [comment]
Thanks for reporting this, @joekrill. We're checking this.

**Comment by masseelch** [comment]
Hey @joekrill, thank you for raising this and sorry for the inconveniences.

I have fixed the build.
