### ISSUE TITLE
Altering Column Name Recreates Enum Type In Migration

### ISSUE THREAD

**Issue by dhoizner** [ariga/atlas#1775]
Hello! 

I am running into an issue with versioned migrations around PostgreSQL enum types, it seems that the generated migration tries to recreate the PG type when the column name is changed.

Steps to reproduce:
1. Create an enum and a table with a column that references it in a SQL schema file:

```sql
CREATE TYPE status_enum AS ENUM (
    'a',
    'b'
);

CREATE TABLE test (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    status status_enum NOT NULL
);
```
2. Generate a versioned migration with atlas.
3. Rename the column that references the custom type in the SQL schema file:

```sql
CREATE TYPE status_enum AS ENUM (
    'a',
    'b'
);

CREATE TABLE test (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    status_renamed status_enum NOT NULL
);
```

4. Generate a migration to apply the column rename.

This causes the `CREATE TYPE` statement to be present in both migrations, and results in an error when trying to create a type that already exists.

`atlas version` output:

```sh
atlas version
atlas version v0.12.1-b781e99-canary
https://github.com/ariga/atlas/releases/latest
```

**Comment by a8m** [comment]
Thanks for reporting this, @dhoizner. I'll give it a look later today/tomorrow and will update you.
