### ISSUE TITLE
[mysql] BUG, Atlas doesn't know the difference between FOREIGN KEY and FOREIGN KEY CONSTRAINTS and crashes

### ISSUE THREAD

**Issue by 205g0** [ariga/atlas#1796]
Former is a FOREIGN KEY without CONSTRAINT. Atlas just adds a CONSTRAINT key word without being asked. You need constraint-less FKs because:

- Some providers like PlanetScale do not allow foreign keys constraints but _do allow_ foreign keys
- You still declare foreign keys as such without the contraints to have indexes autogenerated
- and have a mysql check if types exactly match between referenced ids, so you have at least a check on table creation

So, now if you have ni your declaration file, e.g.:
```sql
CREATE TABLE `items` (
  ...
  `user_id` BIGTINT NOT NULL,
  ...
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) -- without any CONSTRAINT!!
)...
```

Atlas crashes with `Error: create "items" table: Error 1105 (HY000): foreign key constraints are not allowed, see https://vitess.io/blog/2021-06-15-online-ddl-why-no-fk/` because it just included a CONSTRAINT in its query.

**Comment by a8m** [comment]
Hey @205g0,
I'm pretty sure this happens because the dev-database (provided with `--dev-url`) auto creates the foreign-key constraints, and Atlas uses it to convert the provided raw SQL files and statements into the Atlas _"schema graph"_. 

- What dev-database do you use?
- What is the output of `show create table items` from Vitess?

I never tested it on Vitess or PlanetScale, but we do have a special code for TiDB in Atlas.

**Comment by a8m** [comment]
> Some providers like PlanetScale do not allow foreign keys constraints but do allow foreign keys

I wonder what do foreign-keys mean in this case? Is it just for documentation purposes or is the database has any special handling for it? Because, if it's just for docs, you can also use inline `REFERENCES` clauses which are ignored by MySQL.

**Comment by 205g0** [comment]
You are right, closing.

For the record: Even when entered directly into Vitess/PS, I get this same error. So, PS recommends to just use KEY to have the index created. Then, the user still needs to ensure that PK and FK types exactly match.

Still, thanks for the quick support!
