### ISSUE TITLE
Parsing string from runtimevar as json object

### ISSUE THREAD

**Issue by arkadeepsaha-ten** [ariga/atlas#1797]
I have a secret store in AWS Secrets Manager that returns as a json format when using the runtimevar data source

```
data "runtimevar" "secret" {
  url = "awssecretsmanager://appname/secrets?region=ap-southeast-2"
}
```

in this case, the value returned in `secret` looks as follows `"{\"key1\":\"secret1\",\"key2\":\"secret2\"}"` which is a string representation of a JSON object. How would I extract the value of `key1`, if that is the only thing I require?

I could not find any documentation regarding the same in this page: https://atlasgo.io/atlas-schema/projects#data-source-runtimevar

**Comment by a8m** [comment]
Hey @arkadeepsaha-ten 👋 

I think you can use `jsondecode(...).key`, but I'll try to provide a fully working example later today.

**Comment by arkadeepsaha-ten** [comment]
Hi @a8m 
Thank you. 

This works, but adding a small not for the same in docs would be helpful.
