### ISSUE TITLE
Missing schema comment (on Postgres)

### ISSUE THREAD

**Issue by nbenn** [ariga/atlas#1819]
When setting up as

```sql
CREATE SCHEMA "foo";
COMMENT ON SCHEMA "foo" IS 'bar';
```

I get from `atlas schema inspect`

```
schema "foo" {
}
schema "public" {
}
```

Am I wrong to expect something along the lines of

```
schema "foo" {
  comment = "bar"
}
schema "public" {
}
```

(using atlas version v0.12.1-17d97d4-canary)?

**Comment by nbenn** [comment]
That was quick. Thanks!

**Comment by a8m** [comment]
Sure. Thanks for reporting it!
