### ISSUE TITLE
Support of views and functions

### ISSUE THREAD

**Issue by althaf004** [ariga/atlas#1842]
While generating schema migrations, we currently only obtain scripts related to tables. Views and functions are not included in the script. I would like to know if this will be a feature in upcoming versions or if there are any reasons behind this decision.

**Comment by rotemtam** [comment]
Hi @althaf004,

Support for views is coming really soon 😍 

Duplicate of:
https://github.com/ariga/atlas/issues/1373

Closing

**Comment by linzhiq** [comment]
@rotemtam any updates on including functions as well?

**Comment by althaf004** [comment]
if functions where included, entire migration would be completed. shall we expect this any time sooner?
