### ISSUE TITLE
When using "atlas migrate lint" on PostgreSQL, it shows concurrent index violations, but there are none

### ISSUE THREAD

**Issue by vmrm** [ariga/atlas#1851]
```
# atlas migrate lint --dir file://migrations --dev-url "docker://postgres/15/test" --latest 1
20230712165923_create_indexes.sql: concurrent index violations detected:

	L2: Creating index "bookings.facid_memid" non-concurrently causes write locks on the "bookings" table

```
But in migration we do have this:
`# cat migrations/20230712165923_create_indexes.sql
-- Create index "bookings.facid_memid" to table: "bookings"
CREATE INDEX CONCURRENTLY "bookings.facid_memid" ON "cd"."bookings" ("facid", "memid");`

**Comment by a8m** [comment]
Hey @vmrm 👋 

Can you share what OS and Atlas version you use (run `atlas version`)? Thanks

**Comment by vmrm** [comment]
Hi, @a8m , I'm using the Ubuntu 22.04.2 LTS and `# atlas version
atlas version v0.12.1-972da10-canary
https://github.com/ariga/atlas/releases/latest`

**Comment by a8m** [comment]
Thanks for reporting this. I was able to reproduce this and it is fixed in https://github.com/ariga/atlas/pull/1852.

I'll merge the PR once it's green and a new version will be available later today.

**Comment by vmrm** [comment]
Thanks a lot!
