### ISSUE TITLE
invalid userinfo when use password include special characters

### ISSUE THREAD

**Issue by calvin2021y** [ariga/atlas#1860]
when call atlas with password like this `+ysT*Au-83b57X9^t2`, get `net/url: invalid userinfo` error.

is there a work around ? 

```sh
atlas schema apply -u mysql://test:"+ysT*Au-83b57X9^t2"@mysql:3306/test-f ./test.hcl -s test
atlas schema apply -u mysql://test:+ysT*Au-83b57X9^t2@mysql:3306/test  -f ./test.hcl -s test
```

**Comment by a8m** [comment]
Hey @calvin2021y 👋🏻

Yes, please check out this comment https://github.com/ariga/atlas/issues/1034#issuecomment-1212003157:

> As the command accepts a URL, the standard way for dealing with odd characters is using URL encoding, see IETF [RFC 1738](https://www.rfc-editor.org/rfc/rfc1738), (see section 2.2) which defines URLs formally. I don't think Atlas should encode the URL for the user as this is a one-time operation (e.g doesn't change unless the password itself changes).

**Comment by calvin2021y** [comment]
even so,  add a arguments to accept raw password will be much easy for users.

**Comment by a8m** [comment]
Agree. That’s why we added [`urlescape`](https://github.com/ariga/atlas/blob/master/schemahcl/stdlib.go#L162) to [Atlas configuration](https://atlasgo.io/atlas-schema/projects).

**Comment by calvin2021y** [comment]
Can i use this from bash command without change code ?

**Comment by a8m** [comment]
Create an `atlas.hcl` file and use the `urlescape` function. The URL (of an actual database) should not be stored in the file but injected as a variable or read from some secrets store ([Atlas supports this too](https://atlasgo.io/atlas-schema/projects#data-source-runtimevar)). For example:

```hcl
variable "url" {
  type     = string
  default = "<local url"> // Can also be defined as: getenv("DATABASE_URL")
}

env "mysql" {
  url  = urlescape(var.url)
  src = "file://test.hcl"
  # In case you use and want to define a dev-database.
  dev = "docker://mysql/8/dev"
}
```

```bash
atlas schema apply \
  --env mysql \
  --var "url=mysql://test:+ysT*Au-83b57X9^t2@mysql:3306/test"
```

**Comment by calvin2021y** [comment]
thanks for the tips,  after some research I find this tools work suit me need.

```sh
trurl --url mysql://MYSQL_HOST --set port=$MYSQL_PORT --set user=$MYSQL_USER --set password=$MYSQL_PWD
```

https://github.com/curl/trurl
