### ISSUE TITLE
Integration of AtlasGo with an existing target database

### ISSUE THREAD

**Issue by althaf004** [ariga/atlas#1881]
I have a production database with some tables in it. Is it possible to begin using the AtlasGo Migration CLI to handle the script?

i tried to generate the script using statement like below

```
atlas migrate diff jobs   --dir "file://migrations"   --to {DB_DETAILS}  --dev-url "docker://postgres/15"
```

This action generated an SQL file in the migration folder. I then executed 'atlas apply' with an empty database, which applied all the changes.

To compare this with the target database and execute only the necessary scripts how can Atlas help me out.

**Comment by rotemtam** [comment]
Hi @althaf004 

Well done on creating this initial migration file, which we call a "baseline" migration. 

If you try to `migrate apply` this on a database that already contains the tables, Atlas will fail and tell you that the database isn't clean. 

The solution is to use the `--baseline` option. 

You can read more about it [here](https://atlasgo.io/versioned/apply#baseline-migration).

Closing but let me know if you need further assistance.
