### ISSUE TITLE
external_schema doesn't work with `atlas schema diff`

### ISSUE THREAD

**Issue by jerluc** [ariga/atlas#1924]
# Overview

In my testing, I can easily get `atlas migrate diff --env testing` and `atlas schema apply --env testing` working with an `atlas.hcl` config file that looks like:

```hcl
data "external_schema" "orm" {
  program = [
    "/path/to/program",
    "arg1"
  ]
}

env "testing" {
  src = data.external_schema.orm.url
  url = "..."
  dev = "..."
}
```

However, when running `atlas schema diff  --env testing`, I get the following error:

```
Error: required flag(s) "from", "to" not set
```

# What I expected

I expected that these flags would have been populated from the `atlas.hcl` config file:

- `--from` should come from `url`
- `--to` should come from `src`

Is this expected behavior?

**Comment by a8m** [comment]
Hey @jerluc 👋 

If you want to use `--from` as `url` and `--to` as `src`, you can use `schema apply --env testing --dry-run` to achieve this. 

The `schema diff` command currently supports reading its states from the command URLs, but I plan to add support reading it from data sources like this: `data://type/name` in the future.
