### ISSUE TITLE
Atlas cannot parse 'int unsigned' correctly on MySQL

### ISSUE THREAD

**Issue by chrisxiao** [ariga/atlas#1937]
when a column definition is like ‘xxx int unsigned’，Atlas cannot parse it correctly. 
error info as follow:
Error: mysql: parse "unsigned" to int: strconv.Atoi: parsing "unsigned": invalid syntax

command：
atlas schema diff
atlas schema inspect

version info:
atlas community version v0.12.1-98bb7b9-canary
8.0.33 MySQL Community Server

**Comment by a8m** [comment]
Another question: do you compare two different MySQL versions? If so, what are these versions?

**Comment by chrisxiao** [comment]
Sorry, I didn't describe clearly. the table definition is like ：

CREATE TABLE `test` (
  `max_min` double unsigned zerofill DEFAULT NULL COMMENT 'max-min'
) ENGINE=InnoDB ;

the two database instances is the same version

**Comment by a8m** [comment]
Thanks for the answer, @chrisxiao. I merged a fix and I'm going to build a new binary soon. I'll let you know when it's ready.

**Comment by chrisxiao** [comment]
ok, thanks!

**Comment by a8m** [comment]
A new binary was released. I'll appreciate if you can pull it and report if that solves the issue.

Thanks 🙏
