### ISSUE TITLE
CLI: atlasgo.sh installer ignoring `ATLAS_FLAVOR="community"`

### ISSUE THREAD

**Issue by marcozac** [ariga/atlas#1945]
Currently the script (https://atlasgo.sh/) builds the filename checking the `--community` flag and only if `ATLAS_FLAVOR` is different than "C_FLAVOR_COMMUNITY", ignoring the case where `ATLAS_FLAVOR` is "community".

> Lines 119:123
> ```bash
> if [ "$_community" = true ]; then
>  _file="$_file-$C_FLAVOR_COMMUNITY"
> elif [ "$ATLAS_FLAVOR" != "$C_FLAVOR_COMMUNITY" ]; then
>  _file="$_file-$ATLAS_FLAVOR"
> fi
> ```

Since `ATLAS_FLAVOR` default value is `C_FLAVOR_COMMUNITY`, a possible, simple fix might be:

- Remove the `ATLAS_FLAVOR` default value at line 18
  > ```diff
  > - ATLAS_FLAVOR="${ATLAS_FLAVOR:-$C_FLAVOR_COMMUNITY}"
  > + ATLAS_FLAVOR="${ATLAS_FLAVOR:-""}"
  > ```
- Explicitly check for `ATLAS_FLAVOR` value at lines 119:123
  > ```diff
  > - if [ "$_community" = true ]; then
  > + if [ "$_community" = true ] || [ "$ATLAS_FLAVOR" = "$C_FLAVOR_COMMUNITY" ]; then
  >   _file="$_file-$C_FLAVOR_COMMUNITY"
  > - elif [ "$ATLAS_FLAVOR" != "$C_FLAVOR_COMMUNITY" ]; then
  > + elif [ "$ATLAS_FLAVOR" != "" ]; then
  >   _file="$_file-$ATLAS_FLAVOR"
  > fi
  > ```

**Comment by rotemtam** [comment]
Hey @marcozac 

Thanks for reaching, I tested locally and I can confirm the issue. While we work on a fix you can use one of the alternative installation methods that should work. See [here](https://atlasgo.io/community-edition) for the full list

![Screen Shot 2023-08-06 at 16 31 14](https://github.com/ariga/atlas/assets/1522681/4d03a289-1a50-4d87-982f-50289ad8fa5b)

**Comment by rotemtam** [comment]
Hey @marcozac,

@giautm just merged a fix, can you try again?

**Comment by marcozac** [comment]
Hi @rotemtam!

It seems it is still not working:

<img width="593" alt="Screenshot 2023-08-06 at 21 08 24" src="https://github.com/ariga/atlas/assets/78536721/aadacfc9-11ce-44ab-bbca-8d8a2f8f22f3">

**Comment by marcozac** [comment]
No ok, my fault: `ATLAS_FLAVOR` is not available in the new version of the script.

Should be enough to mention the requirement of the `--community` flag in the docs [here](https://atlasgo.io/community-edition).

**Comment by rotemtam** [comment]
You're right :-)

Didn't notice we didn't hit merge on https://github.com/ariga/atlas/pull/1947
