### ISSUE TITLE
Support libsql+ws:// scheme for local environment libSQL databases

### ISSUE THREAD

**Issue by george-lim** [ariga/atlas#1951]
Atlas currently supports `libsql+wss://` scheme for managing Turso databases, but there isn't a way to manage a self-hosted libSQL database (running in a Docker container for example) for local environments, unless it is secured by SSL.

It would help a lot for local migration testing if the non-secured scheme were supported as well.

**Comment by a8m** [comment]
Does libsql support connecting to `ws`? Also, can you elaborate on why not use plain SQLite for local development? e.g., `sqlite://file.db`/`sqlite://file?mode=memory`?

**Comment by george-lim** [comment]
> Does libsql support connecting to ws?

Absolutely! Turso uses [sqld](https://github.com/libsql/sqld) under the hood to manage the libSQL database in server mode. sqld supports [http or ws schemes](https://github.com/libsql/sqld/blob/be9a6efc48948179427fcbee4d4a8e391a943ac6/docs/BUILD-RUN.md?plain=1#L128).

> Also, can you elaborate on why not use plain SQLite for local development?

For my product, I am self-hosting sqld for all environments instead of using Turso. I want to do this for two reasons:
1. I want to ensure that all environments run as close to the same as possible for both simplicity and also consistency
2. There are [features](https://github.com/libsql/libsql/blob/main/doc/libsql_extensions.md) in libSQL that are not present in SQLite

In my specific case, the problem I'm running into is that all of my containers sit behind `nginx`, which is responsible for SSL termination. I want to have all of my internal services communicate without SSL, which includes Atlas (for local development).

For staging and production environments I will be using the [deploy action](https://github.com/ariga/atlas-deploy-action) which will point to a wss:// URL, so that won't be a problem

**Comment by george-lim** [comment]
Hey @a8m sorry to bump, but any thoughts on this? I can make a PR if you'd like. This blocks a project that I am currently working on

**Comment by george-lim** [comment]
@a8m Is there something I can do to help this change get through? My company would really like to get this in because Atlas is the only migration tool that supports libSQL (Turso) out of the box at the moment

**Comment by zestsystem** [comment]
@a8m @george-lim Facing the same issue not being able to utilize local development of Turso. Can the changes be merged? Being able to develop with a local file without having to connect to a real hosted instance is a big part of what makes Turso great.

**Comment by george-lim** [comment]
This is now merged!
