### ISSUE TITLE
duplicate table names breaks schema inspect

### ISSUE THREAD

**Issue by jjdonov** [ariga/atlas#1973]
`atlas schema inspect` fails when there are duplicate table names _across_ schemas. For example, given a postgres db like:

```sql
CREATE SCHEMA "foo";
CREATE TABLE "foo"."foo" (
	"id" uuid not null primary key
);

CREATE SCHEMA "bar";
CREATE TABLE "bar"."foo" (
	"foo_id" uuid not null primary key
);

ALTER TABLE "bar"."foo" 
ADD CONSTRAINT "fk_foo_bar" FOREIGN KEY ("foo_id") 
REFERENCES "foo"."foo" ("id");

```
Atlas will fail to resolve the foreign key:

```
$> atlas schema inspect --url "postgres://user:pass@localhost:5455?sslmode=disable"
Error: postgres: referenced column "id" was not found for fk "fk_foo_bar"
```

I _think_ this is happening because [this if/else block](https://github.com/ariga/atlas/blob/b3b1ccd46dca62c7328471eee106e2afd6bea32b/sql/internal/sqlx/sqlx.go#L139-L148) doesn't disambiguate `foo.foo` from `bar.foo`

## Reproduction

The issue can be reproduced using this project: [jjdonov/atlas-1973](https://github.com/jjdonov/atlas-1973)

**Comment by a8m** [comment]
Thanks for reporting this, @jjdonov. I'll give it a look and update you if I need help reproducing this.
