### ISSUE TITLE
uuid_generate_v4() does not exist error

### ISSUE THREAD

**Issue by fabiorizzomatos** [ariga/atlas#1976]
Hi, 
I'm trying to use Atlas in my go project.

When i run atlas migrate diff --env gorm  i got this error:

Error: sql/migrate: read migration directory state: sql/migrate: execute: executing statement "CREATE TABLE \"tenants\" (\"created_at\" timestamptz,\"updated_at\" timestamptz,\"id\" uuid DEFAULT uuid_generate_v4(),\"name\" text,\"description\" text,\"db_name\" text,\"domain\" text,PRIMARY KEY (\"id\"));" from version "schema": pq: function uuid_generate_v4() does not exist

I have check, and my database has the extension:

database=# CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION
database=# select uuid_generate_v4();
           uuid_generate_v4           
--------------------------------------
 f276d0fb-014f-4735-b892-4c734918ef19
(1 row)

What i'm doing wrong? 

Thanks!

**Comment by crossworth** [comment]
Hello @fabiorizzomatos, does the [`dev database`](https://atlasgo.io/concepts/dev-database), has the extension as well?

Or maybe, you could use the [`gen_random_uuid function`](https://www.postgresql.org/docs/current/functions-uuid.html) to avoid having to use extensions.

**Comment by fabiorizzomatos** [comment]
Hi @crossworth !

I guess not. Just using the default ones.  Would you know how i do this?

**Comment by egandro** [comment]
I have some (braindead) code as workaround for that.

Please ping me if you are interessted.

Atlas --dev-db thingy doesn't support extensions or init scripts at the moment. So you have to do some (very very ugly nasty hacks).

**Comment by fabiorizzomatos** [comment]
@egandro Cool, i would like to have. I'm using citus and uuid extensions only.

**Comment by a8m** [comment]
A simple workaround for this atm, is to spin up a local Postgres container, install there the extensions your schema rely on (e.g., with init script) and use it as a dev-database. The idea here is that this container represents the same production database baseline.

We plan to support extensions in the next version.

**Comment by crossworth** [comment]
I assume you are using something [similar to this](https://atlasgo.io/blog/2023/06/28/external-schemas-and-gorm-support#standalone-mode):

```hcl
env "gorm" {
  src = data.external_schema.gorm.url
  dev = "docker://postgres/15/dev" # <--- dev database here
  migration {
    dir = "file://migrations"
  }
  format {
    migrate {
      diff = "{{ sql . \"  \" }}"
    }
  }
}
```

In that case I think there is a easy way to handle it, first is to not use docker (at least, not in this way),  start a local docker and create the extensions needed (a local database works as well), after that use it on the `dev` part.

@egandro Hi, please, share here with us if possible, this way others can see as well.

**Comment by egandro** [comment]
Again :) this doesn't fix atlas - this is just >> my << hack.

I don't make it work in "you" world. Just the idea how to poke around

```bash
./diffschema.sh "postgres://production:production@172.17.0.1:5432/production?sslmode=disable&TimeZone=UTC"
```

./diffschema.sh is
```bash
#!/bin/bash

LOCAL_DATABASE="$1"

SCHEMA_FILE="./schema.hcl"

IMAGE=postgres:15.3
CONTAINER_NAME=diffschema
POSTGRES_PASSWORD=diffschema
POSTGRES_USER=diffschema
POSTGRES_PORT=15433
PG_URL="postgres://"${POSTGRES_USER}":"${POSTGRES_PASSWORD}"@172.17.0.1:"${POSTGRES_PORT}"/"${CONTAINER_NAME}"?sslmode=disable&TimeZone=UTC"


kill_docker_container () {
    echo "stopping container: ${CONTAINER_NAME}"
    docker rm -f "${CONTAINER_NAME}" 2>/dev/null >/dev/null || true
}

trap kill_docker_container EXIT

kill_docker_container

docker run --name "${CONTAINER_NAME}" -p ${POSTGRES_PORT}:5432 \
    -e POSTGRES_PASSWORD="${POSTGRES_PASSWORD}" \
    -e POSTGRES_USER="${POSTGRES_USER}" -d \
    "${IMAGE}"

sleep 2
docker exec -it "${CONTAINER_NAME}" pg_isready
# add whatever SQL you need here for the temp PG database
docker exec -it "${CONTAINER_NAME}" psql -U "${POSTGRES_USER}" "${CONTAINER_NAME}" -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";'

atlas schema diff \
    --from "${LOCAL_DATABASE}" \
    --to "file://${SCHEMA_FILE}" \
    --dev-url "${PG_URL}" \
    --exclude "atlas_schema_revisions"

```

**Comment by fabiorizzomatos** [comment]
> A simple workaround for this atm, is to spin up a local Postgres container, install there the extensions your schema rely on (e.g., with init script) and use it as a dev-database. The idea here is that this container represents the same production database baseline.
> 
> We plan to support extensions in the next version.

Hi @a8m 

I did it, but i receive now this message:
Error: sql/migrate: taking database snapshot: sql/migrate: connected database is not clean: found schema "citus"

my atlas.hcl:
data "external_schema" "gorm" {
  program = [
    "go",
    "run",
    "-mod=mod",
    "./loader",
  ]
}

env "gorm" {
  src = data.external_schema.gorm.url
  dev = "postgres://user:user@192.168.68.107:54322/database?sslmode=disable"
  migration {
    dir = "file://migrations"
  }
  format {
    migrate {
      diff = "{{ sql . \"  \" }}"
    }
  }
}

**Comment by fabiorizzomatos** [comment]
@crossworth Thanks for helping.

I've tried this: 
`atlas schema apply --env gorm -u "postgres://vindula:vindula@192.168.68.107:5432/vindula?sslmode=disable&search_path=public"`

and still received the error message:

Error: sql/migrate: taking database snapshot: sql/migrate: connected database is not clean: found schema "citus"

Its a database twin, clean, just installed.

Not working using exclude as well.

**Comment by egandro** [comment]
@fabiorizzomatos  your dev-db is not clean not the vindula db

**Comment by crossworth** [comment]
Alright, I have done a few tests:

**Declarative**, setting the `search_path` seems to work:
<img width="1224" alt="image" src="https://github.com/ariga/atlas/assets/1251151/4a140432-00ac-4fe0-8673-54c87d5834b7">

<img width="1221" alt="image" src="https://github.com/ariga/atlas/assets/1251151/6739701d-df66-44b2-93de-f3e8b21fb3b6">

**Versioned**, using the `migrate diff` with `search_path` seems to works as well:
<img width="1088" alt="image" src="https://github.com/ariga/atlas/assets/1251151/9ee55fbf-865f-4675-968d-c3767001589b">

And `apply` works too:
<img width="1202" alt="image" src="https://github.com/ariga/atlas/assets/1251151/9a1a4fe7-08ca-4b01-ad79-911f2fbd5a78">


Maybe you forgot the `search_path` on the `dev`?
```hcl
  dev = "postgres://user:user@192.168.68.107:54322/database?sslmode=disable&search_path=public"
  ```

**Comment by fabiorizzomatos** [comment]
> 
> Maybe you forgot the `search_path` on the `dev`?
> 
> ```terraform
>   dev = "postgres://user:user@192.168.68.107:54322/database?sslmode=disable&search_path=public"
> ```

Bingo! that was my problem. Fixed and it works! Thanks everyone! @crossworth  @egandro
