### ISSUE TITLE
SQL Schema Directory leads to `Error: sql/migrate: read migration directory state`

### ISSUE THREAD

**Issue by maslennikov** [ariga/atlas#1980]
Hello,

I have a clean database and a new project with a following directory structure:
```
my-app/
├─ schema/
│  ├─ 01-my-service-a.sql
│  ├─ 02-my-service-b.sql
├─ migrations/
```

- `schema` dir contains files with valid mysql commands (e.g. create database, create table etc), according to [docs here](https://atlasgo.io/atlas-schema/sql#schema-directory)
- `migrations` dir is empty
- no global `atlas.hcl` config file

## Problem

Trying to execute any of these commands fails with same error message:
```sh
atlas schema diff --from mysql://root:root_secret@localhost:3306 --to file://schema --dev-url 'docker://mysql/8'
# or
atlas migrate diff --dir file://migrations --to file://schema --dev-url 'docker://mysql/8'

# results in:
# Error: sql/migrate: read migration directory state: sql/migrate: execute: validate migration directory: checksum file not found
```

At the same time, when I instead of directory supply `--to file://schema/01-my-service-a.sql` everything works. Trying various globs or some random formats like `--to ./schema/*` wasn't successful neither.

---

Do I need to provide schema dir with some specific syntax to make it work, or is it a bugged behavior?

**Comment by a8m** [comment]
Hey, @maslennikov 👋🏻
All atlas directories should contain the atlas.sum file. To resolve your issue, either run `atlas migrate hash` or drop the directory (if it’s empty) before running `migrate diff`.

**Comment by maslennikov** [comment]
Thank you @a8m, applying `migrate hash --dir file://schema` worked!

It wasn't obvious from the docs that schema directory should be treated the same way as migrations directory. Maybe some mention of this situation on the docs page [here](https://atlasgo.io/versioned/new#recalculating-the-directory-hash) could help?

**Comment by sunilgandipadala** [comment]
hi @a8m,
When I tried to run
atlas migrate diff --env gorm

Error: sql/migrate: read migration directory state: sql/migrate: execute: executing statement 

 from version "schema": Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '&{0xc00013e5a0 <nil> 0 0xc0001fc000 1} <nil>
Data base Connected
CREATE TABLE `u' at line 1

getting this error, even I tried the hashing by specifying the directory,

How can I get rid of this?
