### ISSUE TITLE
migrate diff: object does not have an attribute named "column"

### ISSUE THREAD

**Issue by jjdonov** [ariga/atlas#1984]
I generated my schema using `atlas schema inspect`, then when subsequently trying to run `atlas migrate diff`, I get the following error:

> Unsupported attribute; This object does not have an attribute named "column".

My DB has schemas that share a name with a table in the public schema:
```
table "user" { ... } //user table in public schema
table "user" "address" { ... } //address table in user schema
```
This seems to cause issues when using the HCL format generated by atlas schema inspect  because the qualifier + tableName combo is ambiguous.

## Reproduction

https://github.com/jjdonov/atlas-1984

I was able to create a reproduction by starting with my fully generated schema and deleting all the parts that seemed irrelevant here.

**Comment by a8m** [comment]
Hey @jjdonov 👋 

Can you paste here the SQL you used to generate this schema (the HCL one)? Because qualifiers are added to resources (tables in this case) only if there are duplicate labels (e.g., two "user" tables) and we need to distinguish them on parsing. 

I tried running the following SQL statements, but `atlas schema inspect` generates correct schema for it:
```sql
create table "public"."user"(id serial, primary key(id));
create table "user"."address"(uuid uuid, user_id integer, primary key(uuid), constraint "fk" foreign key (user_id) references "public"."user"(id));
```
```hcl
table "user" {
  schema = schema.public
  column "id" {
    null = false
    type = serial
  }
  primary_key {
    columns = [column.id]
  }
}
table "address" {
  schema = schema.user
  column "uuid" {
    null = false
    type = uuid
  }
  column "user_id" {
    null = true
    type = integer
  }
  primary_key {
    columns = [column.uuid]
  }
  foreign_key "fk" {
    columns     = [column.user_id]
    ref_columns = [table.user.column.id]
    on_update   = NO_ACTION
    on_delete   = NO_ACTION
  }
}
schema "public" {
  comment = "standard public schema"
}
schema "user" {
}
```
