### ISSUE TITLE
If the password contains special characters, the atlas execution fails

### ISSUE THREAD

**Issue by QuanZi123** [ariga/atlas#1985]
When I used atlas, I failed to export the data structure when the password contained @ or #

Executed command:
`atlas schema inspect -u "mysql://root:aG2^eM5#qD@localhost:3306/atlas_test" --format "{{ json . }}" > d:\atlasgo\ttt\result.json`

**Comment by giautm** [comment]
Hello @QuanZi123, you need to encode user:password with the function `encodeURLComponent` function from the browser as described in URI spec. Or access [this link](https://www.urlencoder.org/)

The result will look like this: `encodeURIComponent('aG2^eM5#qD')` -> `aG2%5EeM5%23qD`

**Comment by a8m** [comment]
Hey @QuanZi123 👋🏻

Adding here a link to @rotemtam’s comment: https://github.com/ariga/atlas/issues/1034#issuecomment-1212003157:

> As the command accepts a URL, the standard way for dealing with odd characters is using URL encoding, see IETF [RFC 1738](https://www.rfc-editor.org/rfc/rfc1738), (see section 2.2) which defines URLs formally. I don't think Atlas should encode the URL for the user as this is a one-time operation (e.g doesn't change unless the password itself changes).

**Comment by QuanZi123** [comment]
Thanks
