### ISSUE TITLE
Using valid json in templates

### ISSUE THREAD

**Issue by listepo** [ariga/atlas#2007]
Now, based on the [documentation](https://atlasgo.io/guides/migration-dirs/template-directory#read-data-variables-from-file), when working with templates, you need to use a non-valid `json` and there is no way to use object properties.
It would be great for example
```json
[
  {"name": "Ariel"},
  {"name": "Rotem"}
]
```

```sql
{{ range := .seed_users }}
  INSERT INTO `users` (`role`, `data`) VALUES ('user', '{{ .name }}');
{{ end }}
```

**Comment by a8m** [comment]
Hey @listepo 👋 

Thanks for the feedback. I actually thought about _[JSON lines](https://jsonlines.org/)_ when writing this doc, where each JSON object is terminated by a `\n` character. Maybe this is just my experience, but this is quite a popular format I used when working with other platforms.

**Comment by listepo** [comment]
Hey @a8m, thanks for the quick response. I understand you, then how to get the value from this string as an object/map, not a string?

**Comment by listepo** [comment]
because `{{ $line }}` should return this as a string `"{\"name\": \"Ariel\"}"`
from example: 
```sql
{{ range $line := .seed_users }}
  INSERT INTO `users` (`role`, `data`) VALUES ('user', '{{ $line }}');
{{ end }}
```

**Comment by listepo** [comment]
I think the `csv` format is more suitable for such an implementation

**Comment by a8m** [comment]
The `template_dir` currently supports getting variables as strings, numbers, booleans, or lists of these. I've considered extending it, but I didn't have a use case for it yet. For now, you can use it as the example below, and I'll likely add support for maps in the upcoming days

```hcl
locals {
  seed_users = jsondecode(file("seed_users.json"))
  names = [for user in local.seed_users : user.name]
}

data "template_dir" "migrations" {
  path = "migrations"
  vars = {
    seed_users = tolist(local.names)
  }
}
```

**Comment by listepo** [comment]
@a8m Many Thanks

**Comment by nadeemc** [comment]
Hi @a8m!

Supporting maps in template_dir values would make seeding test data a lot easier. If building that support is a lot of work, a quick option would be to expose a `jsondecode` function to the templates.

This has negative performance implications because it requires decoding each line multiple times to retrieve each key's value. But, it allows the current support for an array of strings to be used for both simple and complex seed data scenarios.

In the test I ran locally, I modified `atlas/cmd/internal/cmdext/cmdext.go` to add a FuncMap to every template:

```go
var funcs = template.FuncMap{
	"jsondecode": func(s string) map[string]any {
		var v map[string]any

		if err := json.Unmarshal([]byte(s), &v); err != nil {
			panic(fmt.Errorf("can not unmarshal %q: %w", s, err))
		}

		return v
	},
}

t := template.New("template_dir").Option("missingkey=error").Funcs(funcs)
```

Then, in our `atlas.hcl` we would have:
```
locals {
  seed_users = split("\n", file("users.jsonl"))
}

data "template_dir" "migrations" {
  path = "migrations"
  vars = {
    seed_users = local.seed_users
  }
}

env "dev" {
  migration {
    dir = data.template_dir.migrations.url
  }
}
```

The data expected in the `users.jsonl` file would be similar to:
```json
{"name":"a8m","email":"a8m@atlasgo.io"}
{"name":"listepo","email":"listepo@github.com"}
{"name":"nadeemc","email":"nadeemc@github.com"}
```

And, in our `timestamp_migration_name.sql` file, we could use the seed data as:
```go
{{ range $line := .seed_users }}
INSERT INTO "users"
(
    "name",
    "email"
)
VALUES
(
    '{{ ($line | jsondecode).name }}',
    '{{ ($line | jsondecode).email }}'
);
{{ end }}
```

Thoughts on that approach?

**Comment by nadeemc** [comment]
Actually, this is possible even without any code changes, so adding this here for reference for others:

```
{{ range $line := .seed_users }}
INSERT INTO "user"
(
    "name",
    "email"
)
VALUES
(
    '{{ $line }}'::json -> 'name',
    '{{ $line }}'::json -> 'email'
);
{{ end }}
```
