### ISSUE TITLE
Running functions from terraform

### ISSUE THREAD

**Issue by althaf004** [ariga/atlas#2035]
Hi Team,

Is it possible to run functions for the database using terraform? it would be great to have a help on this.

Regards

**Comment by masseelch** [comment]
Hello @althaf004,

we have a [Terraform Provider](https://atlasgo.io/integrations/terraform-provider) you can use to include database schema management into your terraform workflow. 

It works both for versioned and declarative workflows. Let me know if you have any further questions.

**Comment by althaf004** [comment]
hey @masseelch , will this migration include functions created under a schema?

**Comment by masseelch** [comment]
Atlas does not support functions (yet). I don't have an exact release date for you, but we want to add support for this soon.

**Comment by giautm** [comment]
Hello @althaf004, what kind of functions do you want to run? That's SQL functions / procedures or something else?

**Comment by althaf004** [comment]
i needed to run SQL functions / procedures

**Comment by althaf004** [comment]
If I'm using AtlasGo to migrate tables and views to the production database, how would you recommend migrating functions to the target database?
