### ISSUE TITLE
SQL Server atlas commands always report failure

### ISSUE THREAD

**Issue by jrmcpeek** [ariga/atlas#2039]
> atlas version v0.13.4-5462430-canary

Using the latest version of atlas and the SQL Server beta driver, any command we run always reports an error, whether successful or not.

This is the typical error message, when no other commands have been run:

```
-- ok (44.314979ms)

  -------------------------
  -- 67.166336ms
  -- 1 migrations 
  -- 2 sql statements
Error: reportMigration Sorry, something went wrong
```

This error message was presented after a previous command _correctly_ resulted in a 401 (host name typo!).

```
  -------------------------
  -- 212.848603ms
  -- 1 migrations 
  -- 2 sql statements
Error: unexpected status code: 401
```

This appears to be purely cosmetic, as `echo $?` always puts out `0` and the command actual does what I would expect it to do.

**Comment by a8m** [comment]
Thanks for reporting this, @jrmcpeek. That because Atlas by default tries to [report deployments](https://atlasgo.io/versioned/intro#applying-migrations) for logged in users. However, this is a local directory and this operation is noop. I will send a patch later today to fix this.

**Comment by Tadimsky** [comment]
I'm seeing this error still - is the fix still coming?

**Comment by a8m** [comment]
@Tadimsky - thanks for the update. @giautm and I will work on it today and update when it's ready.

**Comment by giautm** [comment]
Hello @Tadimsky, @jrmcpeek. To workaround this issue right now, you can provide the `ATLAS_TOKEN` environment variable before running the apply command. It should be working correctly. Like bellow:
```shell
ATLAS_TOKEN=aci_xxx atlas migrate apply --env test
```

I'm on the fix right now.

**Comment by a8m** [comment]
Hey! The problem was solved and a new binary was released.

I appreciate if you can download the latest binary and confirm that the issue was solved on your side. Thanks 🙏🏻

**Comment by jrmcpeek** [comment]
> atlas version v0.14.1-078bbe1-canary

I no longer see error messages after every command.

**Comment by giautm** [comment]
Hello, closing this issue. If you have any questions or another issue. Please contact us.
