### ISSUE TITLE
Atlas visualize doesn't work with beta SQL Server driver

### ISSUE THREAD

**Issue by jrmcpeek** [ariga/atlas#2040]
> atlas version v0.13.4-5462430-canary

When trying use `--visualize` per this [blog post](https://atlasgo.io/blog/2023/08/06/atlas-v-0-13#built-in-schema-visualization), I selected "share privately".

After that, the following error was produced:

```
Error: template: format:1:3: executing "format" at <visualize .>: error calling visualize: unknown driver "sqlserver"
```

**Comment by giautm** [comment]
Hello @jrmcpeek, looks like our cloud doesn't support SQLServer yet. We will working on the support soon and back to you.

**Comment by jrmcpeek** [comment]
Fair enough. Wasn't sure of the expectations since the driver is in beta and the error message looked just like a failure versus "not yet supported".

**Comment by giautm** [comment]
Hello @jrmcpeek, We already support SQL Server on our cloud. Please give try a let me know if you got an issue. <3

**Comment by jrmcpeek** [comment]
> Please give try a let me know if you got an issue. <3

With version `atlas version v0.14.1-078bbe1-canary`

@giautm - This now works for **publishing**, however, I am unable to locate the ERD/visualization in our cloud instance other than through the link generated at publishing time. Is this what is expected?

Additionally, it is _only_ in that view that `SQLSERVER` is listed as a schema option, so I am not able to select it and import a schema through the web interface.

I can make a separate issue / separate issues for these if necessary.
