### ISSUE TITLE
Atlas Migrate Diff - In Golang with Gorm

### ISSUE THREAD

**Issue by sunilgandipadala** [ariga/atlas#2061]
Hi, 

Actually, in my golang project - models.go contain structs - in which these structs will be converted into database tables using gorm. 

I want to do Versioned Migrations while working with atlas in a golang project with gorm.

I have done "atlas migrate diff --env gorm"  on a clean(fresh) database - then the migrations got created and then I have  applied the migrations using 
'atlas migrate apply --dir "migrations directory" --url "my db url"  --baseline "migrations name"'
And the migrations got applied.

Now I want to change my struct with some filed changes and that database table needs to be updated -- for that I am trying to 

do "apply migrate diff --env gorm" again to generate the migrations 

But now,  it is raising an error  "Error: sql/migrate: taking database snapshot: sql/migrate: connected database is not clean: found table"

------- What I have to do to resolve this error and to achieve my target

files I am using .. 

"atlash.hcl"

data "external_schema" "gorm" {
  
  program = [
    "go",
    "run",
    "-mod=mod",
    "./",
  ]
}

env "gorm" {
  src = data.external_schema.gorm.url
  dev = "mydatabase connection url"
  driver = "mysql"
  migration {
    dir = "file://migrations"
  }
  format {
    migrate {
      diff = "{{ sql . \"  \" }}"
    }
  }
}

and in struct 

"models.go"

package models

import (
	"fmt"
	"io"
	"os"

	"ariga.io/atlas-provider-gorm/gormschema"
	"gorm.io/driver/mysql"
	"gorm.io/gorm"
)

type User struct {
	gorm.Model
	Name string
	Pets []Pet
}

type Pet struct {
	gorm.Model
	Name     string
	User     User
	UserID   uint
	NickName string
	Petname  string
}

func ConnectingDB() {
	mysql_conn := "root:root@/sample"
	db, err := gorm.Open(mysql.Open(mysql_conn), &gorm.Config{})
	fmt.Println(db, err)
	fmt.Println("Data base Connected")
	//	db.AutoMigrate(&User{}, &Pet{})

	stmts, err := gormschema.New("mysql").Load(User{}, Pet{})
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to load gorm schema: %v\n", err)
		os.Exit(1)
	}
	io.WriteString(os.Stdout, stmts)

	//Now we have to perform the remaining task

}

Could You please help me? Where I am doing wrong - and why versioned migrations are not working with me?

**Comment by a8m** [comment]
Hey @sunilgandipadala 👋 

The `dev-url` concept is explained in this [link](https://atlasgo.io/atlas-schema/sql#dev-database). Changing the `dev` attribute to `docker://mysql/8/dev` should solve your issue.

**Comment by sunilgandipadala** [comment]
Hi,

When I use the dev-url as  dev=docker://mysql/8/dev 

While I am doing changes in the Struct, will the migrations will generate automatically?

**Comment by rotemtam** [comment]
Yes. The sequence is like this:
1. you run `atlas migrate diff --env gorm`
2. atlas recognizes that the desired state for this env is an `external_schema`
3. atlas runs the external schema program, which returns the DDL statements defined by your GORM struct
4. atlas replays your migrations on the docker dev db
5. atlas calculates a diff between your current migration dir state and the one returned by the external_schema
6. a diff SQL migration is created in your migration dir and your `atlas.sum` is updated

**Comment by sunilgandipadala** [comment]
Okay, Thank you @a8m & @rotemtam
