### ISSUE TITLE
Using visualize silently connects atlas for cloud deployments

### ISSUE THREAD

**Issue by jrmcpeek** [ariga/atlas#2081]
> atlas version v0.14.1-078bbe1-canary

While testing the latest canary build to confirm fixes for #2039 and #2040, I found my local environment suddenly promoted to full cloud connectivity.

First, I ran a visualize command:

```
$ atlas schema inspect --visualize --env local

https://tenant.atlasgo.cloud/explore/shaslug
```

This confirmed some changes had been made for #2040, and I was able to view the generated visualization.

Then, I ran some arbitrary atlas commands to see if error messages were still being displayed.

First

```
$ atlas migrate status --env test

Migration Status: OK
  -- Current Version: 20230831183253
  -- Next Version:    Already at latest version
  -- Executed Files:  2
  -- Pending Files:   0
```

And then was met with a surprise on the following command:

```
$ atlas migrate apply --env test

No migration files to execute

https://tenant.atlasgo.cloud/deployments/idslug
```

I had not been prompted to share this deployment, nor was that necessarily desirable in this scenario.

In general, I don't believe this promotion of data sharing should happen from a [seemingly] unrelated command.

But, if the desire is there because the environment is now primed, then I think this should prompt for consent prior to doing so.

After this, I went to visit our atlas cloud instance.

To my surprise, the deployments were now populated not only with the one deployment command that was issued above, but **all deployments performed in this environment** since the installation and configuration of atlas:

![image](https://github.com/ariga/atlas/assets/55411348/0601755d-ffbb-4e86-85eb-9c6c63374832)

This, of course, is extremely unexpected, especially with a number of a failures associated with bot token auth issues described in #2037.

In general, I wouldn't expect historical, prior-to-connection deployments to be added, though perhaps that could be desirable and configurable.

Interestingly, the historical migrations are also flagged as multi-tenant, which should not be the case for the schema here.

-----

Behavior above aside, I don't see steps in the documentation to "disconnect" this setup now. How is that performed?

**Comment by a8m** [comment]
Thanks for the feedback, @jrmcpeek. This should be disabled for local directories (directories that were not synced to the cloud). 

I'll send a patch to fix this soon.

**Comment by a8m** [comment]
Thanks for reporting this, @jrmcpeek. The issue was resolved with https://github.com/ariga/atlas/pull/2084.
