### ISSUE TITLE
Golang - atlas migrate diff --env gorm rasing Error: sql/migrate: read migration directory state:

### ISSUE THREAD

**Issue by sunilgandipadala** [ariga/atlas#2090]
hi @a8m,
When I tried to run
atlas migrate diff --env gorm

Error: sql/migrate: read migration directory state: sql/migrate: execute: executing statement

from version "schema": Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '&{0xc00013e5a0 0 0xc0001fc000 1}
Data base Connected
CREATE TABLE `u' at line 1

getting this error, even I tried the hashing by specifying the directory,

How can I get rid of this?

**Comment by rotemtam** [comment]
Does this string "'&{0xc00013e5a0 0 0xc0001fc000 1}" appear somewhere in your sql files?

If you run the command specified by the external schema "program" attr directly, what is the output ?

**Comment by rotemtam** [comment]
Also please share your atlas.hcl file if possible

**Comment by sunilgandipadala** [comment]
> Does this string "'&{0xc00013e5a0 0 0xc0001fc000 1}" appear somewhere in your sql files?
> 
> If you run the command specified by the external schema "program" attr directly, what is the output ?

No, that is a general output which is printed using print statement.

**Comment by sunilgandipadala** [comment]
atlas.hcl 

data "external_schema" "gorm" {
  
  program = [
    "go",
    "run",
    "-mod=mod",
    "./",
  ]
}

env "gorm" {
  src = data.external_schema.gorm.url
  url = "mysql://root:Sunil@513@localhost:3306/"
  //to use versioned migration
  dev = "docker://mysql/8/schema"
  migration {
    dir = "file://migrations"
  }
  format {
    migrate {
      diff = "{{ sql . \"  \" }}"
    }
  }
}


And the string, is generating from this print statement
fmt.Println(db)
	fmt.Println("Database Connected")
	//db.AutoMigrate(&UserData{}, &Pet{})

	stmts, err := gormschema.New("mysql").Load(User{}, Pet{})
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to load gorm schema: %v\n", err)
		os.Exit(1)
	}

	io.WriteString(os.Stdout, stmts)


And While running, 
the complete output is here
atlas migrate diff --env gorm
Error: sql/migrate: read migration directory state: sql/migrate: execute: executing statement "&{0xc000140480 <nil> 0 0xc0001fe000 1}\nDatabase 
Connected\nCREATE TABLE `users` (`id` bigint unsigned AUTO_INCREMENT,`created_at` datetime(3) NULL,`updated_at` datetime(3) NULL,`deleted_at` datetime(3) NULL,`name` longtext,PRIMARY KEY (`id`),INDEX `idx_users_deleted_at` (`deleted_at`));" from version "schema": Error 1064 (42000): You 
have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '&{0xc000140480 <nil> 0 0xc0001fe000 1}
Database Connected
CREATE TABLE `users` (' at line 1



Note: I have previous migrations, which were manually created and added into the migration directory,
the atlas.sum consists of 
h1:DTOD733+CTNQyYNoknkpODFdSSSPLyXnHNTysCCPRNE=
20230908185723.sql h1:6umIm8Kv5DvC7JhIJwLRlyhTgtHEDXS2A+b0QsFyER8=
20230908185952.sql h1:9uoHLjjFWKL452qpt5dZbwirVS87cXzXm5TBx4uwMBU=
20230908185962.sql h1:unpJ63BduvfzYR0c3hMCpAAdh0oK7xHM8U9W3piaj4c=
20230908185963.sql h1:8HQ3deMz7JW2Z7rs2hwD2UHJ4EwhCrku3D1E8cSEefQ=
20230908185965.sql h1:pZJ974fl5xAO2oWpVTeLt/JsBJ6dfB3ciw6N2VubKeY=
20230908185966.sql h1:Pd7n5Bvut+B3rUK918k7lnceuy5hAOrLb7bs43BkyJk=

**Comment by rotemtam** [comment]
It's imperative that your external schema program does not print _anything except_ your schema DDL statements. Remove those fmt.Println and you should be good

**Comment by sunilgandipadala** [comment]
OK, its working. Thank you @rotemtam

**Comment by sunilgandipadala** [comment]
> It's imperative that your external schema program does not print _anything except_ your schema DDL statements. Remove those fmt.Println and you should be good

Hi @rotemtam,

Can I use atlas like as follows..

func main() {

	models.AtlasSchema()
	models.AlterMigrationScripts()
	
	//Some more code for db initialization and routers..
}

models.AtlasSchema() 
package models

import (
	"fmt"
	"io"
	"os"

	"ariga.io/atlas-provider-gorm/gormschema"
)

func AtlasSchema() {
	stmts, err := gormschema.New("postgres").Load(mymodels..)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to load gorm schema: %v\n", err)
		os.Exit(1)
	}

	io.WriteString(os.Stdout, stmts)
}

Now, When I run **atlas migrate diff --env gorm**, what will be the code flow and how the atlas will work here. Like in my case when I run, before completion of AtlasSchema() method execution, the following method also got executed.

Can you please give me some idea on this?

**Comment by sunilgandipadala** [comment]
Could you please response quickly?
