### ISSUE TITLE
Migration Fails with PostgreSQL 16

### ISSUE THREAD

**Issue by gurkanguray** [ariga/atlas#2093]
Migration doesn't work properly with PostgreSQL version 16.

Upon examining the source code, I found that when the PostgreSQL driver is initialized, as seen here:
https://github.com/ariga/atlas/blob/a29ae32fa071245f229a552e6bb95bf3dc8a4c0e/sql/postgres/driver.go#L88

It runs the following query to retrieve c.version, c.ctype, and c.collate information about the PostgreSQL database in use:
https://github.com/ariga/atlas/blob/a29ae32fa071245f229a552e6bb95bf3dc8a4c0e/sql/postgres/inspect.go#L1164

However, when executing this query on the latest version of PostgreSQL (version 16.0 at the time of this report), only the version information is returned. This causes the following error:
https://github.com/ariga/atlas/blob/a29ae32fa071245f229a552e6bb95bf3dc8a4c0e/sql/postgres/driver.go#L99

**Comment by jhajjaarap** [comment]
https://www.postgresql.org/docs/current/release-16.html

> Remove read-only server variables lc_collate and lc_ctype (Peter Eisentraut)

**Comment by a8m** [comment]
Thanks for reporting this, @gurkanguray. A new binary will be released soon.
