### ISSUE TITLE
 pq: zero-length delimited identifier at or near """"

### ISSUE THREAD

**Issue by cs-clarence** [ariga/atlas#2095]
```
atlas version v0.14.1-08cdf91-canary
```

Running `atlas schema apply` generates the following:
```sql
-- Planned Changes:
-- Create enum type "gender"
CREATE TYPE ""."gender" AS ENUM ('male', 'female', 'other');
-- Create enum type "staff_role"
CREATE TYPE ""."staff_role" AS ENUM ('super_admin', 'admin');
-- Create enum type "credential_type"
CREATE TYPE ""."credential_type" AS ENUM ('password', 'oidc', 'totp');
-- Create enum type "identity_type"
CREATE TYPE ""."identity_type" AS ENUM ('user', 'staff');
```
This is only for enums, tables has no empty schema identifiers.

My `schema.sql` file's enums has no db schema specified:

```sql
-- Create enum type "gender"
CREATE TYPE "gender" AS ENUM ('male', 'female', 'other');
-- Create enum type "staff_role"
CREATE TYPE "staff_role" AS ENUM ('super_admin', 'admin');
-- Create enum type "credential_type"
CREATE TYPE "credential_type" AS ENUM ('password', 'oidc', 'totp');
-- Create enum type "identity_type"
CREATE TYPE "identity_type" AS ENUM ('user', 'staff');

```

**Comment by a8m** [comment]
Thanks for reporting this, @cs-clarence.

Can you please paste the full command you used? Also, what PostgreSQL version do you use?

**Comment by cs-clarence** [comment]
@a8m 

I am using postgres 16

I used the command:
```sh
atlas schema apply --env local
```

I have the project config:
```hcl
env {
  name = atlas.env
  url  = postgres://user:password@localhost:5432/taskgrove?search_path=iam&sslmode=disable
  dev  = postgres://user:password@localhost:5432/migration_dev?search_path=iam&sslmode=disable
  src  = "file://./src/db/schema.sql"

  migration {
    format = atlas
    dir    = "file://./src/db/migrations"
  }
}
```

**Comment by a8m** [comment]
Thanks for the info, @cs-clarence. I'll give this a look.

For now, I suspect this is an issue with the new PostgreSQL version, and using 15 should solve the issue. Would you mind checking this?

**Comment by cs-clarence** [comment]
Sure

**Comment by cs-clarence** [comment]
I just checked with docker postgres:15-alpine but it's the same @a8m

**Comment by a8m** [comment]
<img width="1573" alt="image" src="https://github.com/ariga/atlas/assets/7413593/c9d6a5ac-e6cb-4f6f-bfd5-3630ec852102">

Another last check. Can you try these two as "dev-url":
- "docker://postgres/15/dev?search_path=public"
- "postgres://user:password@localhost:5432/migration_dev?search_path=public&sslmode=disable"

In "schema scope" the name does not really matter, because statements are not qualified.

**Comment by hectorj-thetreep** [comment]
Same issue here. It doesn't happen if you don't put a `search_path` in the URL, but you can't always do that.

**Comment by hectorj-thetreep** [comment]
Got a working fix https://github.com/ariga/atlas/pull/2125
