### ISSUE TITLE
Creating new Column in postgres and Deleting Old coumn - When Changing a filed name- in golang

### ISSUE THREAD

**Issue by sunilgandipadala** [ariga/atlas#2099]
Hi, 

I am using gorm, and I want to change the column name of the already existing table, The data type is similar and the column contains data in it. 

So, I tried changing the filed name in the struct and run "atlas migrate diff --env gorm". And even is I tried to rename the table (struct name), how can I do that?
Then it generated a migration that deletes the old column and generates a new column.

Is there any way to get my goal done through versioned migrations?

**Comment by rotemtam** [comment]
Hi @sunilgandipadala,

Atlas currently doesn't have a way to tell the difference between a rename and a drop-and-add, as it simply looks at the difference between the current and desired states. 

The expected flow in the occasional need to rename is to manually edit the generated migration to an `ALTER TABLE table RENAME COLUMN column` statement. Don't forget to run `atlas migrate hash` at the end, to update your `atlas.sum` file before committing your changes. 

To prevent Atlas from planning DROP COLUMN changes, you can use [Diff Policies](https://atlasgo.io/versioned/diff#diff-policy). This will not result in a RENAME statement automatically, but at least will prevent the case of accidentally committing a destructive change. 

In addition, it is highly recommended to implement [CI for you Database](https://atlasgo.io/cloud/setup-ci) to prevent destructive changes from being merged. 

Closing, but feel free to re-open if needed. 

HTH

**Comment by sunilgandipadala** [comment]
Hi, 
ok as you mentioned atlas wasn't  able to find difference between Rename & Drop and Add statements. 

_-- Modify "buyers" table
ALTER TABLE "public"."buyers" DROP COLUMN "headers", ADD COLUMN "pet_name" text NULL, ADD COLUMN "headersnew" text NULL;_

Now, it is generating the queries like in an order of DROP Columns first then Add columns of a table. in the order of the fields in the struct. Is it possible to genertare the queries in the migrations through atlas as if a field name changed (Rename operation), to generate both DROP Column statement and ADD Column Statement together  

For Suppose: 
_-- Modify "buyers" table
ALTER TABLE "public"."buyers" DROP COLUMN "headers",ADD COLUMN "headersnew" text NULL, ADD COLUMN "pet_name" text NULL;_

**Comment by sunilgandipadala** [comment]
> Hi @sunilgandipadala,
> 
> Atlas currently doesn't have a way to tell the difference between a rename and a drop-and-add, as it simply looks at the difference between the current and desired states.
> 
> The expected flow in the occasional need to rename is to manually edit the generated migration to an `ALTER TABLE table RENAME COLUMN column` statement. Don't forget to run `atlas migrate hash` at the end, to update your `atlas.sum` file before committing your changes.
> 
> To prevent Atlas from planning DROP COLUMN changes, you can use [Diff Policies](https://atlasgo.io/versioned/diff#diff-policy). This will not result in a RENAME statement automatically, but at least will prevent the case of accidentally committing a destructive change.
> 
> In addition, it is highly recommended to implement [CI for you Database](https://atlasgo.io/cloud/setup-ci) to prevent destructive changes from being merged.
> 
> Closing, but feel free to re-open if needed.
> 
> HTH

Hi,
ok as you mentioned atlas wasn't able to find difference between Rename & Drop and Add statements.

-- Modify "buyers" table
ALTER TABLE "public"."buyers" DROP COLUMN "headers", ADD COLUMN "pet_name" text NULL, ADD COLUMN "headersnew" text NULL;

Now, it is generating the queries like in an order of DROP Columns first then Add columns of a table. in the order of the fields in the struct. Is it possible to genertare the queries in the migrations through atlas as if a field name changed (Rename operation), to generate both DROP Column statement and ADD Column Statement together

For Suppose:
-- Modify "buyers" table
ALTER TABLE "public"."buyers" DROP COLUMN "headers",ADD COLUMN "headersnew" text NULL, ADD COLUMN "pet_name" text NULL;
