### ISSUE TITLE
the Atlas does not create schema for the Postgres Functions

### ISSUE THREAD

**Issue by atazangene** [ariga/atlas#2102]
Hi, I am using the command to create schema of current database

atlas schema inspect -u "postgresql://user:password@1.251.183.1:5432/autojobapply?sslmode=disable" > schema.hcl
it works well, but the problem is that it does not include the functions I have defined for my postgres schemas

what should I do?

**Comment by atazangene** [comment]
Thank you very much, honestly I really like the Atlas, I think it it much much better and easier to use than Liquibase. however the only downside is not able to migrate the functions, do you have any alternative solution ?

**Comment by a8m** [comment]
How do you manage the database schemas currently, versioned migrations (`atlas migrate`) or the declarative workflow (`atlas schema`)?

**Comment by atazangene** [comment]
I am trying to use declarative migration

**Comment by davidovich** [comment]
@atazangene What I did and it seems to be working is to use a manual migration:

```
> atlas migrate new add_function
```
Edit and add your function definition in the resulting migration file:

`CREATE OR REPLACE FUNCTION my_new_function() ... function content ...`

```
# run hash to update the hash after a manual add/update of migration
> atlas migrate hash
```

**Comment by a8m** [comment]
Hey! Just wanted to update you that both functions and procedures have been added to Atlas. They are currently in beta and are available for logged-in users. For more info, check out this link: https://atlasgo.io/atlas-schema/hcl#function.

**Comment by atazangene** [comment]
Ohh, That is really amazing, now Atlas has everything required for a professional migration
