### ISSUE TITLE
sqlite: migration output for column default value incorrectly strips parentheses

### ISSUE THREAD

**Issue by stephen** [ariga/atlas#2124]
### Background
From https://www.sqlite.org/lang_createtable.html#the_default_clause:
> If the default value of a column is an expression in parentheses, then the expression is evaluated once for each row inserted and the results used in the new row.

### Repro
Given this desired schema:
```sql
create table users (
  id text not null default (uuid()),
  primary key (id)
);
```

### Actual result
`atlas migrate diff` will generate:
```sql
CREATE TABLE `users` (`id` text NOT NULL DEFAULT uuid(), PRIMARY KEY (`id`));
```

Note the `uuid()` has the parentheses stripped, which sqlite will not accept as a valid default:
```sql
Parse error: near "(": syntax error
  ATE TABLE `users` (`id` text NOT NULL DEFAULT uuid(),
                                      error here ---^
```

### Expected result
The output migration should keep the parentheses, i.e.
```sql
CREATE TABLE `users` (`id` text NOT NULL DEFAULT (uuid()), PRIMARY KEY (`id`));
```

**Comment by a8m** [comment]
Thanks for reporting this, @stephen. I'll give this a look.
