### ISSUE TITLE
Diffing policy for concurrent_index does not work in `migrate diff` command

### ISSUE THREAD

**Issue by kfirba** [ariga/atlas#2130]
Hey,

We have a schema file which we use `atlas migrate diff` to diff the current schema file against a dev database, to create a new migration file:

```bash
atlas migrate diff \
  --dir "file://migrations" \
  --to "file://schema/master_schema.sql"\
  --config "file://atlas.hcl" \
  --dev-url "postgresql://postgres:postgres@localhost:5432/testing?sslmode=disable"
```

Our `atlas.hcl` file's contents:

```hcl
diff {
  concurrent_index {
    create = true
    drop   = true
  }
}
```

The `master_schema.sql` file contains the following index creation code:

```sql
create index concurrently "Table_column_idx" on "Table" ("column");
```

When we run the `atlas migrate diff...`, the generated migration code does not contain the `concurrently` keyword at all:

```sql
-- Create index "Table_column_idx" to table: "Table"
CREATE INDEX "Table_column_idx" ON "public"."Table" ("column");
```

This behavior does not change even if we remove the `diff` section from `atlas.hcl`.

**Comment by a8m** [comment]
Hey @kfirba and thanks for reporting this. 

Can you please paste here the `atlas.hcl` file you used?

**Comment by kfirba** [comment]
@a8m Certainly:

```
lint {
  destructive {
    error = false
  }

  naming {
    table {
      match   = "^[A-Z][a-z0-9]*(?:[A-Z][a-z0-9]*)*$"
      message = "must be pascal case"
    }
    column {
      match   = "^[a-z]+(?:[A-Z][a-z]+)*$"
      message = "must be camel case"
    }
    foreign_key {
      match   = "^([a-z]+(?:[A-Z][a-z]+)*_)+fk$"
      message = "foreign key must be camel case (with underscore as separator) and end with fk, e.g. demoCol_pompaTest_fk"
    }
  }

  concurrent_index {
    error = true
  }
}

diff {
  concurrent_index {
    create = true
    drop   = true
  }
}
```

**Comment by a8m** [comment]
It looks like there's a typo in your configuration. Replacing `create` to `add` should solve the issue. 

cc @masseelch

**Comment by kfirba** [comment]
@a8m I simply copied it directly from the docs:

https://atlasgo.io/declarative/diff#diff-policy

![image](https://github.com/ariga/atlas/assets/8510486/61059744-16df-462c-9ab0-9d38ebc8d080)


It does work now. However, it now complains that the migration file should be annotated so as not to run in a transaction. However, since we are using the `atlas migrate diff` command, the generated migration file may contain more changes that *I do* want to run in a transaction. Can atlas split those into 2 separate files and add the annotation itself?

**Comment by a8m** [comment]
> @a8m I simply copied it directly from the docs:

Thanks for the feedback. I sent a patch to fix this. 

> However, it now complains that the migration file should be annotated so as not to run in a transaction. However, since we are using the atlas migrate diff command, the generated migration file may contain more changes that I do want to run in a transaction. Can atlas split those into 2 separate files and add the annotation itself?

Right, because `lint` and `diff` policies are two different entities. A capability like this, together with "propose fixes/changes" is going to be released soon for cloud users (more like an advisory mode). You're welcome to join [https://atlasgo.cloud](https://auth.atlasgo.cloud/signup) and we'll let you know when the feature is out. I'm also available on our Discord if you need more help or have questions.
