### ISSUE TITLE
atlas migrate diff --env gorm - Error: sql/migrate: read migration directory state: sql/migrate: execute: executing statement 

### ISSUE THREAD

**Issue by snehachebrolu123** [ariga/atlas#2168]
Error: sql/migrate: read migration directory state: sql/migrate: execute: executing statement "CREATE TABLE \"customers\" (\"id\" bigserial) from version "schema": pq: relation "customers" already exists

While I am running the command, getting the above error, I am unable to get the reason why it is raising. 
**atlas.hcl**
```
variable "destructive" {
  type    = bool
  default = false
}


data "external_schema" "gorm" {
  
  program = [
    "go",
    "run",
    "main.go",
    "migrate",
    "-mod=mod",
    "./",
  ]
}

env "gorm" {
  src = data.external_schema.gorm.url
  url = "dburl"
  
  //to use versioned migration
  dev = "docker://postgres/15/sample"
  migration {
    dir = "file://migrations"
  }
  format {
    migrate {
      diff = "{{ sql . \"  \" }}"
    }
  }
  diff {
    skip {
      drop_schema = !var.destructive
      drop_table  = !var.destructive
    }
  }
}
```

Could you please let me know the reason

**Comment by masseelch** [comment]
Hey! This looks like your migration directory does not contain correct files. An chance you can share it?

**Comment by snehachebrolu123** [comment]
PFA for the migration directory
[migrations.zip](https://github.com/ariga/atlas/files/12855085/migrations.zip)

**Comment by snehachebrolu123** [comment]
The problem has been resolved, There is a problem while loading tables to Postgres db, We need to pass all the models as a parameter for the load() method.
Previously in the code, it accepted a single table struct as a parameter.

**Comment by snehachebrolu123** [comment]
Thanks!
