### ISSUE TITLE
Atlas fails to parse password with `?`

### ISSUE THREAD

**Issue by jay-babu** [ariga/atlas#2173]
I rotated the password so don't worry about the security risk, but I am running 

`atlas schema inspect -u "postgres://postgres:PkFK87?F~mpqpuOHOCJI(i%Y3KtA@transformity-gamma.cluster-cu3q2lrqndpl.us-east-1.rds.amazonaws.com:5432/transformity_pos" --visualize`

and keep getting this error `Error: invalid port ":PkFK87" after host`. Unsure how to fix and this is blocking any sort of getting started with atlas

**Comment by masseelch** [comment]
Hey. Please url encode your password and then it will work. Let me know, if not.

**Comment by jay-babu** [comment]
Yes, that works. thank you. seems like a poor customer experience though

**Comment by masseelch** [comment]
Glad it works now. Let me know if you have any more questions 😊
