### ISSUE TITLE
Don't it support installation via go install?

### ISSUE THREAD

**Issue by sishuiL** [ariga/atlas#2193]
I tried to install it using this
```go install github.com/ariga/atlas/cmd/atlas@latest```

Error:
```shell
go: github.com/ariga/atlas/cmd/atlas@latest: github.com/ariga/atlas/cmd/atlas@v0.13.1: parsing go.mod:
        module declares its path as: ariga.io/atlas/cmd/atlas
                but was required as: github.com/ariga/atlas/cmd/atlas
```

**Comment by masseelch** [comment]
Hey, the module is named `ariga.io/atlas/cmd/atlas` not `github.com/ariga/atlas/cmd/atlas`. Also, I advise to install Atlas using our installation instructions, not `go install`: `curl -sSf https://atlasgo.sh | sh`. See more details [here](https://atlasgo.io/getting-started#installation).
