### ISSUE TITLE
how to ignore general foreign key constraints  with gorm when doing migrate 

### ISSUE THREAD

**Issue by qbright** [ariga/atlas#2196]
in gorm framework has a config "DisableForeignKeyConstraintWhenMigrating" ，but when I use atlas to general migrate sql , it will general the foreign key constraints 
how to config it to ignore general the foreign key constraints

**Comment by masseelch** [comment]
Hey @qbright. Please have a look at the [README](https://github.com/ariga/atlas-provider-gorm#additional-configuration) of the atlas-gorm-provider repository. It has an example for exactly that use-case.

If there are any problems, don't hesitate to reach out.
