### ISSUE TITLE
Can't connect to LibSQL local file database

### ISSUE THREAD

**Issue by KamWithK** [ariga/atlas#2198]
I'm trying to use Atlas but if I set up my atlas.hcl as such:
```
env "local" {
  src = "file://schema.sql"
  url = "libsql://data/local.db"
  dev = "libsql://data/atlas.db"
}
```

Then I get this error (when for example I run a command like `atlas migrate diff --env local`):
```
Error: sqlite: query version pragma: failed to WebSocket dial: failed to send handshake request: Get "https://data/atlas.db": dial tcp: lookup data on 172.27.240.1:53: no such host
```

Does atlas only support LibSQL when run with Turso or as a server?

I could modify it to just use sqlite instead of libsql for local tests but then libsql supports some features which libsql does not (for example random row id), and so atlas would give an error when trying to use one of those

**Comment by penberg** [comment]
The `libsql://` protocol implies remote access right now. @haaawk, is this use case supported where you use local files only?

**Comment by KamWithK** [comment]
> The `libsql://` protocol implies remote access right now. @haaawk, is this use case supported where you use local files only?

Ah I see, makes sense
Would definitely be useful to be able to use it from a file as well though!
Maybe you could do `libsql+file://` for file databases or something

**Comment by KamWithK** [comment]
From a quick search through your code you've imported `libsql-client-go`, not sure how you use it but `sql.open("libsql", "file:/local.db")` allows you to read a local libsql database
