### ISSUE TITLE
Connect to Postgres docker image results in error "postgres: unexpected number of rows: 1"

### ISSUE THREAD

**Issue by HollererJ** [ariga/atlas#2210]
i tried to run atlas with a local docker container running postgres:16 
when trying to run postgres.Open from the "ariga.io/atlas/sql/postgres" package i get the error 
`postgres: unexpected number of rows: 1`

after analysis from the executed code the following query is executed:
`SELECT setting FROM pg_settings WHERE name IN ('lc_collate', 'lc_ctype', 'server_version_num', 'crdb_version') ORDER BY name DESC;`

the result out of that query in our case is `160000` (the server_version_num)

in our docker container the variables 'lc_collate','lc_ctype' and 'crdb_version' are not available.
out of that issue it is not possible to connect to the database and perform any schema inspection

**Comment by a8m** [comment]
Hey @HollererJ 👋🏻

This issue was fixed a few weeks ago. Please, upgrade Atlas to its latest version and report if you still encounter errors.

**Comment by HollererJ** [comment]
Perfect - works with v0.14.2 
thanks for the fast reply

**Comment by lufia** [comment]
Hi, @a8m 

Would you release **cmd/atlas** module on Go Modules with the **cmd/atlas/v0.19** tag?

Today, I try `go install github.com/ariga/atlas/cmd/atlas@latest` then it installs old version atlas command that this issue is not fixed yet.

**Comment by giautm** [comment]
hello @lufia please use our installer script to install atlas on your system.

curl -sSf https://atlasgo.sh | sh
