### ISSUE TITLE
Postgres DOMAIN support in v15 isn't working

### ISSUE THREAD

**Issue by ilanfrai** [ariga/atlas#2214]
According to V15 release notes (https://github.com/ariga/atlas/releases/tag/v0.15.0), domains should be supported now.
We tried to use it to generate migrations on the following simple schema:
```
create domain "Amount" as numeric(14, 4);

create table
  "Products" (
    "id" text,
    "price" "Amount"
  )
```

and the following command:
`atlas migrate diff  --dir "file://migrations" --to "file://schema/master_schema.sql" --config "file://atlas.hcl" --dev-url "postgresql://postgres:postgres@localhost:5432/testing?sslmode=disable"`

the result was one migration file with the following contents:
`-- Create "Products" table
CREATE TABLE "public"."Products" ("id" text NULL, "price" "amount" NULL);
`
As you can see the domain generation is missing from it.
Atlas version is: v0.15.1-7a5cb53-canary

**Comment by a8m** [comment]
Hey @ilanfrai,
As stated in the doc, domains, functions, and procedures are in beta and available for logged-in users only. https://atlasgo.io/atlas-schema/hcl#domain

I'll make sure we add this info to the blog post.  Thanks for reporting this 🙏
