### ISSUE TITLE
Is Windows version deprecated?

### ISSUE THREAD

**Issue by myonlylonely** [ariga/atlas#2215]
I know that Windows binary is not provided any more. But is Windows version still considered in the developerment? Is building from source still a good option? There are some Windows Server environment that Docker or WSL is not possible or convenient.

**Comment by masseelch** [comment]
Hey @myonlylonely. Atlas is using pg_query internally and one of its dependencies can currently not be build on windows. See [this issue](https://github.com/pganalyze/libpg_query/issues/44).

This is the reason we removed the windows binary. For now, we haven't found a way around this limitation. I'll keep this open and will answer once we have further info.

**Comment by myonlylonely** [comment]
@masseelch The link that you provided suggests that the disscussion of Windows support in libpg_query started at 2018. But until 0.14 of Atlas, Atlas still provided Windows version. Is pg_query switch to libpg_query recently?

**Comment by masseelch** [comment]
Yes we switched only recently. We discussed and will revert the switch for the windows version. You can expect the windows builds to be back at latest tomorrow. I'll notify you here.

**Comment by myonlylonely** [comment]
@masseelch I can see the new commit that bring Windows support back, any updates for the Github release?

**Comment by masseelch** [comment]
The build is re-enabled and the documentation is back with windows instructions.
