### ISSUE TITLE
SqlServer inspect fails

### ISSUE THREAD

**Issue by yunusbyrak** [ariga/atlas#2220]
I have bunch of schemas in my SqlServer, I'm trying to inspect the database getting this error:

`Error: referenced schema "*****" was not found in realm`

**Comment by rotemtam** [comment]
Thanks for reaching out!

What exactly is the command you are running ? (Mask credentials)

**Comment by yunusbyrak** [comment]
`atlas schema inspect -u "sqlserver://sa:********@********:1433?database=********" > schema.hcl `

**Comment by giautm** [comment]
> `atlas schema inspect -u "sqlserver://sa:********@********:1433?database=********" > schema.hcl `

Hey, look like you're trying to inspect whole database, and one of resources reference to another schema. By default, Atlas will use the schema mode to inspect the given database, which is the schema of current user. To inspect whole database, please add `&mode=database` in your URL. 

`atlas schema inspect -u "sqlserver://sa:********@********:1433?database=********&mode=database" > schema.hcl `

See more detail about URL here (choose SQL server tab): https://atlasgo.io/concepts/url#what-is-a-url

**Comment by yunusbyrak** [comment]
Yeah, that fixed the problem, thank you!
