### ISSUE TITLE
Error on atlas migrate diff with citus extension enabled

### ISSUE THREAD

**Issue by fabiorizzomatos** [ariga/atlas#2221]
Hello guys,

i'm working on a project with atlas, but i'm having this problem with citus extension enabled:

atlas migrate diff --env gorm
Error: sql/migrate: taking database snapshot: view "citus_schemas" was not found in schema "public"
make: *** [makemigrations] Error 1

my atlas.hcl

data "external_schema" "gorm" {
  program = [
    "go",
    "run",
    "-mod=mod",
    "./loader",
  ]
}

env "gorm" {
  src = data.external_schema.gorm.url
  dev = "postgres://vindula:vindula@127.0.0.1:54322/vindula?sslmode=disable&search_path=public"
  migration {
    dir = "file://migrations"
  }
  format {
    migrate {
      diff = "{{ sql . \"  \" }}"
    }
  }
}

and my loader:

func main() {
	stmts, err := gormschema.New("postgres").Load(
		&models.User{},
	)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to load gorm schema: %v\n", err)
		os.Exit(1)
	}
	io.WriteString(os.Stdout, stmts)
}

Could you guys, help me figure what i'm doing wrong?

Thanks!

**Comment by fabiorizzomatos** [comment]
I noted that the error starting to happen when i create a new view. After that, the citus_schema happens everytime when i tried to do atlas migrate apply --env gorm -u "postgres://vindula:vindula@127.0.0.1:5432/vindula?sslmode=disable&search_path=public"

**Comment by fabiorizzomatos** [comment]
Guys, its related to my issue: What is the procedure to use views and retain the ability of making diffs? today, in my project, i'm not using views, because, after the first, the atlas diffs stop working.

i appreciate any tip. Thanks!

**Comment by offroff** [comment]
I have the same problem. I just learned there are an option to exclude views when inspecting the schema. https://github.com/ariga/atlas/issues/2017 
I'll try that.

**Comment by a8m** [comment]
Thanks for reporting this, @fabiorizzomatos and @offroff. We'll try to get to it later today.

**Comment by offroff** [comment]
I found no way to deal with this problem. I created a view with the suffix _view and tried to exclude it using --exclude "*_view"

But I get this error: 
Error: view "citus_schemas" was not found in schema "public"

(Same error without the exclude flag)

Hoping you'll get time to look into this issue.

**Comment by a8m** [comment]
Hey! I sent a patch to fix this issue and a new binary should be available soon. Please, give it a try and let me know if it solved your issue.

See this example usage, and note you can use `docker+postgres://citusdata/citus/dev?search_path=public` as a URL for your dev-database:

```
➜  citus-example cat schema.sql 
create table t(c int);

create view v(c) as select c from t;

➜  citus-example atlas migrate diff \                                                                                               
--to file://schema.sql \
--dev-url "docker+postgres://citusdata/citus/dev?search_path=public"

➜  citus-example cat migrations/20231106123117.sql 
-- Create "t" table
CREATE TABLE "t" ("c" integer NULL);
-- Create "v" view
CREATE VIEW "v" ("c") AS SELECT c
   FROM t;

➜  citus-example atlas migrate apply \            
--url "postgres://postgres:pass@:5432/example?search_path=public&sslmode=disable"
Migrating to version 20231106123117 (1 migrations in total):

  -- migrating version 20231106123117
    -> CREATE TABLE "t" ("c" integer NULL);
    -> CREATE VIEW "v" ("c") AS SELECT c
   FROM t;
  -- ok (7.747902ms)

  -------------------------
  -- 57.479392ms
  -- 1 migrations 
  -- 2 sql statements

➜  citus-example atlas migrate apply \
--url "postgres://postgres:pass@:5432/example?search_path=public&sslmode=disable"
No migration files to execute

➜  citus-example vi schema.sql 

➜  citus-example cat schema.sql 
create table t(c int);

create view v(c) as select c from t;

create table t1(c int);

create view v1(c) as select c from t1;

➜  citus-example atlas migrate diff \ 
--to file://schema.sql \                                                         
--dev-url "docker+postgres://citusdata/citus/dev?search_path=public"

➜  citus-example cat migrations/20231106123221.sql 
-- Create "t1" table
CREATE TABLE "t1" ("c" integer NULL);
-- Create "v1" view
CREATE VIEW "v1" ("c") AS SELECT c
   FROM t1;

➜  citus-example atlas migrate diff \             
--to file://schema.sql \
--dev-url "docker+postgres://citusdata/citus/dev?search_path=public"
The migration directory is synced with the desired state, no changes to be made

➜  citus-example atlas migrate apply \           
--url "postgres://postgres:pass@:5432/example?search_path=public&sslmode=disable"
Migrating to version 20231106123221 from 20231106123117 (1 migrations in total):

  -- migrating version 20231106123221
    -> CREATE TABLE "t1" ("c" integer NULL);
    -> CREATE VIEW "v1" ("c") AS SELECT c
   FROM t1;
  -- ok (7.83122ms)

  -------------------------
  -- 20.320454ms
  -- 1 migrations 
  -- 2 sql statements

➜  citus-example atlas migrate apply \
--url "postgres://postgres:pass@:5432/example?search_path=public&sslmode=disable"
No migration files to execute

➜  citus-example atlas migrate status \
--url "postgres://postgres:pass@:5432/example?search_path=public&sslmode=disable"
Migration Status: OK
  -- Current Version: 20231106123221
  -- Next Version:    Already at latest version
  -- Executed Files:  2
  -- Pending Files:   0
```

**Comment by offroff** [comment]
It works! Thank you.

**Comment by a8m** [comment]
Wonderful. Thanks for the update

**Comment by fabiorizzomatos** [comment]
@a8m Thanks!
