### ISSUE TITLE
Migrating Multiple Schema Versions

### ISSUE THREAD

**Issue by feigi** [ariga/atlas#2225]
Hey everyone,

I stumbled upon Atlas and would like to use it to migrate multiple schema versions using the versioned migration approach via the Terraform provider. Unfortunately I'm struggling a bit. Basically what I'd like to do is, handle two schema.sql files (users_v1_schema.sql and users_v2_schema.sql) with two migrations folders (e.g. migrations_v1 and migrations_v2), so that I can run two versions in parallel for a certain period. The Atlas config and CLI works just fine, I'm just running into issues deploying it via the Terraform provider.

I'm trying to do something like this:

```terraform 
data "atlas_migration" "this" {
  for_each = local.schemas

  revisions_schema = each.key
  dir              = "${each.value}?format=atlas"
  url              = local.url
}

resource "atlas_migration" "this" {
  for_each = local.schemas

  revisions_schema = each.key
  dir              = "${each.value}?format=atlas"
  version          = data.atlas_migration.this[each.key].latest # Use latest to run all migrations
  url              = local.url
  dev_url          = local.dev_url
}
```

with `local.schemas` being a map of schema names and a migration folder. E.g. `{ "users_v1" : "migrations_v1", "users_v2" : "migrations_v2" }`.

Sadly I'm running into this error: 

```plain
module.db_migration.data.atlas_migration.this["users_v1"]: Reading...
module.db_migration.data.atlas_migration.this["users_v2"]: Reading...
module.db_migration.data.atlas_migration.this["users_v2"]: Read complete after 0s [id=migrations_v2?format=atlas]
module.db_migration.data.atlas_migration.this["users_v1"]: Read complete after 0s [id=migrations_v1?format=atlas]
module.db_migration.atlas_migration.this["users_v2"]: Refreshing state... [id=file://migrations_v2?format=atlas]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the
following symbols:
  + create

Terraform will perform the following actions:

  # module.db_migration.atlas_migration.this["users_v1"] will be created
  + resource "atlas_migration" "this" {
      + dev_url          = (sensitive value)
      + dir              = "migrations_v1?format=atlas"
      + id               = (known after apply)
      + revisions_schema = "users_v1"
      + status           = (known after apply)
      + url              = (sensitive value)
      + version          = "20231025085555"
    }

  # module.db_migration.atlas_migration.this["users_v2"] will be created
  + resource "atlas_migration" "this" {
      + dev_url          = (sensitive value)
      + dir              = "migrations_v2?format=atlas"
      + id               = (known after apply)
      + revisions_schema = "users_v2"
      + status           = (known after apply)
      + url              = (sensitive value)
      + version          = "20231025091424"
    }

Plan: 2 to add, 0 to change, 0 to destroy.
╷
│ Warning: Lint error
│
│   with module.db_migration.atlas_migration.this["users_v2"],
│   on ../modules/db-migration/migrations.tf line 14, in resource "atlas_migration" "this":
│   14: resource "atlas_migration" "this" {
│
│ File: 20231025091424_initial_schema.sql
│ executing statement: pq: schema "users_v2" does not exist
│
│ (and one more similar warning elsewhere)
╵

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.db_migration.atlas_migration.this["users_v2"]: Creating...
module.db_migration.atlas_migration.this["users_v1"]: Creating...
module.db_migration.atlas_migration.this["users_v2"]: Still creating... [10s elapsed]
module.db_migration.atlas_migration.this["users_v1"]: Still creating... [10s elapsed]
module.db_migration.atlas_migration.this["users_v2"]: Creation complete after 14s [id=file://migrations_v2?format=atlas]
╷
│ Warning: Lint error
│
│   with module.db_migration.atlas_migration.this["users_v1"],
│   on ../modules/db-migration/migrations.tf line 14, in resource "atlas_migration" "this":
│   14: resource "atlas_migration" "this" {
│
│ File: 20231025085555_add_users_table.sql
│ executing statement: pq: schema "users_v1" does not exist
│
│ (and one more similar warning elsewhere)
╵
╷
│ Error: sql/migrate: connected database is not clean: found schema "users_v2". baseline version or allow-dirty is required
│
│
│   with module.db_migration.atlas_migration.this["users_v1"],
│   on ../modules/db-migration/migrations.tf line 14, in resource "atlas_migration" "this":
│   14: resource "atlas_migration" "this" {
```

It looks to me like I'm getting this error because two migrations are running in parallel. `users_v2` actually completed successfully, but `users_v1` then failed. I also tried adding the schemas before via `atlas_schema` as described [here](https://atlasgo.io/guides/terraform/named-databases) but ran into the same error.

Is something like this even supported? Could you give a hint on how to fix it maybe?

**Comment by rotemtam** [comment]
Hi
I'm a bit confused as to what you're trying to achieve. 

In principle, if you are using [versioned migrations](https://atlasgo.io/versioned/intro), a schema in your database should be managed by only one migration directory. There are exceptions to the rule which can be managed using custom `exclude` flags, etc, but still each schema resource (table etc) would be managed by only one directory. 

What is the relation between `migrations_v1` and `migrations_v2`?

**Comment by feigi** [comment]
Hi! 

the naming was a bit unclear. It’s rather user_v1_migrations user_v2_migrations. One folder per Schema. I’m trying to run two schemas in parallel for downtime less migration in case of a breaking change we can’t avoid. 

Thanks!

**Comment by masseelch** [comment]
Hey. This means you (sometimes) want one schema to be one or more versions farther than the other schema, correct?

But they won't drive in different directions, right? Just one is faster than another?

**Comment by feigi** [comment]
Hey! Technically yes, but since the schema name changes, it‘s going to be a whole new set of tables I suppose. Each create table statement will contain e.g. „users_v2“.“some_table“ instead of „users_v1“, so I‘d expect a whole bunch of drop tables and create tables? 

I can also spin up a new „v2“ DB cluster temporarily as a workaround. First idea was just using versioned schemas as it’s more lightweight.
