### ISSUE TITLE
Feature: Ability to Link other files into the schema.hcl

### ISSUE THREAD

**Issue by ocomsoft** [ariga/atlas#2229]
It would be really useful if we could Link other files into the schema.hcl for example something like

```
import "./auth_tables.hcl"
import "../app/other.hcl"
```

This would help with reusing Schemas. I hope this makes sense. Thanks for all that has been done already.

**Comment by rotemtam** [comment]
This is already possible. You can provide multiple HCL files or complete directories as input to most Atlas commands.


E.g
![image](https://github.com/ariga/atlas/assets/1522681/36735fe5-cb47-4d4e-980d-8cc9b37ba426)

**Comment by ocomsoft** [comment]
@rotemtam  I am so sorry. I didn't see these options. Thanks for pointing them out.
