### ISSUE TITLE
Sql Server - image column type not supported when inspecting as SQL

### ISSUE THREAD

**Issue by jamesdkelly88** [ariga/atlas#2231]
When using atlas schema inspect against the Northwind database from [here](https://github.com/microsoft/sql-server-samples) I am able to generate HCL output, but when generating SQL output the command fails with the error:
`Error: template: format:1:3: executing "format" at <sql .>: error calling sql: create table "Employees": mssql: unexpected binary type: "image"`

Command executed: `atlas schema inspect -u "sqlserver://sa:***@localhost:1433/northwind" --format '{{ sql . }}'`
Version: `atlas version v0.15.1-8b67253-canary`

**Comment by giautm** [comment]
Hello @jamesdkelly88 can you share the SQL of the example DB (use the SQL server tool to dump) for me? Because I have never used the repo you provided and don't know how to use it.

Or you can provide step-by-step to reproduce the issue, I will very appreciate.

**Comment by giautm** [comment]
Hello @jamesdkelly88, I sent a PR to fix the support for image column and other issues which I found in that migration files. Please upgrade atlas-cli enterprise to the latest build and try again. Any feedbacks from you are welcome. If you still facing any issue, please send them to me. I'll check and fix ASAP. Thank you in advance.
