### ISSUE TITLE
'create extension' statement is not being generated.

### ISSUE THREAD

**Issue by althaf004** [ariga/atlas#2248]
In the migration script, the 'create extension' statement is not being generated. Is there a way to include that as well?

**Comment by jerluc** [comment]
@althaf004 this doesn't solve your issue exactly, but I've basically done this by starting my migrations with:

```
atlas migration new --edit
```

And manually editing the first migration to include all the `CREATE EXTENSION` statements I need.

This is far from ideal, but this works for my use case in the interim!

**Comment by masseelch** [comment]
Atlas does not have support for extensions management (yet). As a workaround, your migration diectory can contain a "baseline" file, that contains the create extension instructions, as mentioned by @jerluc. Note as well, that you can use any custom docker image for the docker driver: `--dev-url docker+postgres://owner/image` for a postgres custom image that has extensions compiled for example.

**Comment by alexisvisco** [comment]
It does not work at all, creating a migration with `atlas migration new --edit` is completely ignored (atlas tell that no migrations need to be ran run) --edit should add it to the hash so why it say that ?

And baseline isn't ran because I have `hstore type does not exist` in other migrations.

**Comment by domenkozar** [comment]
I wanted to use this with [devenv postgres](https://devenv.sh/services/), but it seems that #2507 is missing.

Using [this workaround](https://github.com/cachix/devenv/issues/587#issuecomment-1550774701) helps.

**Comment by a8m** [comment]
Hey! Just to update that this was solved in the latest release. Please, see the doc for more info: https://atlasgo.io/atlas-schema/hcl#extension

**Comment by domenkozar** [comment]
Are they also supported when using just SQL?

**Comment by a8m** [comment]
> Are they also supported when using just SQL?

Yes

**Comment by domenkozar** [comment]
Thank you guys :)

**Comment by brenwell** [comment]
Hey team is there an example for how to do this in straight sql? Should I be using a different dev image?

schema.sql

```sql
CREATE extension postgis;
```

atlas.hcl

```hcl
env "local" {
  src = "./schema.sql"
  dev = "docker://postgis"
  ...
}
```

Command

```sh
atlas migrate diff --env local create_postgis
Error: sql/migrate: taking database snapshot: sql/migrate: connected database is not clean: found schema "public"
```

**Comment by brenwell** [comment]
So I got it working thanks to the Giau in discord. With the following but I have no idea what it does

```hcl
env "local" {
  src = "./schema.sql"
  dev = "docker://postgis/postgis/16-3.4/app?search_path=public"
  ...
}
```
