### ISSUE TITLE
ORM based Migration apply not working after applying once

### ISSUE THREAD

**Issue by althaf004** [ariga/atlas#2262]
hi, I was able to apply migration to a database using 
```
atlas migrate apply --env orm
```

After making few changes to the source file, ```diff``` command was run and new files where generated in migration folder.

When tried to run ```apply``` im getting response as ```No migration files to execute```

**Comment by a8m** [comment]
Hey @althaf004 👋 

Can you please paste here the `atlas.hcl` you used to generate migrations?

**Comment by althaf004** [comment]
hi @a8m , find below ```atlas.hcl```

```
data "external_schema" "orm" {
  # The first argument is the command to run,
  # and the rest are optional arguments.
  program = [
    "cat",    
    "schema.psql"
  ]
}

env "orm" {
  src = data.external_schema.orm.url
  dev = "docker://postgres/15/dev"
  url = "postgres://postgres:citrus123@10.10.11.249:5432/althaf3"
  migration {
    dir = "file://migrations"
  }
  format {
    migrate {
      diff = "{{ sql . \"  \" }}"
    }
  }
}
```

**Comment by a8m** [comment]
I don't see any problems with this configuration. Can you please paste the result of the following commands?

```shell
ls migrations
```

```shell
atlas migrate status --env orm
```

**Comment by althaf004** [comment]
please see the screenshot below.  
![image](https://github.com/ariga/atlas/assets/83403907/844c60fe-ddae-4fd8-87df-9263d8577ead)

ls migration had 4 files. I made some changes in sql file and run the diff again which changes the lists to 5.

**Comment by a8m** [comment]
OK, I'm not sure why I see `new` in the `Current Version`? Did you have a file named `new*.sql`in the migration directory before? If that's the case, we should warn or return an error. If not, can you send me the actual content of the `atlas_schema_revisions` table (Discord or here)?

**Comment by althaf004** [comment]
@a8m there was a  file named "new.psql ". Will try from initial steps with a different file name and will share the status.

**Comment by althaf004** [comment]
after providing a proper name the migration script start working properly. So i hope its to do with the file name,
