### ISSUE TITLE
Error: sql/sqlclient: unknown driver "libsql+ws". See https://atlasgo.io/url

### ISSUE THREAD

**Issue by zestsystem** [ariga/atlas#2274]
Hello I've been following the issue #1951, which was finally solved by  #2010 seemingly making local development with sqld possible. But I am still met with the `Error: sql/sqlclient: unknown driver "libsql+ws". See https://atlasgo.io/url` when I try to use `atlas schema apply` command against the local sqld instance. I am currently on v.0.15.0 of atlas.

I start my sqld process that listens on port 6969 with this: 
```bash
  turso dev --db-file db-file --port 6969
```

My atlas hcl: 
```hcl
variable "destructive" {
  type    = bool
  default = false
}

variable "token" {
  type    = string
  default = getenv("TURSO_DB_AUTH_TOKEN")
}

env "dev" {
  url     = "libsql+ws://localhost:6969"
  exclude = ["_litestream*"]
}

env "turso" {
  url     = "libsql+wss://${getenv("TURSO_DB_PRL")}?authToken=${var.token}"
  exclude = ["_litestream*"]
  diff {
    skip {
      drop_schema = !var.destructive
      drop_table  = !var.destructive
    }
  }
}
```
my atlas apply command
```
atlas schema apply --env=dev --var destructive=true --to file://schema.hcl
```

 My guess is that connecting to turso using a configuraton file has been left out and still only accepts wss:// scheme?

 https://atlasgo.io/guides/sqlite/turso (this doc only mentions libsql+wss://)

**Comment by giautm** [comment]
Hello, I ran your script without any issue on the canary version of atlas-cli. You can install that version using this script
```
curl -sSf https://atlasgo.sh | sh
```

Please try again and let me know if the issue still existing. Also, we have a guide for turso here: https://atlasgo.io/guides/sqlite/turso

<img width="629" alt="Screenshot 2023-11-10 at 16 28 58" src="https://github.com/ariga/atlas/assets/12751435/03b4218e-bac2-4f05-94e7-e3859c517cb7">

**Comment by zestsystem** [comment]
Ok I figured out where its going wrong... My nix flake for atlas v0.15.0  is failing to build so I was probably using v0.14.1 as fallback. Weird how it would show me the version 0.15.0 on `atlas version` though.

While 0.14.1 is built just fine, 0.15.0 fails to build.

<img width="1440" alt="Screenshot 2023-11-12 at 11 16 49 AM" src="https://github.com/ariga/atlas/assets/39456023/39ffb0eb-0463-49bb-9882-53b6d4138a69">

I think the problem is introduced with this change: 
cmd/internal/sqlparse/pgparse: move to pgquery (https://github.com/ariga/atlas/pull/2143)

Maybe this is relevant: 
https://discourse.nixos.org/t/trouble-packaging-sqlc/18261/9

My undertanding of go and nix isn't deep enough for me to be certain though. Will continue to explore this more.

**Comment by zestsystem** [comment]
The issue has been resolved with this PR:

https://github.com/NixOS/nixpkgs/pull/267409
