### ISSUE TITLE
JetBrains plugin Not compatible with the version of your running IDE (GoLand 2023.2.5)

### ISSUE THREAD

**Issue by sishui** [ariga/atlas#2293]
Not found from Marketplace in Goland 2023.2.5

**Comment by datdao** [comment]
Hi @sishui, thank you for reporting this. We will check and reply to you soon.

**Comment by datdao** [comment]
Hi @sishui , we have updated the plugin to be compatible with the latest version (2023.2.5). It will take some time to appear on the marketplace, so you can download the plugin through this link https://plugins.jetbrains.com/plugin/22307-atlas-hcl

**Comment by sishui** [comment]
THX @datdao
