### ISSUE TITLE
Can't generate baseline migration on existing database: Error: *schema.ModifySchema is not allowed when migration plan is scoped to one schema

### ISSUE THREAD

**Issue by veqryn** [ariga/atlas#2295]
Running this to generate a baseline:
`$ atlas migrate diff my_baseline --dir "file://sql/migrations" --to "mysql://user:${PASS}@sql-proxy.myenv.mycompany.net:3306/myschema" --dev-url "docker://mysql/8/myschema"`
Returns this error:
`Error: *schema.ModifySchema is not allowed when migration plan is scoped to one schema`

I was able to run this successfully:
`$ atlas schema diff --from "mysql://user:${PASS}@sql-proxy.myenv.mycompany.net:3306/myschema" --to "file://sql/db-schema.sql" --dev-url "docker://mysql/8/myschema"`
And that generated a lot of alter statements...

**Comment by a8m** [comment]
Hey @veqryn,
What MySQL version do you use? Also, what is the collation/charset in `myschema`? This is probably the issue (schemas attributes are different between databases).

**Comment by veqryn** [comment]
Trying with 5.6 and 5.7 just gives an error.  Seems there is no image that works on arm64:
```
Error: Unable to find image 'arigaio/mysql:5.7' locally
5.7: Pulling from arigaio/mysql
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.
See 'docker run --help'.
```

However, pulling it manually did work: `docker pull --platform linux/amd64 arigaio/mysql:5.7`
