### ISSUE TITLE
Migration containing ALTER DATABASE CHARSET causes new migration diffs to generate: Error: *schema.ModifySchema is not allowed when migration plan is scoped to one schema

### ISSUE THREAD

**Issue by veqryn** [ariga/atlas#2304]
One of our migration files contains this line:
`ALTER DATABASE myschema CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;`

This migration has been successfully applied to several of our environments already, without issue.

However, when trying to create a new migration, we get the following error:
```
$ atlas migrate diff my_migration --dir "file://sql/migrations" --to "file://sql/desired-end-state-db-schema.sql" --dev-url "docker://mysql/5.7/tokenization"
Error: *schema.ModifySchema is not allowed when migration plan is scoped to one schema
```

If I delete that line from the already run migration, recompute hashes, and rerun the migrate diff, it works successfully.

**Comment by a8m** [comment]
Hey @veqryn 👋🏻

As the error states, Atlas does not allow modifying specific schema attributes when the plan is scoped to a schema connection. This restriction exists because the plan could potentially be executed on any schema (tables not qualified with a schema name in this mode), and the modified schema might not exist.

To change the migration plan to target a database/instance (multiple schemas), remove the `tokenization` schema from the dev-url path. More examples can be found here: https://atlasgo.io/concepts/url

**Comment by a8m** [comment]
You are more than welcome to join our [Discord server](https://discord.com/invite/zZ6sWVg6NT) in case you need more help with this’🙂

**Comment by veqryn** [comment]
Uh... we have a lot of schemas and I'd like to make sure that any migrations created by junior devs don't accidentally step on other schemas, so we have set the schema in the path.

Why would modifying a schema not be allowed if the name matches the same name as the scoped schema?  That seems like it absolutely should be allowed, since they are the same...?

**Comment by a8m** [comment]
> Why would modifying a schema not be allowed if the name matches the same name as the scoped schema? That seems like it absolutely should be allowed, since they are the same...?

Because a plan with commands like this: `CREATE TABLE t(...)` (not qualified) can be executed on any schema. 

> Uh... we have a lot of schemas and I'd like to make sure that any migrations created by junior devs don't accidentally step on other schemas, so we have set the schema in the path.

You can do one of the following: don't manage schema charset/collate in this migration directory, or use a database connection but limit the `schemas` to a specific one.

**Comment by a8m** [comment]
<img width="1099" alt="image" src="https://github.com/ariga/atlas/assets/7413593/be1351e6-d95e-4983-836c-99ab0e5bfef9">
I hope this example can help.

**Comment by goluckycoding** [comment]
> <img alt="image" width="1099" src="https://private-user-images.githubusercontent.com/7413593/284827683-be1351e6-d95e-4983-836c-99ab0e5bfef9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMjg3NDUsIm5iZiI6MTcxMTAyODQ0NSwicGF0aCI6Ii83NDEzNTkzLzI4NDgyNzY4My1iZTEzNTFlNi1kOTVlLTQ5ODMtODM2Yy05OWFiMGU1YmZlZjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjFUMTM0MDQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGJjYmM2NzA0YWVmZDdmYzNmNzM4YWNmODE1MzNmYjE5M2E1OWUwY2RkNzVhZTQwYjU0YzlmZGFhNGQ4YzhmMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rGQwKgUJT9toNFKp8ldAfwG4x9rMGJqN1te-aXoiELA"> I hope this example can help. If you work on a schema connection, you can only work on objects in the scope of a schema (its objects). If you want to mutate/manage the database schemas, you need to work on instance/database level, not a schema.

how to run altas at database level ?
