### ISSUE TITLE
Exclude atlas_schema_revisions didn't work on diff with schema set

### ISSUE THREAD

**Issue by veqryn** [ariga/atlas#2305]
Two slightly different ways this came up:

```
atlas schema diff --from "mysql://root:@localhost:3306" --to "file://sql/desired-end-state-db-schema.sql" --dev-url "docker://mysql/5.7" --schema myschema --exclude "atlas_schema_revisions"
-- Drop "atlas_schema_revisions" table
DROP TABLE `myschema`.`atlas_schema_revisions`;
```

and
```
atlas schema diff --from "mysql://root:@localhost:3306" --to "file://sql/desired-end-state-db-schema.sql" --dev-url "docker://mysql/5.7" --exclude "atlas_schema_revisions"
-- Drop "atlas_schema_revisions" table
DROP TABLE `myschema`.`atlas_schema_revisions`;
```

I also tried `--exclude "*atlas_schema_revisions*"` but that didn't help.

**Comment by a8m** [comment]
Hey! The syntax is `<schema>.<table|view|...>.<resource>` when the scope is a database connection. See: https://atlasgo.io/declarative/inspect#exclude-tables

<img width="831" alt="image" src="https://github.com/ariga/atlas/assets/7413593/f5c4bfb1-3212-4817-96c3-99e241e1c1bf">
