### ISSUE TITLE
[PostgreSQL] Enhancing Zero-Downtime Migrations in PostgreSQL: Issue

### ISSUE THREAD

**Issue by varunnayal** [ariga/atlas#2345]
I encountered a challenge while attempting to implement zero-downtime migrations, as outlined in this article: [Zero-Downtime Postgres Schema Migrations: Lock Timeout and Retries](https://postgres.ai/blog/20210923-zero-downtime-postgres-schema-migrations-lock-timeout-and-retries).

To provide a clearer picture, I set up an environment with multiple terminals executing various SQL queries:

Terminal 1: Create a table using following SQL command

```sql
create table test as select 1 as i;
```

Terminal 2: Initiated a transaction to simulate a scenario where a long-running transaction occurs before migration:

```sql
begin;
select * from test;
```

Migration file: The migration file contained an alteration to the test table:

```sql
alter table test alter column i set not null;
```

Terminal 3: Executed the migration command:

```sh
atlas migrate apply \
  --dir "file://migrations" \
  --url "${PG_URL}"
```

This command stalled, waiting for the `select * from test;`` command from Terminal 2 to complete.

Terminal 1(continued): Attempted to select from the test table:

```sql
select * from test
```

However, this query was blocked by the `alter table`` statement in the migration from Terminal 3.

Issue:

- The atlas migrate apply command in Terminal 3 does not proceed due to the ongoing select statement in Terminal 2.
- Adding the --lock-timeout parameter to the atlas migrate apply command does not resolve the issue, as it appears to be intended for acquiring an advisory lock before executing migration statements rather than for handling this specific type of blocking.
- Blocked migration ends up stalling other queries too

Expectation:

- If migration takes more time to get the desired lock, it can abort. User can then retry the transaction
- This will ensure other queries(like simple read queries) are not blocked.

**Comment by kevbook** [comment]
I think the CLI should provide a `prepend` and `append` option so users add whatever they want. 
Eg. use case: prepend `SET ROLE "something"; `

**Comment by a8m** [comment]
> I think the CLI should provide a `prepend` and `append` option so users add whatever they want. Eg. use case: prepend `SET ROLE "something"; `

Thanks for the feedback, @kevbook. I feel like this fits better to the `migrate diff` (and other migration planning stages) rather than the execution. We actually have some work for this that we didn't release yet - a way to write custom policy as code (any code) for migration planning. 

For cases like controlling the client/transaction connections, e.g., setting `statement_timeout` or `lock_timeout` users can use migration hooks: https://atlasgo.io/versioned/apply#migration-hooks
