### ISSUE TITLE
Atlas HCL plugin for jetbrain is broken with phpstorm

### ISSUE THREAD

**Issue by jaugustin** [ariga/atlas#2365]
Hello,

The latest version of the plugin is not compatible with the latest version of phpstorm 2023.3.3

I think it's only a version restriction issue, can you check.

![image](https://github.com/ariga/atlas/assets/564420/08a2cf41-a2de-4b3c-95a1-27563672c533)

**Comment by giautm** [comment]
Hello @jaugustin, thank you for your report. We has a mismatch config on IntelliJ plugin and it rollout an newer version to the old IDEA. we update it, and it should affect after few minutes (Removed the warning message). Btw, If you can upgrade your PHPStorm to the latest version, it also works fine with new features.

**Comment by giautm** [comment]
Closing the issue now, If you still facing with this warning. Please let me known by comment on this issue. Thank you again,
