### ISSUE TITLE
Baseline schema example does not work for diff

### ISSUE THREAD

**Issue by alexisvisco** [ariga/atlas#2372]
Hey ! 

From your documentation https://atlasgo.io/concepts/dev-database#baseline-schema

```
variable "driver" {
  type = string
  default = "postgres"
}

variable "url_local_database" {
  type = string
  default = "postgres://postgres:postgres@localhost:5444/postgres?sslmode=disable"
}

locals {
  dev_url = {
    mysql = "docker://mysql/8/dev"
    postgres = "docker://postgres/pgextensioned"
    sqlite = "sqlite://file::memory:?cache=shared"
  }[var.driver]
}


docker "postgres" "dev" {
  image  = "postgres:16.1-alpine"
  schema = "public"
  baseline = <<SQL
   CREATE EXTENSION IF NOT EXISTS "uuid-ossp" SCHEMA "public";
   CREATE EXTENSION IF NOT EXISTS "hstore" SCHEMA "public";
  SQL
}


env "gen_mig" {
  src = "file://schema.sql"
  dev = docker.postgres.dev.url
  migration {
    dir = "file://./migrations"
  }
  format {
    migrate {
      diff = "{{ sql . \"  \" }}"
    }
  }
}

env "apply_mig" {
  url = var.url_local_database
  dev = local.dev_url
  migration {
    dir = "file://./migrations"
  }
  format {
    migrate {
      diff = "{{ sql . \"  \" }}"
    }
  }
}

```

running ` atlas migrate diff --env gen_mig` 

This result to `Unsupported attribute; This object does not have an attribute named "url".` 

Can you have some explanation ? If it's only available for applying migration I think there is a misconception from your part because why you wouldn't be able to have a baseline for generating diff ? Better question how to create those "first" migrations that you need to perform diff that just "works"with the extensions you might want to use ???? 

Thanks you.

**Comment by alexisvisco** [comment]
Directly from your repository : 

<img width="2560" alt="image" src="https://github.com/ariga/atlas/assets/17145294/c411abab-8cee-41c1-9aa7-94af2bf0064b">

**Comment by a8m** [comment]
Hey! What version of Atlas do you use?

**Comment by alexisvisco** [comment]
atlas version v0.14.3-ed5ffb8-canary
https://github.com/ariga/atlas/releases/latest

**Comment by alexisvisco** [comment]
Okay updated it and now it works

**Comment by a8m** [comment]
Updating Atlas using the following command should solve the issue:
```
curl -sSf https://atlasgo.sh | sh
```

Please reopen if you still have issues.
