### ISSUE TITLE
Bug: check_drop flag not honoured when running migrate lint command

### ISSUE THREAD

**Issue by varunnayal** [ariga/atlas#2375]
I am trying to play with `check_drop` lint flag(similar to `check_create`) for [concurrent_index](https://atlasgo.io/lint/analyzers#concurrent-index-policy-postgresql) and found issues.

`atlas.hcl`
```hcl
lint {
  concurrent_index {
    // or use error = true
    check_create = true
    check_drop   = true
    check_txmode = true
  }
}
```
Migration Files

`20231127200109.sql`
```sql
--atlas:txmode none

CREATE TABLE t1(c1 int);
CREATE INDEX CONCURRENTLY i1 ON t1 (c1);
```

`20231127200110.sql`
```sql
--atlas:txmode none

DROP INDEX CONCURRENTLY i1
```

Running `atlas migrate lint --dir file://migrations --dev-url "${DEV_URL}"` give following output

```sh
20231127200110.sql: concurrent index violations detected:

        L3: Dropping index "i1" non-concurrently causes write locks on the "c1" table
```
**Expectation**: It should not raise any error as `CONCURRENTLY` is set and atlas transaction mode is set to `none`.

**Comment by varunnayal** [comment]
PR: https://github.com/ariga/atlas/pull/2376

**Comment by a8m** [comment]
Thanks for reporting this and your contribution, @varunnayal. This should be addressed with https://github.com/ariga/atlas/pull/2377

**Comment by a8m** [comment]
> PR: #2376

I just saw this. I appreciate your willingness to help, but I saw it after I had already pushed it. Thanks again

**Comment by varunnayal** [comment]
@a8m 
For the PR #2377,
should
```go
case stmt.GetDropStmt() != nil && stmt.GetDropStmt().GetConcurrent():
	modify, err := expectModify(changes)
```

be changed to

```go
case stmt.GetDropStmt() != nil && stmt.GetDropStmt().GetConcurrent()
&& stmt.GetDropStmt().GetRemoveType() == pgquery.ObjectType_OBJECT_INDEX:
	modify, err := expectModify(changes)
```

**Comment by a8m** [comment]
Can you elaborate? I'm not aware of any other DROP command that supports the CONCURRENTLY clause.

**Comment by varunnayal** [comment]
Oh. Got it. Thats sums up the clause. Thanks again! :)
