### ISSUE TITLE
Dev DB initialization SQL

### ISSUE THREAD

**Issue by anuraaga** [ariga/atlas#2386]
We are using atlas with versioned migrations and golang-migrate. We manage roles outside of migrations in Terraform, mostly to allow tying them to passwords or other credentials, and then grant privileges in migrations. After adding a grant migration, using a manual migration, when executing `atlas migrate diff` we get an error we would expect when executing the migrations on a DB without the role

`pg: role "foo" does not exist`

It would be nice if it were possible to define initialization SQL before atlas runs operations on a local database, for example

```
env "local" {
  dev = "docker://postgres/15/dev"
  devInitSql = [
    "create role foo"
  ]
  migration {
    dir = "file://migrations"
    format = golang-migrate
  }
}
```

As a workaround, I currently temporarily rename migration files with grant statements and rehash before and after.

**Comment by a8m** [comment]
Hey @anuraaga 👋 

You can create these roles in a baseline migration file or use a `dev` driver with a baseline schema. See: https://atlasgo.io/concepts/dev-database#baseline-schema

BTW, roles will be added soon to Atlas and you will be able to manage them as well.

**Comment by anuraaga** [comment]
Ah thanks baseline schema with the docker driver is almost exactly what I was looking for. Though since it's login gated won't be able to use it unfortunately (I understand the need to monetize OSS it's not a bad thing).
