### ISSUE TITLE
[Question] Database clean check for a single schema for atlas migrate

### ISSUE THREAD

**Issue by varunnayal** [ariga/atlas#2387]
Is there a way to run `migrate lint` or `migrate apply` on a single(or multiple) schema(s), say `public`.

So, I have a scenario where some extra extensions are loaded into the database and I want to use atlas command only for a particular schema.

- Loaded Extensions
```sql
create extension pg_repack;
```

- Version file
```sql
create table a(int i);
```

Running `atlas migrate {apply|lint}` command errors out stating the database is not clean.

**Comment by a8m** [comment]
Hey @varunnayal 👋 

Yes, you can set `search_path=public` to set the context to schema-scope, in this case `public`. Or, use multiple schemas using the -s option.
