### ISSUE TITLE
Ent scheme is no longer supported

### ISSUE THREAD

**Issue by jakubno** [ariga/atlas#2388]
When running `atlas migrate diff test  --dir "file://ent/migrate/migrations"--to "ent://ent/schema" --dev-url "docker://postgres/15/dev"`

I now receive following error:
```
Error: ent:// scheme is no longer supported by this release. See: https://atlasgo.io/getting-started
```

I didn't find any mention about this on the website. Will there be some provider similarly as for [gorm](https://github.com/ariga/atlas-provider-gorm)?

**Comment by a8m** [comment]
Hey @jakubno 👋 

How did you install Atlas? Please install using `curl -sSf https://atlasgo.sh | sh` and re-run the command.

**Comment by jakubno** [comment]
I compiled it from source from `master` branch. I wanted to add possibility to skip dropping function when generating diff migrations. 

I am running `go build .` in `cmd/atlas`

**Comment by jakubno** [comment]
It works for me on version `v0.15.1-10d0fb0-canary`. It looks it was introduced here: https://github.com/ariga/atlas/commit/d7c2fcef28b67213e8e089ff9126ada321e4ee40

**Comment by a8m** [comment]
As mentioned in the error message, the `ent` loader is not part of this release. Functions, procedures, and some other parts do not exist in this repo as well. If you want to ignore `DROP FUNCTION` changes, we can add it to the skip-policy: https://atlasgo.io/versioned/diff#diff-policy.

**Comment by jakubno** [comment]
That's what I've tried. I can create PR for that.

Is it possible to build whole CLI locally?

**Comment by a8m** [comment]
> That's what I've tried. I can create PR for that.

No need, because I already have the code for that and we can export it. It will land later today. 

> Is it possible to build whole CLI locally?

No, the binary we release contains internal code for interacting with Atlas Cloud and some beta/pro features.

**Comment by jakubno** [comment]
I see, thanks and have a nice day!

**Comment by a8m** [comment]
Closed with https://github.com/ariga/atlas/pull/2395.

Please, update the Atlas binary to use new options. Thanks for reporting this.
