### ISSUE TITLE
 atlas migrate checkpoint straight up broken?

### ISSUE THREAD

**Issue by advanderveer** [ariga/atlas#2430]
Atlas's checkpoint functionality would be useful to us but currently it seems to be straight up broken. I have the following in ./migrations:

`migrations/20240110180000_base.sql`
```sql
-- initial setup with some schema changes
CREATE SCHEMA IF NOT EXISTS "public";
-- some stored procedur
CREATE PROCEDURE hello_world()
LANGUAGE plpgsql
AS $$
BEGIN
RAISE NOTICE 'Hello world';
END
$$;
```

`migrations/20240111060407.sql`
```sql
-- Create "users" table
CREATE TABLE "users" ("id" character varying(21) NOT NULL, PRIMARY KEY ("id"));
```

`migrations/20240111060440.sql`
```sql
-- Modify "users" table
ALTER TABLE "users" ADD COLUMN "foo" character varying NOT NULL;
```

`atlas.hcl`
```hcl
variable "database_url" {
  type = string
  default = "postgres://postgres:postgres@localhost:55435/postgres?sslmode=disable"
}

env "local" {
  url = var.database_url 
  dev = "docker://postgres/14/dev?search_path=public"
  
  migration {
    dir = "file://migrations"
    format = "atlas"
  }
}
```

When I run: `atlas migrate checkpoint --env=local`:

`migrations/20240111062228_checkpoint.sql`
```sql
-- atlas:checkpoint

-- Create "users" table
CREATE TABLE "users" ("id" character varying(21) NOT NULL, "foo" character varying NOT NULL, PRIMARY KEY ("id"));
```

My issue is a follows:
1. Where is the "CREATE PROCEDURE" and "CREATE SCHEMA"?
2. When I run `atlas migrate checkpoint --env=local` it just keeps creating more checkpoints with the same, shouldn't it notice that the latest checkpoint is fully up-to-date?

Version:
```
atlas version v0.17.0
https://github.com/ariga/atlas/releases/tag/v0.17.0
```

**Comment by a8m** [comment]
Hey @advanderveer 👋🏻 

Schema creation operations are not added when the dev URL is scoped to a specific schema. Objects are defined without schema qualifiers because the schema is expected to be predefined in the database.

Functions, procedures, views, etc., require `atlas login`.

**Comment by a8m** [comment]
Closing, but please feel free to reopen or join the [Discord](https://discord.gg/zZ6sWVg6NT) in case you need more help with this 😄

**Comment by a8m** [comment]
> Thank you for the quick response! I've tried that, but now atlas migrate diff --env=local --to=ent://schema will complain about: Error: missing schema in --dev-url.

Ent schemas are always scoped to a specific schema. i.e., all Ent queries/operations are executed without qualifiers by default. Are you working in multi-schema mode?

> I'm not sure what you mean with "Functions, procedures, views, etc., require atlas login.", is there more documentation about what is exactly possible with or without atlas login? It feels like I'm being pushed into a paid plan

Sure, check out this: https://atlasgo.io/atlas-schema/hcl. The [community version/plan](https://atlasgo.cloud/pricing) of Atlas Cloud is really generous and should not be a blocker for most users.

**Comment by advanderveer** [comment]
I'm not sure what "multi-schema" mode means. I've trying searching the documentation but can't find a reference to that term. There is an old blog post: https://atlasgo.io/blog/2022/02/01/atlas-v032-multi-schema but that seems to refer to declarative workflow.

If it's more a general question of "do I want to use multiple schemas", prime requirements is being able to put everything into a differently named schema from "public", i.e: a schema named "my_project". BUT, It would be highly desirable to for us to allow supporting multiple schemas down the road, being locked into a single schema for the rest of the project is a no-go.

> Sure, check out this: https://atlasgo.io/atlas-schema/hcl. The [community version/plan](https://atlasgo.cloud/pricing) of > Atlas Cloud is really generous and should not be a blocker for most users.

Thank you, having to login for declaring views, functions etc suggests that such functionality could become a paid feature in the future. But maybe that is a discussion for another place.
