### ISSUE TITLE
Feature: Support mixed --to urls

### ISSUE THREAD

**Issue by advanderveer** [ariga/atlas#2432]
I'm trying to get a satisfying migration setup going for Ent. The declarative approach seems promising but it seems i can ONLY get the schema from ent, and not from other sources. When I use `atlas schema apply --env=ent` with: 

```hcl
variable "database_url" {
  type = string
  default = "postgres://postgres:postgres@localhost:55435/postgres?sslmode=disable"
}

env "ent" {
  src = ["ent://schema", "file://schema/extra.hcl"]
  url = var.database_url 
  dev = "docker://postgres/14/dev"
}
```

It complains with `Error: got mixed --to url schemes: "ent" and "file", the desired state must be provided from a single kind of source`. Which is clear. 

But locking me into just using "ent://schema" prevents me from adding other postgres things like procedures, views, etc.  I might be able to do this within Ent but it would be nice to just use sql or hcl for these other things.

**Comment by a8m** [comment]
Thanks for the suggestion. Schema composition is something that is going to be added in the next release (probably today). See this: https://github.com/ariga/atlas/pull/2428 

Closing as there's no action to take here.
