### ISSUE TITLE
Can't install to Ubuntu using Homebrew

### ISSUE THREAD

**Issue by tom-uchida** [ariga/atlas#2452]
I tried to install on Ubuntu with WSL2, but the following error occurred:

```bash
$ brew install ariga/tap/atlas
Error: ariga/tap/atlas: undefined method `downcase' for nil:NilClass
```

My Ubuntu version: 
```bash
$ cat /etc/issue
Ubuntu 20.04.6 LTS \n \l
```

My Homebrew version:
```
$ brew --version
Homebrew 4.2.4
```

Do you know the cause and solution?

**Comment by rotemtam** [comment]
Hey @tom-uchida 

Homebrew currently only works for macOS, on linux the simplest way to install is running:
```sh
curl -sSf https://atlasgo.sh | sh
```

**Comment by tom-uchida** [comment]
@rotemtam 
Thank you for your quick response!

I tried curl first, but I got a curl error: 
```bash
$ curl -sSf https://atlasgo.sh | sh
Install 'atlas-linux-amd64-latest' to '/usr/local/bin/atlas'? [y/N] y
Downloading https://release.ariga.io/atlas/atlas-linux-amd64-latest
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

There was an article that said that adding the `-k` or `--insecure` option would solve the problem, so I tried that, but the result did not change.

**Comment by tom-uchida** [comment]
@giautm 

Looks correct.
```bash
$ date
Wed Jan 17 17:18:43 JST 2024
```

**Comment by giautm** [comment]
@tom-uchida: I've no idea. But I'm sure I can install the Atlas CLI both ways. Please check your machine again. or maybe call cURL with a different URL (like github.com) to check if the SSL issue also happens.

If we can help with anything, please let us know.

**Comment by snps-ravinu** [comment]
@tom-uchida , I have the same issue with curl in ubuntu docker container, I have verified that curl works with other endpoints like google.com, etc.  How did you resolve this?

**Comment by tom-uchida** [comment]
@snps-ravinu 

Sorry, I gave up and installed it on Windows.

**Comment by snps-ravinu** [comment]
@giautm , I can confirm I am facing the same issue, I have tried curl with other urls and it works fine. I tried to set timezone to utc as well, nothing worked. To reproduce it, I request you to use this dockerfile, 

`sh
FROM ubuntu:latest
WORKDIR /app  

RUN apt-get update && apt-get install -y curl

COPY . .
  
EXPOSE 8080  

CMD ["curl -sSf https://atlasgo.sh"]`


When you try to build it, you will get the error, you can try it from the docker container as well by commenting the last cmd and running it

**Comment by giautm** [comment]
@snps-ravinu you dockerfile is invalid. because `CMD` is used for run the application, not for execute any script during the build process. Please use the `RUN` command instead

```shell
FROM ubuntu:latest
WORKDIR /app

RUN apt-get update && apt-get install -y curl

COPY . .

EXPOSE 8080

RUN curl -sSf https://atlasgo.sh | sh -s
```

<img width="798" alt="Screenshot 2024-08-08 at 20 41 48" src="https://github.com/user-attachments/assets/2eac0404-a842-4cf1-880e-4a4a59ba60a0">

Test:

<img width="709" alt="Screenshot 2024-08-08 at 20 42 58" src="https://github.com/user-attachments/assets/e3439a4b-f84f-4a54-b744-a3379ec53d75">

**Comment by snps-ravinu** [comment]
@giautm , thank you for the quick response. CMd can be used with shell as well, after that I was running it with I was using, docker run -d migrationimage name -f  bash -c "tail -f /dev/null"

I have tried your suggestion as well, it is the same :(
![image](https://github.com/user-attachments/assets/affc4337-a7fe-4fd0-9411-ffa94df80c72)

**Comment by giautm** [comment]
Did you see the download process during build? If it has, the binary should be put in the PATH

**Comment by giautm** [comment]
btw, you can use our docker image here as the base for run migration.

https://hub.docker.com/r/arigaio/atlas
