### ISSUE TITLE
Comments fail on overloaded functions

### ISSUE THREAD

**Issue by maciejb** [ariga/atlas#2460]
Consider the following Postgres SQL schema:

```sql
CREATE FUNCTION foo(arg TEXT) returns TEXT AS $$ SELECT arg; $$ LANGUAGE SQL;
COMMENT ON FUNCTION foo(TEXT) IS 'text foo';

CREATE FUNCTION foo(arg INT) returns INT AS $$ SELECT arg; $$ LANGUAGE SQL;
COMMENT ON FUNCTION foo(INT) IS 'int foo';
```

The `migrate diff` for it will generate:

```sql
-- Create "foo" function
CREATE FUNCTION "public"."foo" ("arg" text) RETURNS text LANGUAGE sql AS $$ SELECT arg; $$;
-- Set comment to function "foo"
COMMENT ON FUNCTION "public"."foo" IS 'text foo';
-- Create "foo" function
CREATE FUNCTION "public"."foo" ("arg" integer) RETURNS integer LANGUAGE sql AS $$ SELECT arg; $$;
-- Set comment to function "foo"
COMMENT ON FUNCTION "public"."foo" IS 'int foo';
```

Note the lack of `INT` vs `TEXT` qualification on the `COMMENT ON` lines.

The next `migrate diff` will then fail because Postgres does now know which version of the function we want to apply the comment to:
```
Error: sql/migrate: read migration directory state: sql/migrate: executing statement "COMMENT ON FUNCTION \"public\".\"foo\" IS 'int foo';" from version "20240120002843": pq: function name "public.foo" is not unique
```

**Comment by PFJoey** [comment]
This issue stops us from taking Atlas into test phase for our company.

**Comment by a8m** [comment]
This issue was fixed in the latest version. Please, update atlas and report if you still encounter any issues with it.  

<img width="1074" alt="image" src="https://github.com/ariga/atlas/assets/7413593/95364f63-4703-44fa-bd65-c000d10ff805">
