### ISSUE TITLE
Add support for Postgres LTREE

### ISSUE THREAD

**Issue by Maxpnl** [ariga/atlas#2462]
Hello, it would be super nice to get support for LTREE columns in postgres.

https://www.postgresql.org/docs/current/ltree.html

Thanks :)

**Comment by a8m** [comment]
Hey, @Maxpnl 👋🏻

User-defined or extension types are already supported as explained here: https://github.com/ariga/atlas/issues/2277#issuecomment-1806862171

Closing, but please feel free to reopen if you still need help with this.
