### ISSUE TITLE
Requiring login for beta

### ISSUE THREAD

**Issue by cemo** [ariga/atlas#2463]
Hi all, 

we are experimenting atlas in our workflow and we would like to use atlas terraform provider. I guess it is not possible to use atlas terraform provider with beta capabilities since it requires login. Would you please make login constraint for beta features optional? 

Thanks

**Comment by giautm** [comment]
Hello, login is not require if you use the token flow. Please give a try and let me if it works or not.

**Comment by a8m** [comment]
> Hello, login is not require if you use the token flow. Please give a try and let me if it works or not.

This should work. Please reopen if not.

**Comment by giautm** [comment]
Hello @cemo, you can create a bot account on your organization, and it will generate a token to use with Terraform. More detail on this link: https://atlasgo.io/cloud/bots

**Comment by cemo** [comment]
I opened an issue on the provider. This is causing 401s. 

Would you please consider not requiring login for beta features?

**Comment by a8m** [comment]
> I opened an issue on the provider. This is causing 401s.

Are you getting 401 only in the provider or also in the CLI?

> Would you please consider not requiring login for beta features?

Not in the foreseeable future.
