### ISSUE TITLE
VSCode extension doesn't work correctly on Windows

### ISSUE THREAD

**Issue by mmorton** [ariga/atlas#2473]
When the extension tries to download the language server, it does not append a `.exe` extension to the download URL (i.e. `https://release.ariga.io/atlas-ls/atlas-ls-${n}-${i}-${t}`) on Windows, resulting in a 404 error. It also does not append a `.exe` extension to the local file either, which causes it not to be able to start the LS. 

When I applied both fixes to my locally installed `extension.js` it does work, though with an `EBUSY` error on the first start after the download.

**Comment by datdao** [comment]
Hi @mmorton , thank you for reporting this. May I ask which operating system architecture (e.g., x64, x32) you are using?

**Comment by mmorton** [comment]
x64

**Comment by datdao** [comment]
Hi @mmorton, we've fixed the issue on the Windows platform. Please upgrade your VSCode to version 0.4.3
