### ISSUE TITLE
Is it possible to apply the migrations, without storing them as files?

### ISSUE THREAD

**Issue by sunilgandipadala** [ariga/atlas#2480]
I am running my project using docker engine, and I can run my project and store the migration files which will be generated locally, so I can pass **--dir** with by that path/Url and then can perform Apply. 

Now can I able to do this, without saving the migrations into a file, by directly applying?

**Comment by rotemtam** [comment]
You have two alternatives: 
1. Use declarative migrations read about the `atlas schema apply` command. 
2. You can store the migrations in Atlas Cloud using `atlas migrate push` during CI. Then during deployment you can apply from `atlas://dirname`. Then you can skip the annoyance of needing to build a container and to have it available in your deployment infra.
