### ISSUE TITLE
Foreign key from another schema

### ISSUE THREAD

**Issue by polter05** [ariga/atlas#2484]
Hi,

I have some foreign keys from another schema (another base on same server mariadb).

When I use atlas schema inspect, I have : 

> Error: template: inspect:1:4: executing "inspect" at <$.MarshalHCL>: error calling MarshalHCL: missing reference for column "$table.xxx.$column.xxx" in "xxxx"."xxx"."xxxx_ibfk_10". But all the keys, on both bases, are ok.

Can you help me ?
Tks

**Comment by a8m** [comment]
Hey! To inspect a schema that links to another schema, you need to either inspect both or exclude the specific foreign key that points to the other schema. See these options: https://atlasgo.io/declarative/inspect#inspect-a-database.

```
atlas schema inspect -u mysql://root:pass@:3307/s1 --exclude 't1.*[type=fk]'
```

Closing, but please feel free to join our [Discord server](https://discord.gg/zZ6sWVg6NT) in case you need more help with this.
