### ISSUE TITLE
Atlas Isn't considering the Changes that were done, manually.

### ISSUE THREAD

**Issue by sunilgandipadala** [ariga/atlas#2494]
Hi @rotemtam 
I had done some changes to my db, which were modified to models and generated migration to the changes and the changes were done manually(which were generated through atlas diff) and removed that changes from the migration file and performed **hash**.  later again tried to perfrom **atlas migrate diff --env gorm**, but it is again giving the changes that were already done.

I want it has to recognize the changes done manually and it won't report the changes which were done to db manually.

Ex: 

And,
model changes. 
![image](https://github.com/ariga/atlas/assets/65104532/c968995c-d188-4e2a-9277-813d6ea90820)

First Generated Migration File:
![image](https://github.com/ariga/atlas/assets/65104532/a0674893-b057-4990-a009-67ae1ec64532)
After clearing the changes.-->(just to apply them manually-mainly alter statements)
![image](https://github.com/ariga/atlas/assets/65104532/426e367a-84ed-441f-930a-00ab19996c90)
[Removed the generated queries]

These are the updated column names  - Manually
![image](https://github.com/ariga/atlas/assets/65104532/1f5a0a4a-0a86-4bdf-aec0-3bfa96023061)

Now, again run diff
![image](https://github.com/ariga/atlas/assets/65104532/a0674893-b057-4990-a009-67ae1ec64532)
Same changes/queries were again coming.

**Comment by noamcattan** [comment]
Hello, @sunilgandipadala!
Can you share the relevant parts of your `atlas.hcl` file so we can have more context?

**Comment by sunilgandipadala** [comment]
Hi @noamcattan,

`variable "destructive" {
  type    = bool
  default = false
}


data "external_schema" "gorm" {
  
  program = [
    "go",
    "run",
    "main.go",
    "migrate",
    "-mod=mod",
    "./",
  ]
}

env "gorm" {
  src = data.external_schema.gorm.url
  //url = "mysql://root:Sunil@513@:3306/employees"
  url = "postgres://postgres:postgres@904@172.31.50.134:5432/sunilpg?search_path=public&sslmode=disable"
  
  //to use versioned migration
  dev = "docker://postgres/15/dev"
  //dev = "docker://mysql/8/dev"
  migration {
    dir = "file://migrations"
  }
  format {
    migrate {
      diff = "{{ sql . \"  \" }}"
    }
  }
  diff {
    skip {
      drop_schema = !var.destructive
      drop_table  = !var.destructive
    }
  }
}`

**Comment by noamcattan** [comment]
To generate a migration based on the current state of a running database, you can set the "src" property in the env block to be the url of the database, or pass is as argument to the cli like so:
```
atlas migrate diff --dev-url "docker://postgres/15/dev" --to "postgres://..."
```
