### ISSUE TITLE
Preventing AUTO_INCREMENT Value Comparisons in Inspect and Diff Commands

### ISSUE THREAD

**Issue by Sau64** [ariga/atlas#2500]
Is it possible to avoid comparing and dumping the starting value of AUTO_INCREMENT in the inspect and diff commands?

Each time I create a new branch, I take a snapshot (inspect) of the master database, and before merging, I generate the changes. I've noticed this issue only occurs when using --format "{{ sql . }}", which is necessary for my workflow.

I do not want to generate incremental changes like the following:

```
./db_diff.sh
-- Modify "logins" table
ALTER TABLE `logins` AUTO_INCREMENT=1212;
-- Modify "logs" table
ALTER TABLE `logs` AUTO_INCREMENT=133052;
-- Modify "pages" table
ALTER TABLE `pages` AUTO_INCREMENT=4;
-- Modify "phrases" table
ALTER TABLE `phrases` AUTO_INCREMENT=436;
```

Thanks for any help with this issue.

**Comment by Kevinello** [comment]
How did you solve this problem?👀

**Comment by garfildalex6** [comment]
> How did you solve this problem?👀

Were you able to solve the problem?

**Comment by Sau64** [comment]
I ended using hcl format
