### ISSUE TITLE
Cannot get composite_schema to work

### ISSUE THREAD

**Issue by advanderveer** [ariga/atlas#2531]
This works: 

```
env "local" {
  src = "ent://schema"
  url = "postgres://postgres:postgres@localhost:55438/postgres?sslmode=disable&search_path=public"
  dev = "docker://postgres/16/dev?search_path=public"
}
```

This does not work: 
```
data "composite_schema" "project" {
  schema "graph" {
    url = "ent://schema
  }
}

env "local" {
  src = data.composite_schema.project.url
  url = "postgres://postgres:postgres@localhost:55438/postgres?sslmode=disable&search_path=public"
  dev = "docker://postgres/16/dev?search_path=public"
}
```

I get: 
```
Error: cannot diff a schema with a database connection: "public" <> ""
Error: failed to apply: failed to run atlas: running "atlas schema apply --config file://atlas.local.hcl --env local --auto-approve" failed with exit code 1
```

**Comment by rotemtam** [comment]
The composite schema by definition is db scope, while your env url is schema scoped (search_path=public), which is incompatible. Drop the search path param and you should be ok.
HTH

**Comment by advanderveer** [comment]
That indeed seems to work although I'm almost certain that I've tried it. Anyhow it does raise confusion for me as to what the  "schema" directive in the composite_schema configuration actually is? does it need to be an actual schema in postgres or is it another concept? 



What if multiple are defined and how is the ordering? For example, when I do this:

```
data "composite_schema" "project" {
  schema "public" {
    url = "ent://schema"
  }
  schema "public" {
    url = "file://schema/schema.sql"
  }
}
```

Is the second schema.sql always "applied" after the ent schema?

If I change the configuration to be this: 

this seems to not change anything
```
data "composite_schema" "project" {
  schema "public" {
    url = "ent://schema"
  }
  schema "foo" {
    url = "file://schema/schema.sql"
  }
}
```

It does create a "foo" schema. But if the schema.sql contains fully qualified table names (into public for example) the "foo" doesn't seem to do a lot?

**Comment by a8m** [comment]
The issue was resolved with latest build, and the doc was updated accordingly: https://atlasgo.io/atlas-schema/projects#data-source-composite-schema-arguments (open the Usage Details box). 

Please reopen in case you need more help with this.
