### ISSUE TITLE
Rangetype constraints with `EXCLUDE USING GIST`

### ISSUE THREAD

**Issue by asger-noer** [ariga/atlas#2551]
Hi, 

Thanks for the great project. It is really cool!

I'm building a small booking system that requires similar logic on the `tstxrange` as  what is mentioned in the PostgreSQL docs on  [range-type constraints](https://www.postgresql.org/docs/current/rangetypes.html#RANGETYPES-CONSTRAINT). I'm not completely sure if this is something I can accomplish with Atlas HCL at the moment. 

Basically I want to the create a constraint that will reject overlapping ranges only if the meeting room are equal. Something like this:

```sql
CREATE EXTENSION btree_gist;
CREATE TABLE room_reservation (
  room text,
  during tsrange,
  EXCLUDE USING GIST (room WITH =, during WITH &&)
);
```

From what I can read the following thing prevents be from creating this index:
- Creation of the `btree_gist` extension
- There seem to be no way of modelling `EXCLUDE USING GIST` using HCL

**Comment by a8m** [comment]
Thanks for reporting this. This was addressed in the latest release. Please, see https://atlasgo.io/atlas-schema/hcl#exclude-constraints for more info
