### ISSUE TITLE
Visualize don't work for `ent` in `go 1.22.0`

### ISSUE THREAD

**Issue by DanArmor** [ariga/atlas#2561]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ariga/atlas/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

I run command from the root of the project
```bash
atlas schema inspect \
-u "ent://ent/schema" \
--dev-url "docker://postgres/15/test?search_path=public" \
-w
```
And got the output: 
```
Error: loading schema: entc/load: no schema found in: <path-to-my-project>/ent/schema
```
(for publicly and privately visualization)
I tried to change path, run command from another directory, provide full path - nothing did work

I have `go 1.22.0` in my go.mod

If I change that to `go 1.21` - the same command works fine

## Expected Behavior 🤔

Work with `go 1.22.0` in go.mod

## Steps to Reproduce 🕹

Steps:

1. Create simple project with few entities
2. Set `go 1.22.0` in go.mod
3. Run the command described above. You will got the error
4. Change `go 1.22.0` to `go 1.21`
5. Run the command described above. It will work

Screenshot:
![Screenshot_20240220_171346](https://github.com/ariga/atlas/assets/39347109/7ebf7d2a-ef09-472f-9e45-d47a5e928b02)

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.22.0  |
| Ent         | 0.13.0   |
| Database    | PostgreSQL   |

**Comment by a8m** [comment]
Hey! This was fixed in the latest version. Can you try reinstalling Atlas and report if this solved the issue?

**Comment by DanArmor** [comment]
> Hey! This was fixed in the latest version. Can you try reinstalling Atlas and report if this solved the issue?

Thanks, that really works. I installed atlas a few days ago (maybe, feb 17-th) and didn't expect, that it was patched right after that day. Sorry for false issue :)
