### ISSUE TITLE
ClickHouse: flatten_nested = 0 / multiple levels of nested not supported

### ISSUE THREAD

**Issue by antoinematyja** [ariga/atlas#2569]
Hi,

I am new to Atlas and still playing with it. I would like to use it with my ClickHouse database but I have an issue because I have a table with a column using multiple levels of nested.

In ClickHouse there is a nested column type:
https://clickhouse.com/docs/en/sql-reference/data-types/nested-data-structures/nested

And there is a setting [flatten_nested](https://clickhouse.com/docs/en/operations/settings/settings#flatten-nested) (set to 1 by default) that transforms nested columns into one (array) column for each field of the nested type.
Atlas works well with this: if a run an `atlas schema inspect` it will show the flatten columns, both HCL and SQL work fine.

However if I `SET flatten_nested = 0` before creating a table (for example to have a nested in a nested), Atlas will not be able to export the schema.

For a table with only 1 level of nested, created with `SET flatten_nested = 0`
- schema.hcl will have a column with `type = sql("Nested")` (it's missing the types of the fields inside the nested)
- schema.sql will have a blank line where the column should be (schema.sql is incomplete but no error was raised)

For a table with 2 levels of nested (nested in nested), again created with `SET flatten_nested = 0`
- schema.hcl will raise an error:
  ```
  Error: template: inspect:1:4: executing "inspect" at <$.MarshalHCL>: error calling MarshalHCL: specutil: failed converting schema to spec: clickhouse: unsupported type *schema.UnsupportedType
  ```
- schema.sql will have a blank line where the column should be (again no error raised)

This is quite an edge case and few people use this feature of ClickHouse so I'm not sure if you want to support this in Atlas.

**Comment by giautm** [comment]
Hello @antoinematyja, yes. This is an edge case. The nested structure doesn't play well with our HCL presentation. Or event with `sql("")`. So we decided to delay the support a bit and hear feedback from the community before bring it to Atlas-CLI.

May I ask some question please? How did you use ClickHouse DB with your application? It's primary storage or the storage for Data Warehouse?

**Comment by antoinematyja** [comment]
Thanks for the quick reply 👍🏻 

We currently use ClickHouse as primary storage for user interactions, and we would like to use it also for our core data for faster queries.

Here is a simplified version of our `events` table to store user interactions:

```
CREATE TABLE `events` (
  `id` UUID DEFAULT generateUUIDv4(),
  `timestamp` DateTime64(3),
  `service_id` UInt32,
  `action` String,
  ...
  `stores` Nested(
    `id` UInt32,
    `products` Nested(
      `id` UInt32,
      `price` Nullable(Decimal(18, 3))
    )
  )
) ENGINE = MergeTree()
```

**Comment by datdao** [comment]
Hi @antoinematyja, we now support the `Nested` data type in the latest Atlas version. You can find the documentation here:
https://atlasgo.io/atlas-schema/hcl-types#nested

Let us know if you encounter any issues!
