### ISSUE TITLE
suppor triggers migration in PostgresSQL

### ISSUE THREAD

**Issue by atazangene** [ariga/atlas#2575]
Hi, I am using the atlas inspect cli to migrate the code 

https://atlasgo.io/cli/getting-started/inspection

however, it does not get the postgers triggers.

how can I inspect and load triggers and then migrate that?

**Comment by a8m** [comment]
Hey! Triggers require login to Atlas. Please, see: https://atlasgo.io/declarative/inspect#automatic-schema-inspection

Closing, but feel free to reopen if you still encounter issues.

**Comment by atazangene** [comment]
Thanks, how can I login with cli? 
I am using the inspect command with GitHub action

**Comment by noamcattan** [comment]
You can use the setup action and provide a cloud token:
https://github.com/ariga/setup-atlas

**Comment by a8m** [comment]
The GitHub Action accepts a `cloud-token` as an option. See: https://github.com/ariga/atlas-action?tab=readme-ov-file#arigasetup-atlas

**Comment by a8m** [comment]
Thanks @noamcattan for the help - we commented at the same time :D

**Comment by atazangene** [comment]
Thanks All!
