### ISSUE TITLE
Support Azure Sql Database and using Azure AD or Workload Identity Authentication

### ISSUE THREAD

**Issue by markphillips100** [ariga/atlas#2590]
This is a 2-part question really.

1. Does atlas support Azure SqlDatabase?  I see there's a beta driver for MSSQL so can this be used for the Azure product?
2. If it does, do I have to specify credentials, or will more secure options be available, such as Workload Identity?

**Comment by markphillips100** [comment]
I've just seen issue #2343 so my guess is it's a no for question 2.  I'll add a comment there.

**Comment by markphillips100** [comment]
I should have added that I'm specifically interested in using the Atlas operator for running the schema update rather than the CLI, although the CLI would be very useful in addition.

**Comment by giautm** [comment]
We have run tests on azure-sql, sqlserver-2017, sqlserver-2019, and sqlserver-2022. About the Azure AD auth, we didn't support it yet. only user-pass is supported at the moment.

**Comment by giautm** [comment]
@markphillips100 yes, we used [microsoft/go-mssqldb](https://github.com/microsoft/go-mssqldb) for connect to SQL server. But currently don't use package `azuread` yet. I think we will and this soon in the next week.

**Comment by markphillips100** [comment]
That's great news.  I'm available if you need me to test it out.

**Comment by giautm** [comment]
hey, can you please DM me on our discord? I need your help for azure ad, it's a bit hard to testing on my end.

**Comment by giautm** [comment]
Hello @markphillips100, thank you for helping me test AAD support. Please let me know if you have any questions.
