### ISSUE TITLE
Error: role does not exist

### ISSUE THREAD

**Issue by sarahdipiero-igenius** [ariga/atlas#2591]
Hi,
I am making Atlas operator in Terraform:

`````````
resource "helm_release" "atlasgo-operator" {
  name             = "atlasgo-operator"
  repository       = "oci://ghcr.io/ariga/charts"
  chart            = "atlas-operator"
  namespace        = "atlas-operator"
  create_namespace = true
}
`````````

and I create a schema (all the variables are double checked):
`````````
apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasSchema
metadata:
  name: atlasgoapp
  namespace: atlas-operator
spec:
  credentials:
    scheme: postgres
    host: ${db_host}
    user: ${db_username}
    password: ${db_password}
    database: ${database_name}
    port: 5432
  schema:
    sql: |
      CREATE SCHEMA ${schema_name} AUTHORIZATION ${schema_owner};
  policy:
    diff:
      skip:
        drop_column: true
        drop_table: true
        drop_schema: true
    lint:
      destructive:
        error: false
`````````

but when I terraform plan then apply I have the following error:

`2024-03-04T10:32:15Z    DEBUG    events    Error: read state from "schema.sql": executing statement: "CREATE SCHEMA atlasgo_schema_2 AUTHORIZATION provisioner;": pq: role "provisioner" does not exist    {"type": "Warning", "ob │
│ ject": {"kind":"AtlasSchema","namespace":"atlas-operator","name":"atlasgoapp","uid":"c048bae6-be1f-4264-bb14-588c09985bcf","apiVersion":"db.atlasgo.io/v1alpha1","resourceVersion":"35147420"}, "reason": "Error"}`

**The role exists**
![Screenshot 2024-03-04 alle 12 00 08](https://github.com/ariga/atlas/assets/152958926/0119c61e-842a-48f5-90ef-4c12c41c1759)

The database sslmode is _prefer_ but atlas does not support prefer mode (just disable, require, verify-ca and verify-full). I don't know if this could be the cause of this problem. However I tried _disable_ and _require_ and they don't work.

**Comment by rotemtam** [comment]
Hi,

Atlas runs your desired state on an empty database called a [dev database](https://atlasgo.io/concepts/dev-database) to calculate the diff. That db is an empty Postgres, that doesn't contain that role. The error happens when Atlas tries to create your schema on that dev db. You can provide your dev db URL if needed, see [docs](https://atlasgo.io/integrations/kubernetes/operator#devurl)
