### ISSUE TITLE
How to create schema object in MSSQL database?

### ISSUE THREAD

**Issue by markphillips100** [ariga/atlas#2594]
I'm testing out sqlserver migrations using dotnet's Entity Framework Core generated (non-idempotent) scripts.  Aside from atlas having issues with the remaining IFs and GOs in the generated schema file - I assumed this would be the case and intend to transform the files without the EFCore additions - it seems I have an issue with a schema name preceding the table name.  The issue being that the schema does not yet exist of course.

An example table:
```
CREATE TABLE [MySchema].[Image] (
    [ImageId] uniqueidentifier NOT NULL,
    [ImageSource_FileName] nvarchar(64) NULL,
    CONSTRAINT [PK_Image] PRIMARY KEY ([ImageId])
);
```
...and the error:
```
The specified schema name "MySchema" either does not exist or you do not have permission to use it.
```

Schema objects in sqlserver (created using `CREATE SCHEMA <schema-name>`) must exist prior to applying table changes.  With EFCore migrations, the generated script would normally take care of that:
```
IF SCHEMA_ID(N'ITOps_Images') IS NULL EXEC(N'CREATE SCHEMA [MySchema];');
GO
```

I've tried leaving this in of course but didn't expect it to work.  Does atlas have a way of creating the required schema some how?  I'm not seeing anything jumping out at me in docs.

**Comment by giautm** [comment]
Hello @markphillips100, when you use the versioned migration flow, you have to handle the creation of schema inside your migration script. So, `IF SCHEMA_ID(N'ITOps_Images') IS NULL EXEC(N'CREATE SCHEMA [MySchema];');` is needed for your migration.

If you use the declarative flow, you can define the schema in Atlas's schema and Atlas will create the schema for you.

```hcl
schema "MySchema" {}

table "Image" {
    schema = schema.MySchema
    column "ImageId" {
        type = uniqueidentifier
        null = false
    }
    column "ImageSource_FileName" {
        type = nvarchar(64)
        null = true
    }
    primary_key {
        columns = ["ImageId"]
    }
}
```

**Comment by markphillips100** [comment]
I have no intention of using HCL though.  I was also hoping to use the declarative flow with pure sql.

**Comment by giautm** [comment]
> I have no intention of using HCL though. I was also hoping to use the declarative flow with pure sql.

You can define you schema in [SQL format](https://atlasgo.io/atlas-schema/sql) too. So just give atlas full schema of your migration.

**Comment by markphillips100** [comment]
Hmm okay.  I tried that earlier (and again just now) and the cli reports "Schema is synced, no changes to be made"

**Comment by giautm** [comment]
> Hmm okay. I tried that earlier (and again just now) and the cli reports "Schema is synced, no changes to be made"

And the resources were created?

**Comment by markphillips100** [comment]
Sorry. No.

**Comment by markphillips100** [comment]
If it were regular TSQL I was executing the CREATE SCHEMA would need to be followed by a GO statement as it must execute in its own batch.  I assume it might not be the case here (and cli doesn't like the GOs anyway).  Still, no schema and no table are created.

**Comment by giautm** [comment]
One sec, I'll try on my side and update you.

**Comment by giautm** [comment]
Hello @markphillips100 again, please don't forget to add `mode=database` in your connection string. Atlas need this query parameter to know which is the scope of connection.

```shell
atlas schema apply \
  --url "sqlserver://sa:P@ssw0rd0995@:1433?database=master&mode=database" \
  --to "file://schema.sql" \
  --dev-url "docker://sqlserver/2022-latest/dev?mode=database"
  ```
  
  
<img width="584" alt="Screenshot 2024-03-05 at 10 33 54" src="https://github.com/ariga/atlas/assets/12751435/cb2d78cc-d669-4b50-836e-a026ccb84879">

**Comment by markphillips100** [comment]
Oooh I see.  Can you point me at docs re `mode=database` please?

**Comment by markphillips100** [comment]
Also, just to confirm for me, when doing things declaratively, can the sql contain IFs and GOs or not?  It would be ideal if I didn't have to trim the efcore scripts of those parts of their generated script is all.

**Comment by giautm** [comment]
> Oooh I see. Can you point me at docs re `mode=database` please?

The SQL Server tab on this URL doc. https://atlasgo.io/concepts/url

**Comment by giautm** [comment]
> Also, just to confirm for me, when doing things declaratively, can the sql contain IFs and GOs or not? It would be ideal if I didn't have to trim the efcore scripts of those parts of their generated script is all.

You can, with a [custom delimiter](https://atlasgo.io/versioned/new#custom-statements-delimiter). You don't need it in almost of cases, but I find some case that you have to run it sepereted like create triggers or proceduces in your migration. So just set it one on the top of migration file

```sql
-- atlas:delimiter GO
CREATE SCHEMA [MySchema];
GO
CREATE TABLE [MySchema].[Image] (
    [ImageId] uniqueidentifier NOT NULL,
    [ImageSource_FileName] nvarchar(64) NULL,
    CONSTRAINT [PK_Image] PRIMARY KEY ([ImageId])
);
```

<img width="727" alt="Screenshot 2024-03-05 at 10 38 29" src="https://github.com/ariga/atlas/assets/12751435/e9477116-59e4-4ba7-8324-816568eeffa2">

**Comment by markphillips100** [comment]
Can confirm that `mode=database` worked perfectly.  Thank you very much.

I tried the `mode=database` and `GO` delimiter and the following managed to process an untouched efcore migration script which is good.  I don't care that the INSERT at the end didn't end up putting data in the target db (don't actually want it to).

This is good news :-)

Here's the script I tried:
```
-- atlas:delimiter GO
IF OBJECT_ID(N'[__EFMigrationsHistory]') IS NULL
BEGIN
    CREATE TABLE [__EFMigrationsHistory] (
        [MigrationId] nvarchar(150) NOT NULL,
        [ProductVersion] nvarchar(32) NOT NULL,
        CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY ([MigrationId])
    );
END;
GO

IF SCHEMA_ID(N'MySchema') IS NULL EXEC(N'CREATE SCHEMA [MySchema];');
GO

CREATE TABLE [MySchema].[Image] (
    [ImageId] uniqueidentifier NOT NULL,
    [ImageSource_FileName] nvarchar(64) NULL,
    CONSTRAINT [PK_Image] PRIMARY KEY ([ImageId])
);
GO

INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
VALUES (N'20240203051214_InitialCreate', N'8.0.2');
GO
```

**Comment by giautm** [comment]
Good news!, you're welcome. Please join [our community on Discord](https://discord.gg/zZ6sWVg6NT) for further question if you have, I'm the main maintainer of SQL Server driver. So, I would like to support its popular. :)

**Comment by markphillips100** [comment]
If I have more than one schema file (different efcore dbcontexts) and apply them using this approach, the 2nd file applied would result in the diff suggesting to remove the 1st file's schema.  I see 2 possibilities to remedy this:

1. Merge all schema files into one long script, or
2. Have one script to create the schema names only (`CREATE SCHEMA ...`) with use `mode-database`, and then for each schema apply their schema (without the create and using `mode=schema` and using the schema in the url).

Is there a preferred strategy here?

**Comment by markphillips100** [comment]
oops sorry, didn't see you closed the issue.  I don't actually use discord.

**Comment by giautm** [comment]
Hello @markphillips100, you can use `composite_schema` in `atlas.hcl` to merge schema from many files.

https://atlasgo.io/atlas-schema/projects#data-source-composite_schema

**Comment by markphillips100** [comment]
thanks, but like I mentioned earlier, I want to use non-hcl approach...and the operator ultimately (but still need the cli for PR diffs)

**Comment by giautm** [comment]
> thanks, but like I mentioned earlier, I want to use non-hcl approach...and the operator ultimately (but still need the cli for PR diffs)

Yes, `atlas.hcl` is the config file for project. Not database schema in HCL format, the `composite_schema` datasource support both SQL and HCL format of migration. :) Please read the doc.

**Comment by giautm** [comment]
You can read all content of efcore by use [`external_schema` datasource](https://atlasgo.io/atlas-schema/projects#data-source-external_schema) to invoke the command that print TSQL in terminal, then Atlas can read it directly. :)

**Comment by markphillips100** [comment]
Apologies for my hastiness.  I realised my error when I took a look at docs.  Seems like that's the solution, so once again thank you.  You've been very helpful.
