### ISSUE TITLE
migrate apply error when fk changed

### ISSUE THREAD

**Issue by idc77** [ariga/atlas#2598]
old schema:
```go
package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

// Image holds the schema definition for the Image entity.
type Image struct {
	ent.Schema
}

// Fields of the Image.
func (Image) Fields() []ent.Field {
	return []ent.Field{
		field.Int("id"),
		field.String("sub"),
		field.String("name"),
		field.String("alt"),
		field.String("path"),
	}
}

// Edges of the Image.
func (Image) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("recipe", Recipe.Type).Ref("image").Required().Unique(),
	}
}
```

new schema
```go
package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

// Image holds the schema definition for the Image entity.
type Image struct {
	ent.Schema
}

// Fields of the Image.
func (Image) Fields() []ent.Field {
	return []ent.Field{
		field.Int("id"),
		field.String("sub"),
		field.String("name"),
		field.String("alt"),
		field.String("path"),
		field.Int("recipe_id"),
	}
}

// Edges of the Image.
func (Image) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("recipe", Recipe.Type).Ref("image").Field("recipe_id").Required().Unique(),
	}
}
```

notice field recipe_id was added

I have added it because the jsonencode extension wouldn't render the "recipe_image" edge field, because it's not exported in the struct.

```
./migrate-apply 
Migrating to version 20240307023155 from 20240220144847 (1 migrations in total):

  -- migrating version 20240307023155
    -> ALTER TABLE `images` DROP INDEX `images_recipes_image`, DROP FOREIGN KEY `images_recipes_image`;
    -> ALTER TABLE `images` DROP COLUMN `recipe_image`, ADD COLUMN `recipe_id` bigint NOT NULL, ADD INDEX `images_recipes_image` (`recipe_id`), ADD CONSTRAINT `images_recipes_image` FOREIGN KEY (`recipe_id`) REFERENCES `recipes` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION;
    Error 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`rezeptx`.`#sql-3f0_21`, CONSTRAINT `images_recipes_image` FOREIGN KEY (`recipe_id`) REFERENCES `recipes` (`id`))

  -------------------------
  -- 150.826602ms
  -- 1 migration with errors
  -- 1 sql statement ok, 1 with errors
Error: sql/migrate: executing statement "ALTER TABLE `images` DROP COLUMN `recipe_image`, ADD COLUMN `recipe_id` bigint NOT NULL, ADD INDEX `images_recipes_image` (`recipe_id`), ADD CONSTRAINT `images_recipes_image` FOREIGN KEY (`recipe_id`) REFERENCES `recipes` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION;" from version "20240307023155": Error 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`rezeptx`.`#sql-3f0_21`, CONSTRAINT `images_recipes_image` FOREIGN KEY (`recipe_id`) REFERENCES `recipes` (`id`))
```

mysql --version
mysql  Ver 8.1.0-1 for Linux on x86_64 (Source distribution)

I can drop or truncate the database, but I'm afraid if I apply migrations on prod sometime later that I'll get stuck on the same error again.

Should I delete all migrations and start fresh with migration recording?

**Comment by masseelch** [comment]
Hey! This migration fails because of a data dependent change. You are adding a foreign key on data where that does not satisfy this constraint. 

In your case the image table seems to hold a row with an recipe id that does not exist. 

There are ways to fix this, e.g. by removing conflicting rows before applying the change. 

I suggest you have a look at the `atlas migrat lint` command.

**Comment by idc77** [comment]
Ok but this isn't fixed.
I know what's happening, but this can still happen again anytime a field is added to the foreign key edge.

Before there was just an edge that went from recipe to image O2M.

Now the image has a named field "recipe_id", so the table had its field changed from recipe_image to recipe_id.
But the migration tool is unable to create a proper migration.

This is a bug.

Atlas is supposed to be a tool that keeps watch and helps with migrations, tracks changes and creates the SQL so that you can apply all the migrations in sequence.
In this case it doesn't do the job, it fails to do the job, creates a non-working migration.

**Comment by giautm** [comment]
Hello @idc77, you can use the StorageKey annotation to keep the old column, so any migration engine (ent’s or atlas) won’t try to drop and re-create the column for that field. Please let me know if it helps.

**Comment by masseelch** [comment]
I just see now that it drops and re-creates the column, sorry missed that before. It's not really possible to determine if for a change made in the desired schema if it's a rename (like in your case) or a drop+add with equal types. 

This is one of the reasons why there is `atlas migrate lint`. It would have told you that dropping a column is dangerous and most likely not intentional. Also, you can edit a generated migration and change the drop+add to a column rename. Or just use the `StorageKey` option as @giautm mentioned to keep the database column name.

However, we are actively working on solutions for these type of problems :-)
