### ISSUE TITLE
CREATE SEQUENCE for MSSQL database fails

### ISSUE THREAD

**Issue by markphillips100** [ariga/atlas#2599]
One of my scripts has a `CREATE SEQUENCE` sql command and atlas seems to have a problem with it.  It's for a specific schema but so are the tables in script and they have no problem being created (so long as I comment out the sequence statement).

atlas cli v0.19.0
sqldb: docker linux container: mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04

You can replicate with this script using `mode=database`:
```
-- atlas:delimiter GO
CREATE SCHEMA [MySchema];
GO
CREATE SEQUENCE [MySchema].[MySequence] AS int START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE NO CYCLE;
GO
```

and the error you should see is:
**Error: Drop schema named "MySchema": mssql: Cannot drop schema 'MySchema' because it is being referenced by object 'MySequence'**.

**Comment by giautm** [comment]
Hello, the support for sequence will come soom in late next week. I'll update you when it out.

**Comment by markphillips100** [comment]
Thanks @giautm .  Living on the edge :-)
