### ISSUE TITLE
Atlas-operator helm chart doesn't support customization of labels

### ISSUE THREAD

**Issue by markphillips100** [ariga/atlas#2602]
I shall soon need to apply a label to the atlas-operator pod in order to support Azure Workload Identity.  Unfortunately the helm chart's [labels spec](https://github.com/ariga/atlas-operator/blob/fe97c2f8179333a632c264c44fb336fb8fb1b6ae/charts/atlas-operator/templates/deployment.yaml#L19) doesn't have support for custom labels supplied by values.

**Comment by rotemtam** [comment]
We will happily review a PR if you submit one . If you do please research what is the standard and common way to supply such configurations from values file and provide reference links

Let me know if you need any help with this

**Comment by giautm** [comment]
Close with https://github.com/ariga/atlas-operator/pull/154
