### ISSUE TITLE
[Bug] Incorrect command argument in `Introduction to Atlas Migrations` documentation

### ISSUE THREAD

**Issue by Pante** [ariga/atlas#2610]
I'm currently experiencing an issue when following the versioned migration guide, https://atlasgo.io/versioned/intro#creating-the-first-migration on `v0.19.3-2d83466-canary`, Windows.

Running the command stated in the docs:
```
atlas migrate diff initial --to file://schema.sql --dev-url "docker://postgres/15/dev?search_path=public" --format '{{ sql . "  " }}
```

Yields:
```
Error: accepts at most 1 arg(s), received 2
```

After further digging, it seems like `--format '{{ sql . "  " }}` is causing the issue. Removing `"  "` seems to solve the issue but I don't think has the same indentation. On another note, the error message is extremely vague and took me awhile to figure out what was the exact issue. Perhaps it could be tweaked?

**Comment by masseelch** [comment]
I think quoting in windows works different from unix systems. If I remember correctly in windows `^` is the escape char. Can you try: 

`--format '{{ sql . ^"  ^" }}` instead?
