### ISSUE TITLE
New version of atlas operator required built with atlas v0.20.0 or above?

### ISSUE THREAD

**Issue by markphillips100** [ariga/atlas#2662]
I require the functionality available via atlas v0.20.0 please, namely the sqlserver "out of beta" and the support for Azure AD authentication.

Is there a reason the atlas operator release is out of step with atlas itself?

**Comment by markphillips100** [comment]
Thank you @rotemtam .  Much appreciated.

**Comment by giautm** [comment]
We have a nightly build version of the atlas-operator for the latest feature daily. So you can change the image tag if needed.

https://hub.docker.com/r/arigaio/atlas-operator/tags

P/s: on the process for tag new operator version.
