### ISSUE TITLE
Atlas thinks tables that exist need to be created for postgres

### ISSUE THREAD

**Issue by jaym** [ariga/atlas#2677]
We have an issue where Atlas does not correctly see that some tables exists.
This seems to manifest when we upgrade the version of Postgres. For context,
we use Postgres from Google Cloud SQL. This happens consistently across versions;
we've tried upgrades from 11 to 13 and 13 to 15. I think I've narrowed down the problem
to `oid`s that conflict across different classes. From my understanding, `oid`s are not globally
unique.

Atlas seems to use this query to find the existing database objects it should know about:
```sql
SELECT
    t3.oid,
    t1.table_schema,
    t1.table_name,
    pg_catalog.obj_description(t3.oid, 'pg_class') AS comment,
    t4.partattrs AS partition_attrs,
    t4.partstrat AS partition_strategy,
    pg_get_expr(t4.partexprs, t4.partrelid) AS partition_exprs
FROM
    INFORMATION_SCHEMA.TABLES AS t1
    JOIN pg_catalog.pg_namespace AS t2 ON t2.nspname = t1.table_schema
    JOIN pg_catalog.pg_class AS t3 ON t3.relnamespace = t2.oid AND t3.relname = t1.table_name
    LEFT JOIN pg_catalog.pg_partitioned_table AS t4 ON t4.partrelid = t3.oid
    LEFT JOIN pg_depend AS t5 ON t5.objid = t3.oid AND t5.deptype = 'e'
WHERE
    t1.table_type = 'BASE TABLE'
    AND NOT COALESCE(t3.relispartition, false)
    AND t1.table_schema IN ('nexus')
        AND t5.objid IS NULL;
```

However, a bunch of existing tables are being filtered out. We can see this if we
change the condition on `t5.objid` to `IS NOT NULL`:

```sql
SELECT
    t3.oid,
    t1.table_schema,
    t1.table_name,
    pg_catalog.obj_description(t3.oid, 'pg_class') AS comment,
    t4.partattrs AS partition_attrs,
    t4.partstrat AS partition_strategy,
    pg_get_expr(t4.partexprs, t4.partrelid) AS partition_exprs
FROM
    INFORMATION_SCHEMA.TABLES AS t1
    JOIN pg_catalog.pg_namespace AS t2 ON t2.nspname = t1.table_schema
    JOIN pg_catalog.pg_class AS t3 ON t3.relnamespace = t2.oid AND t3.relname = t1.table_name
    LEFT JOIN pg_catalog.pg_partitioned_table AS t4 ON t4.partrelid = t3.oid
    LEFT JOIN pg_depend AS t5 ON t5.objid = t3.oid AND t5.deptype = 'e'
WHERE
    t1.table_type = 'BASE TABLE'
    AND NOT COALESCE(t3.relispartition, false)
    AND t1.table_schema IN ('nexus')
        AND t5.objid IS NOT NULL;
```

```
  oid  | table_schema |    table_name     | comment | partition_attrs | partition_strategy | partition_exprs
-------+--------------+-------------------+---------+-----------------+--------------------+-----------------
 16610 | nexus        | axxxxxxxxxxxxxxx  |         |                 |                    |
 16622 | nexus        | axxxxx            |         |                 |                    |
 16646 | nexus        | ixxxxxxxxxxxxx    |         |                 |                    |
 16658 | nexus        | ixxxxxxxxxxx      |         |                 |                    |
 16670 | nexus        | ixxxxxxxxxx       |         |                 |                    |
 16683 | nexus        | oxxxxxxxxxxxx     |         |                 |                    |
 16570 | nexus        | schema_migrations |         |                 |                    |
 16757 | nexus        | uxxxx             |         |                 |                    |
 16580 | nexus        | sxxxxxxxxxxxxxxx  |         |                 |                    |
 16743 | nexus        | sxxxxx            |         |                 |                    |
```

So in this case, as an example, atlas thinks the `schema_migrations` table does not exist. But it does:

```
mondoo=> \d nexus.schema_migrations
          Table "nexus.schema_migrations"
 Column  |  Type   | Collation | Nullable | Default
---------+---------+-----------+----------+---------
 version | bigint  |           | not null |
 dirty   | boolean |           | not null |
Indexes:
    "schema_migrations_pkey" PRIMARY KEY, btree (version)
```

Further digging into things, this is what `pg_depend` looks like for that table:
```sql
select * from pg_depend where objid = '16580';
```

```
 classid | objid | objsubid | refclassid | refobjid | refobjsubid | deptype
---------+-------+----------+------------+----------+-------------+---------
    1255 | 16580 |        0 |       2615 |    16445 |           0 | n
    1255 | 16580 |        0 |       3079 |    16449 |           0 | e
    1259 | 16580 |        0 |       2615 |    16444 |           0 | n
```

This shows that there are repeated `objid` values, but they have a different class:

```sql
select oid, relname, relnamespace,reltype from pg_class where oid in (1255, 1259);
```

```
 oid  | relname  | relnamespace | reltype
------+----------+--------------+---------
 1255 | pg_proc  |           11 |      81
 1259 | pg_class |           11 |      83
 ```

 We can confirm that there is an object matching that oid in pg_proc as well:
 ```sql
 select oid,proname,probin from pg_proc where oid = 16580;
 ```

 ```
   oid  |     proname     |     probin
-------+-----------------+-----------------
 16580 | word_similarity | $libdir/pg_trgm
 ```

 For the original query, I think it only makes sense to do the JOIN between `pg_class` and `pg_depend` if the
 `classid` in `pg_depend` says its a class. Otherwise, you can end up considering the wrong object like in this
 case, where a table and a proc have the same oid.

**Comment by a8m** [comment]
Hey, @jaym. Thanks for the detailed report. However, to reproduce this, I need the command you used, an example schema, and the database version/flavour.

If this is something that can be reproduced locally, that’s preferred, of course. If not, the inspection output together with the migration/schema file(s) can also help - you can send me that privately in our Discord.

**Comment by jaym** [comment]
I don't currently have a local reproduction of this and I do not believe this is related to our schema. In fact, we have different databases with the same schema that will fail to detect different tables.

I think I can perhaps come up with a script that could force oids to wrap around in a way that is problematic. From the postgres 7.2 docs:
> OIDs are 32-bit quantities and are assigned from a single cluster-wide counter. In a large or long-lived database, it is possible for the counter to wrap around. Hence, it is bad practice to assume that OIDs are unique, unless you take steps to ensure that they are unique.

Future versions of the docs do not mention a single cluster-wide counter, though just playing around with things it feels like it may still do this.

So if I can create some tables, then eat up enough oids to force a wrap around, and then start installing extensions, we'd probably see this clash. Ill try to find some time to work on such a script, assuming its possible. Otherwise, continually installing and removing an extension could also do it, it would just take forever

**Comment by a8m** [comment]
OK, I think we can simply add the condition for `classid` and you can retest it. I will let you know when it’s ready
