### ISSUE TITLE
Domain types are not recognized properly.

### ISSUE THREAD

**Issue by ibrhmkoz** [ariga/atlas#2679]
```
CREATE SCHEMA IF NOT EXISTS "public";

CREATE DOMAIN EMAIL AS VARCHAR(255)
    CHECK (
        VALUE ~ '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z]{2,}$'
        );

CREATE TABLE clinics
(
    id    TEXT PRIMARY KEY,
    name  TEXT NOT NULL,
    email EMAIL
);

CREATE TABLE doctors
(
    id        TEXT PRIMARY KEY,
    clinic_id TEXT NOT NULL,
    CONSTRAINT fk_clinic
        FOREIGN KEY (clinic_id)
            REFERENCES clinics (id)
);
```

If I spin up my database with the schema above, I get the warning below:

`pgtest_test.go:15: Error: create "clinics" table: pq: type "email" does not exist`

**Comment by rotemtam** [comment]
Hey @ibrhmkoz 

domains are available to logged in users, can you verify that you are logged in when you try this?

**Comment by ibrhmkoz** [comment]
It is resolved. Is this documented somewhere? It's pretty fundamental, someone using it for the first time can surmise this as a bug.
