### ISSUE TITLE
Problem with LowCardinality(Nullable(String)) in clickhouse

### ISSUE THREAD

**Issue by ToGoBananas** [ariga/atlas#2688]
![image](https://github.com/ariga/atlas/assets/5418148/9069546f-b235-4d4c-a146-0ac26d2407cf)

Applying schema to table with LowCardinality(Nullable())

resulting in `Error: clickhouse: failed converting to *schema.Realm: cannot convert table "country_cdc": clickhouse: "type" attribute of column "after.alpha2" should be wrapped with "Nullable()"`

**Comment by datdao** [comment]
Hi @ToGoBananas. It seems like your datatype doesn't need the `null` attribute. If you specified it, you should change your datatype to `Nullable(LowCardinality(Nullable(String)))` but it is not a valid type for ClickHouse

**Comment by datdao** [comment]
Besides of that, we'll review again about the `nullable` message, as some users have encountered similar confusion. Thank you for bringing this to our attention
