### ISSUE TITLE
Atlas CLI inspect -w arrow keys not working for selecting

### ISSUE THREAD

**Issue by PFJoey** [ariga/atlas#2716]
Currently using the latest windows binaries it is not possible to change between atlas public domain and private organization domain when performing the following command:

atlas schema inspect -u 'file://schema.hcl' -w

The selector shows up, however, arrow keys do not work so it is impossible to change to the non-public version.

**Comment by giautm** [comment]
On Windows and Power-Shell, please use `j` to navigate down, and `k` to navigate up.

Closing this issue here, we may come back in the future with help message on the UI;

**Comment by mehdic213** [comment]
This should be documented somwhere. It wasn't clear.
