### ISSUE TITLE
Migrate Diff error using Postgis on latest release

### ISSUE THREAD

**Issue by saurori** [ariga/atlas#2718]
Hi - I noticed the latest atlas release breaks compatibility with postgis geometry types.

I upgraded to the latest `atlas` release:
```
atlas version
atlas version v0.21.2-b951fe0-canary
https://github.com/ariga/atlas/releases/latest
```
I can no longer run `migrate diff` using the `postgis` image with `geometry` types:
```
atlas migrate diff locations_timestamps \
                --dir "file://ent/migrate/migrations" \
                --to "ent://ent/schema" \
                --dev-url "docker://postgis/postgis/15-3.4/app?search_path=public"
```
Returns error: `Error: create "locations" table: pq: type "geometry" does not exist`

If I downgrade `atlas` to `v0.21.1`, everything works as expected:
```
export ATLAS_VERSION=v0.21.1 && curl -sSf https://atlasgo.sh | sh
Install 'atlas-darwin-arm64-v0.21.1' to '/usr/local/bin/atlas'? [y/N] y
Downloading https://release.ariga.io/atlas/atlas-darwin-arm64-v0.21.1
######################################################################## 100.0%
atlas version v0.21.1
https://github.com/ariga/atlas/releases/tag/v0.21.1
Installation successful!
```

Could this PR be related? https://github.com/ariga/atlas/pull/2704

**Comment by a8m** [comment]
Hey @saurori 👋🏻 

Sorry for the inconvenience, but this is actually a bug that was fixed. According to Postgis (Docker image) doc:
> This image ensures that the default database created by the parent postgres image will have the following extensions installed: … 

That means, if you are not using the default database (in your case, app), you need to let Atlas managing these extensions. Otherwise, use the default database.

**Comment by saurori** [comment]
@a8m Ah ok that makes sense. Thanks for the quick reply.

For anyone landing here: The default DB is `postgres` so using `--dev-url "docker://postgis/postgis/15-3.4/postgres?search_path=public"` fixes the issue (or let Atlas manage extensions if you need to use a different DB name).
