### ISSUE TITLE
Feature Request: Podman Support for Dev Database

### ISSUE THREAD

**Issue by CodeMan99** [ariga/atlas#2726]
My software team just decided against using Atlas. The biggest hang up by far is that [dev-url](https://atlasgo.io/concepts/dev-database) does not support executing via `podman`.

Current Version: `atlas version v0.21.2-1fb7588-canary`
Development OS: Windows 10
CI/CD OS: Ubuntu
Production OS: RHEL 9

**Comment by a8m** [comment]
Hey @CodeMan99 👋🏻 

Thanks for the feature suggestion. However,  there is nothing to support here as the two CLIs are compatible. See: https://podman-desktop.io/blog/5-things-to-know-for-a-docker-user#cli-compatibility

Closing, but please feel free to join our Discord in case you need more help .
