### ISSUE TITLE
Highlight destructive actions when listing planned changes

### ISSUE THREAD

**Issue by forsstromerik** [ariga/atlas#2729]
I accidentally dropped a table when running `atlas schema apply` from an outdated branch. The output listed all the changes but the "drop table" change was a little bit hidden among the other listed changes. Suggestions to help mitigate this:

* Separate destructive actions into its own section in the listed output
* List the output as it is today but highlight destructive actions in red

**Comment by rotemtam** [comment]
Hi @forsstromerik 

Functionality similar to what you described is available via [Interactive Declarative Migrations](https://atlasgo.io/blog/2023/10/19/atlas-v-0-15#interactive-declarative-migrations)

**Comment by a8m** [comment]
Migration linting was added to the declarative workflow on v0.27.
