### ISSUE TITLE
Are function and triggers not supported?

### ISSUE THREAD

**Issue by ewan-escience** [ariga/atlas#2743]
In the [documentation on inspect](https://atlasgo.io/declarative/inspect), it says

> By default, running atlas schema inspect inspects only schemas, tables, and their associated indexes and constraints such as foreign keys and checks.

> Views, materialized views, functions, procedures, triggers, sequences, domains, extensions, and additional features are available to logged-in users only.

Is this also the case for `atlas schema diff`? If so, that would be a deal breaker for us, but can that same warning at least be added to [here](https://atlasgo.io/declarative/diff)?

**Comment by a8m** [comment]
Hey, @ewan-escience. That’s true for all commands. 

In order to enable automation such as inspection and diffing for these objects you need to have a cloud account.
