### ISSUE TITLE
Preventing Unwanted Line Addition in Generated SQL File

### ISSUE THREAD

**Issue by user0608** [ariga/atlas#2752]
When I run the atlas schema inspect command to generate the 01-schema.sql file, the following line is appended to the end of the file:

```bash
A new version of Atlas is available (v0.22.0): https://github.com/ariga/atlas/releases/tag/v0.22.0
```
![image](https://github.com/ariga/atlas/assets/37247825/d5b09c88-5347-4aef-a4e2-3ff2232133af)

How can I prevent this from happening?

This is the script I'm using:
```bash
atlas schema inspect \
	-u "${atlasdsn_postgres}" \
	--format '{{ sql . "  "}}' > ./sql-scripts/01-schema.sql

```
Any suggestions on how to fix this issue?

Thank you!

**Comment by a8m** [comment]
Hey, you can set the `ATLAS_NO_UPDATE_NOTIFIER` environment variable to `true` to disable update notifications. Or, update Atlas to the latest version ofc :D
