### ISSUE TITLE
Failed creating migration diff from docker image

### ISSUE THREAD

**Issue by dv-petrov** [ariga/atlas#2753]
```
# docker run --rm arigaio/atlas:latest migrate diff create_database --dir "file://migrations" --to "file://schema.sql" --dev-url 
 "docker://postgres/15/dev?search_path=public"

Error: exec: "docker": executable file not found in $PATH
```

For example, schema inspect seems to works correctly.

**Comment by rotemtam** [comment]
The docker:// which you used for your dev database relies on the docker executable which isn't available from within the docker image in which you run atlas.

**Comment by noamcattan** [comment]
One option is to setup another docker container as dev database, like:
```bash
docker run -d --rm --name pg -e "POSTGRES_PASSWORD=pass" -e "POSTGRES_DB=dev" -p "5432:5432" postgres:15
```

And then run the atlas image with network=host:
```bash
docker run --rm --network=host arigaio/atlas:latest schema migrate diff ... --dev-url "postgres://postgres:pass@127.0.0.1/dev?sslmode=disable"
```

**Comment by a8m** [comment]
Another option is to build a custom Docker image with docker installed there and mount the docker.sock. 

Closing, but please join our Discord in case you need more help with this.

**Comment by rotemtam** [comment]
For future readers, here are docs for running Atlas in Docker: 
https://atlasgo.io/guides/atlas-in-docker
