### ISSUE TITLE
Migrate diff always generates SET DEFAULT (gen_random_uuid())

### ISSUE THREAD

**Issue by Hiroki6** [ariga/atlas#2759]
When I generates a migration script on Postgres, it always generates `SET DEFAULT (gen_random_uuid())` even though the column has this default value.
```
ALTER TABLE "groups" ALTER COLUMN "id" SET DEFAULT (gen_random_uuid());
```

As far as I understand, it's compared by using `SELECT %s = %s` .
https://github.com/ariga/atlas/blob/master/sql/postgres/diff.go#L409
```go
	// The DEFAULT expressions are safe to be inlined in the SELECT
	// statement same as we inline them in the CREATE TABLE statement.
	rows, err := d.QueryContext(context.Background(), fmt.Sprintf("SELECT %s = %s", d1, d2))
	if err != nil {
		return false, err
	}
	if err := sqlx.ScanOne(rows, &b); err != nil {
		return false, err
	}
```

In Postgres, it returns `false`.
```
SELECT (gen_random_uuid()) = (gen_random_uuid());
```

However, other default values such as `now()` returns `true`. Therefore, it doesn't generate `SET DEFAULT now()`
```
SELECT (now()) = (now());
```

Since I use `migrate.NamedDiff` function for the generation in Golang, I can implement a hook not to generates this statement.
But, are there any other workarounds for this?

**Comment by a8m** [comment]
Hey @Hiroki6 👋 

How do you generate the migrations and how's the column is defined?

**Comment by a8m** [comment]
> But, are there any other workarounds for this?

Yes, if the two definitions are identical, the check will be skipped. Read more about it here: https://atlasgo.io/concepts/dev-database#diffing

**Comment by Hiroki6** [comment]
I define my schema with ent.
```go
func (Group) Fields() []ent.Field {
	field.UUID("id", uuid.UUID{}).
			Default(uuid.New).
			Immutable().
                        Annotations(
			entsql.DefaultExprs(map[string]string{
				dialect.Postgres: "gen_random_uuid()",
				dialect.SQLite:   "uuid()",
			}),
		),
        }
}
```

and generates the migration like this below
```go
dir, err := atlasMigrate.NewLocalDir("ent/migrate/migrations")
opts := []schema.MigrateOption{
			schema.WithDir(dir),
			schema.WithMigrationMode(schema.ModeInspect),
			schema.WithDialect(dialect.Postgres),
			schema.WithFormatter(atlasMigrate.DefaultFormatter),
			schema.WithDropColumn(true),
}
err = migrate.NamedDiff(ctx, cfg.PostgresConnectionString, migrationName, opts...)
```

**Comment by Hiroki6** [comment]
> > But, are there any other workarounds for this?
> 
> Yes, if the two definitions are identical, the check will be skipped. Read more about it here: https://atlasgo.io/concepts/dev-database#diffing

@a8m 
so, since atlas doesn't think that `gen_random_uuid()` is identical because `SELECT (gen_random_uuid()) = (gen_random_uuid())` returns false, I can't skip the check.

**Comment by a8m** [comment]
You should use `atlas migrate diff` instead, or skip the dev-database by keeping the two definitions identical. i.e., wrap your default value with parens: `(gen_random_uuid())`.

**Comment by Hiroki6** [comment]
@a8m 
I see. I will try that. Thank you so much for your quick response!
