### ISSUE TITLE
DSNs containing a protocol or parentheses in the host aren't parsed correctly

### ISSUE THREAD

**Issue by xaverhimmelsbach** [ariga/atlas#2760]
I use the following command to connect to a database running in a container on my system:

```
atlas migrate apply --dir file://db/migration --url mysql://dev:dev@tcp\(db:3306\)/mydb
```
This fails with
```
Error: sql/sqlclient: parse open url: invalid port ":3306)" after host
```

This seems to be the same issue as in https://github.com/golang-migrate/migrate/issues/264 from golang-migrate.
Using net/url to parse a DSN doesn't work, if the DSN contains non-standard formatting like the tcp(...) part.

This can be fixed by parsing the DSN manually (e.g. https://github.com/ory/x/pull/119/files).

I'd be up to fix it, but it'll probably be some time before I can start on that.

**Comment by rotemtam** [comment]
Atlas uses standard URLs without the tcp() thing.

See https://atlasgo.io/concepts/url

**Comment by xaverhimmelsbach** [comment]
Oof, thank you. Removing the tcp makes it run without problems.
