### ISSUE TITLE
Support for DESC NULLS LAST Postgres indexes

### ISSUE THREAD

**Issue by net** [ariga/atlas#2762]
1. Inspecting a database with a DESC NULLS LAST index does not specify that index as NULLS LAST in the output HCL.
   i. As a result, Atlas will generate an incorrect diff, dropping and recreating the index as DESC NULLS FIRST.
3. I'm unable to find any way to specify indexes as DESC NULLS LAST in HCL.

```sql
CREATE TABLE users (id SERIAL PRIMARY KEY, name TEXT NOT NULL);
CREATE INDEX idx_name_desc_nulls_last ON users (name DESC NULLS LAST);
```

```hcl
table "users" {
  schema = schema.public
  column "id" {
    null = false
    type = serial
  }
  column "name" {
    null = false
    type = text
  }
  primary_key {
    columns = [column.id]
  }
  index "idx_name_desc_nulls_last" {
    on {
      desc   = true
      column = column.name
      # <-- nothing specifying this index as NULLS LAST
    }
  }
}
schema "public" {
  comment = "standard public schema"
}
```

**Comment by a8m** [comment]
Closed with https://github.com/ariga/atlas/issues/2763. A new version will be released soon.
