### ISSUE TITLE
Create citext type column

### ISSUE THREAD

**Issue by enrique-fernandez-polo** [ariga/atlas#2769]
Hello there!

I am trying to create a table with a `citext` column 

```hcl
schema "public" {}

extension "citext" {
  schema  = schema.public
}

table "accounts" {
  schema = schema.public
  column "email" {
    type = citext
  }
}
```

I am getting the following error

`Unknown column.type; There is no type named "citext". Did you mean "text"?`

I've tried this without success

```hcl
table "accounts" {
  schema = schema.public
  column "email" {
    type = extension.citext
  }
}
```

Any advice? Thanks in advance!

**Comment by a8m** [comment]
Hey! Non-standard and user-defined types can be defined using the `sql` expression as follows: `sql("citext")`.

**Comment by enrique-fernandez-polo** [comment]
Thank you for your fast response! I am still having the same issue 🥲

```hcl
column "email" {
  type = sql("citext")
}
```

I am trying other types too but I am having the same issue

```hcl
type = sql("xid8")
```

**Comment by enrique-fernandez-polo** [comment]
Cool!! I had to update the CLI too. I guess this is one of the latest features.

Thanks!
