### ISSUE TITLE
Clickhouse migrations failing for atlas 0.22

### ISSUE THREAD

**Issue by ToGoBananas** [ariga/atlas#2786]
schema.sql fle:
```
CREATE TABLE country_cdc
(
    `after.id` UInt64,
    `after.name` LowCardinality(Nullable(String)),
    `after.alpha2` LowCardinality(Nullable(String)),
    `after.alpha3` LowCardinality(Nullable(String)),
    `op` LowCardinality(String),
    `ts_ms` UInt64,
    `source.sequence` String,
    `source.lsn` UInt64
)
ENGINE = MergeTree ORDER BY (`after.id`);
```

Command
`atlas migrate diff initial --dir "file://migrations/clickhouse/versions" --to  "file://migrations/clickhouse/schema.sql" --dev-url "clickhouse://username:password@localhost:9000/core" --format '{{ sql . "  " }}'`

Resulting in error
```Error: clickhouse: failed to extract primary key for table "country_cdc": column "`after.id`" was not found in table "country_cdc"
clickhouse: failed to extract primary key for table "country_cdc": column "`after.id`" was not found in table "country_cdc"```

ClickHouse version 24.4.1.2088 (official build)
atlas version v0.22.1-51ccdb0-canary

0.21 versions works fine

**Comment by datdao** [comment]
Hi @ToGoBananas, We have fixed the problem. Please upgrade Atlas to see the change. Thanks for reporting 👍
