### ISSUE TITLE
unknown driver "sqlserver"

### ISSUE THREAD

**Issue by kshpytsya** [ariga/atlas#2798]
As stated [here](https://github.com/ariga/atlas#supported-databases)

> ...SQL Server...

and [here](https://atlasgo.io/url)

> Connecting to a default schema of current user:
> sqlserver://sa:P@ssw0rd0995@localhost:1433?database=master&mode=schema
> Connecting to a local SQLServer database named master (all schemas). The user need to have db_owner role:
> sqlserver://sa:P@ssw0rd0995@localhost:1433?database=master&mode=database

and even having a dedicated page [here](https://atlasgo.io/guides/mssql) (to be frank, "To use SQL Server with Atlas, you'll need to log in to Atlas." should raise a suspicion) one may assume that SQL Server is supported. However, doing 

(per [building from source](https://atlasgo.io/community-edition#building-from-source))

```sh
$ go version
go version go1.22.3 linux/amd64
$ go get ariga.io/atlas/cmd/atlas
go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
```

to fix things:

```sh
$ go install ariga.io/atlas/cmd/atlas@latest
$ atlas version
atlas version - development
https://github.com/ariga/atlas/releases/latest
```

(one should be left guessing the version. Currently master is at [479d552](https://github.com/ariga/atlas/commit/479d552031eeaba097727b1de69045f3cd2b5cb1)

Now, try exact url from [here](https://atlasgo.io/concepts/url)

```sh
$ atlas schema inspect --url 'sqlserver://sa:P@ssw0rd0995@localhost:1433?database=master&mode=schema'
Error: sql/sqlclient: unknown driver "sqlserver". See: https://atlasgo.io/url
```

There is [this](https://github.com/ariga/atlas/issues/1343) open issue with last activity more than 10 month ago.

When in November 2023  I have inquired in Atlas Support chat "Are there any ETA for MSSQL support going out of beta", I got a reply from @rotemtam inviting me to go the Atlas Cloud way, which in my case is unacceptable for multiple reasons.

It looks like it is a business decision of providing SQL Server only on commercial basis. This is a perfectly valid approach but it would be great if it was more prominently and straightforwardly stated.

**Comment by rotemtam** [comment]
Hi @kshpytsya 

Thanks for reaching out.

The SQL Server driver is only available to logged in users, as you've correctly mentioned.

This is documented in many places, among them:

https://atlasgo.io/features#database-support

https://atlasgo.io/guides/mssql#logging-in-to-atlas

And many more.

The SQL Server driver is available on the free plan of Atlas, so it should be accessible for most cases. However, if you operate in circumstances that prohibit using it (such as an air-gapped or highly regulated environment) please don't hesitate to reach out to me personally so we can see how we can help you out.

Best regards

**Comment by kshpytsya** [comment]
Hi @rotemtam 

For multiple reasons which are really not mine to discuss and argue, for solving my task I am confined to the realm of purely open-source software with non-restrictive licenses.

All I can say is that I am in process of refactoring of some non-customer facing application where database schema changes once in a blue moon (and not because it is inconvenient to do so). The application is written in Python and originally would use its dbapi with raw SQL for all database interactions (both data and schema related). Any schema changes where made on the fly in reaction to a "column not found" exception. No matter how atrocious this sounds, this approach served the purpose and didn't cause any major issues other then hurting the eyes of anyone reading the code. Now I have switched the data part of database interaction to [SQLAlchemy](https://www.sqlalchemy.org/). All the schema management provided by SQLAlchemy itself boils down to "create all missing tables" operation which doesn't modify schema of existing tables. The recommended approach of dealing with anything more complex is the [alembic](https://alembic.sqlalchemy.org/) sister project. It is live, mature and well documented, however puts extra load on both developers and devops. [Here](https://github.com/sqlalchemy/alembic/discussions/1214) is a discussion with alembic's authors explaining one of the problems I have with it.  And [this](https://github.com/sqlalchemy/alembic/discussions/1214#discussioncomment-5593494) summarizes the kind of usability I would like to achieve with the schema management solution I am to adopt.

I really hoped that I could use Atlas' declarative approach, possibly with Atlas Kubernetes Operator to deal with the task in nearly fire-and-forget way.

Thank you for you attention.

**Comment by rotemtam** [comment]
Thank you for considering Atlas. Closing.
