### ISSUE TITLE
`pq: syntax error at or near "NULLS"` (`NULLS NOT DISTINCT` in the wrong place)

### ISSUE THREAD

**Issue by hectorj-thetreep** [ariga/atlas#2818]
Hi!

`atlas schema apply` generates invalid postgres code when dealing with a `CONSTRAINT xxx UNIQUE NULLS NOT DISTINCT`.

It worked with v0.21.1 but hasn't worked since, even with latest v0.23.0.

The query in my schema file looks like this :

```
create table my_table (
    my_column text
   constraint my_table_constraint UNIQUE NULLS NOT DISTINCT (my_column)
);
```

but the query Atlas tries to apply uses `CONSTRAINT "my_table_constraint" UNIQUE ("my_column") NULLS NOT DISTINCT`

`NULLS NOT DISTINCT` should not be moved after the column list

**Comment by bene** [comment]
Experiencing the same issue

**Comment by a8m** [comment]
> Experiencing the same issue

Hey @bene, what versions are you using?

**Comment by bene** [comment]
I'm using currently `v0.25.1-2985991-canary`

**Comment by a8m** [comment]
Thanks. I'll check this and update

**Comment by a8m** [comment]
Issue was resolved and should be fixed in the latest version.

**Comment by bene** [comment]
Awesome, thanks for the quick response! 🙌
