### ISSUE TITLE
Clickhouse integration fails with unhelpful error

### ISSUE THREAD

**Issue by Nintorac** [ariga/atlas#2826]
Hey, I cant seem to get click house working, I have setup a clickhouse managed db and configured my .env with appropriate vars

My `atlas.hcl` looks like this

```hcl
// Define an environment named "local"
env "local" {
  // Declare where the schema definition resides.
  // Also supported: ["file://multi.hcl", "file://schema.hcl"].
  src = "file://${getenv("PROJECT_NAME")}/schema.hcl"

  // Define the URL of the database which is managed
  // in this environment.
  url = "clickhouse://${getenv("CLICKHOUSE_USER")}:${getenv("CLICKHOUSE_PASSWORD")}@${getenv("CLICKHOUSE_HOST")}:${getenv("CLICKHOUSE_PORT")}/default"

}
```

Then I get the following error when trying to interact with the server

```zsh
λ  atlas schema inspect --env local
Error: clickhouse: query server property: read: EOF
```

I haven't been able to find anything on bumping the verbosity level of atlas. Any ideas what I might be missing or ways to increase verbosity?

Thanks!

**Comment by datdao** [comment]
Hi @Nintorac, let try with this url format ```clickhouse://user:pass@CLICKHOUSE-CLOUD-HOST:9440/schema?secure=true``` if you are using Clickhouse managed DB

**Comment by Nintorac** [comment]
Thanks for getting back to me!

Yup, that works :) specifically using port 9440 (rather than 8443) and the `secure=true` flag

When using the https port I got the following error
```zsh
λ  atlas schema inspect --env local
Error: clickhouse: query server property: [handshake] unexpected packet [72] from server
```

So it could help to add some error handling/hints around
- incorrect protocol (i.e not using the native protocol) 
- bad SSL (i.e not setting the secure flag)

Had a quick look to see if I could understand how to do this but my Go is weak :|

**Comment by datdao** [comment]
Hi @Nintorac, it's true about the error messages being quite unclear. We will improve those messages in the next version. Thanks for reporting this ❤️
