### ISSUE TITLE
Feature Request: Support for Kafka Engine Type for ClickHouse

### ISSUE THREAD

**Issue by c0x65o** [ariga/atlas#2828]
I'm currently using AtlasGo to manage my database schemas, and I am looking to integrate it with ClickHouse's Kafka engine type. I have encountered an issue where defining a table with the Kafka engine type in the HCL schema results in an error stating, "Unknown table.engine; There is no engine named 'Kafka'."

I am assuming this is not currently supported, but maybe there is a workaround?

If not, want to add to the feature request list.

**Comment by datdao** [comment]
Hi @c0x65o, you can use `sql("Kafka(...)")` instead
