### ISSUE TITLE
SQL Server driver generating invalid SQL for down migration pre-checks

### ISSUE THREAD

**Issue by paul-komarnytskyy** [ariga/atlas#2845]
It seems that the driver for SQL Server is generating wrong SQL for down migration pre-checks.

If I try to migrate down from a migration that created a table or column in a table, the pre-check has invalid SQL and the whole thing fails:
`mssql: Incorrect syntax near the keyword 'AS'.`
![image](https://github.com/ariga/atlas/assets/16213846/cf3bb519-8d1f-4018-8dd6-7b88a9d893c1)
![image](https://github.com/ariga/atlas/assets/16213846/9c283a66-72ff-4581-b2ec-02ebc34e267b)

atlas version v0.23.1-4bd85b6-canary
SQL Server 16.0.1115.1 server
dev = "docker://sqlserver/2022-latest/dev?mode=database"

**Comment by a8m** [comment]
Thanks for reporting this. I've sent a patch to fix this, and a new version is now available for use.

Please, let me know if you encounter any more issues with it. Thanks
