### ISSUE TITLE
Dynamic Table Names / Schema Names not Supported

### ISSUE THREAD

**Issue by akmani-w** [ariga/atlas#2853]
Dynamic Table Names / Schema Names not Supported . Lets say I have a template variable for table name and if a different name is passed after first migration the migration does not run in case of same database

**Comment by akmani-w** [comment]
@datdao

**Comment by a8m** [comment]
Hey @akmani-w,

Please, see: https://atlasgo.io/atlas-schema/input-variables on how to inject custom names to schemas, and https://atlasgo.io/guides/migration-dirs/template-directory for customizing any migration directory with templates.

Note, input variables cannot be injected to set the table name. 

Closing, but feel free to join our Discord server in case you need more help with it.
