### ISSUE TITLE
<atlas schema inspect>Issue when password has an at sign

### ISSUE THREAD

**Issue by jllanes-ss** [ariga/atlas#2857]
Hi Atlas Team

Feature: Inspecting database using connection string

Scenario: Error inspecting database with password containing special characters  (@,?,!)
  Given a inspect command atlas schema inspect -u "mysql://user:my_password!@#$@127.0.0.1/atlastest" > schema.hcl  
  When the connection string is parsed
  Then the driver should be "mysql"
  And the username should be "user"
  And the password should be "p@ssw!0rd"
  And the address should be "127.0.0.1"
  And the database name should be "atlastest"

  But When the parsing is done incorrectly
  Then an error message indicating "bash: !0: event not found" is shown
  And the inspect should run successfully

Examples:
| Password | Expected Result |
| my_password!@#$  | bash: !@#: event not found |
| my_p?assword | Error: invalid port ":my_p" after host |

**Comment by a8m** [comment]
Hey @jllanes-ss 
Please see: https://atlasgo.io/concepts/url#non-alphanumeric-characters

**Comment by a8m** [comment]
Closing, but feel free to join our Discord in case you need more help with it.

**Comment by jllanes-ss** [comment]
Hey @a8m 

Thanks and sorry for the rookie mistake with the documentation :P .
