### ISSUE TITLE
bug: `altas schema diff` misbehaves when tables share a constraint name

### ISSUE THREAD

**Issue by Oursin** [ariga/atlas#2884]
Hi ! I've run into an issue with `atlas schema diff` where atlas gets lost if there is a diff on a constraint which shares its name with several others in the database.

### Context
```
atlas version - development
https://github.com/ariga/atlas/releases/latest
```
(fresh `go install`)

Database: PostgreSQL 15

### Steps to reproduce
Create a database with the following schema

```
CREATE TABLE a
(
    name       varchar,
    created_at timestamp,
    updated_at timestamp,
    deleted_at timestamp,
    CONSTRAINT deleted_at_range CHECK (created_at <= deleted_at),
    CONSTRAINT updated_at_range CHECK (created_at <= updated_at)
);

CREATE TABLE b
(
    name       varchar,
    created_at timestamp,
    updated_at timestamp,
    deleted_at timestamp,
    CONSTRAINT deleted_at_range CHECK (created_at <= deleted_at),
    CONSTRAINT updated_at_range CHECK (created_at <= updated_at)
);

CREATE TABLE c
(
    name       varchar,
    created_at timestamp,
    updated_at timestamp,
    deleted_at timestamp
);
```

Running `atlas schema diff` at this point returns `Schemas are synced, no changes to be made.`, as expected.

Now change the schema for the table `c` to this:

```
CREATE TABLE c
(
    name       varchar,
    created_at timestamp,
    updated_at timestamp,
    deleted_at timestamp,
    CONSTRAINT deleted_at_range CHECK (created_at <= deleted_at),
    CONSTRAINT updated_at_range CHECK (created_at <= updated_at)
);
```

Run `atlas schema diff` returns this:
```
-- Modify "a" table
ALTER TABLE "public"."a" DROP CONSTRAINT "updated_at_range";
-- Modify "b" table
ALTER TABLE "public"."b" ADD CONSTRAINT "updated_at_range" CHECK (created_at <= updated_at);
```

Where the expected output would be
```
-- Modify "c" table
ALTER TABLE "public"."c" ADD CONSTRAINT "updated_at_range" CHECK (created_at <= updated_at), ADD CONSTRAINT "deleted_at_range" CHECK (created_at <= deleted_at);
```

**Comment by a8m** [comment]
Hey! We no longer maintain the `cmd/atlas` package as an executable - mainly for technical and time reasons. Atlas is used by various programming languages, like Python and Java, and the binary we distribute includes additional capabilities.

You can use the following command to install Atlas, and report back if you still face issues with it. 

```
curl -sSf https://atlasgo.sh | sh
```

**Comment by Oursin** [comment]
Just tried with the binary received from the script and it works as expected, thanks!

I could be a good idea to add a warning [in the documentation](https://atlasgo.io/community-edition) about this so others don't end up with the same issues.
