### ISSUE TITLE
Support for Clickhouse NOT NULL table column

### ISSUE THREAD

**Issue by justas200** [ariga/atlas#2885]
I want to deploy this table with NOT NULL time_ch column using Atlas HCL and terraform provider.

```
table "data_local" {
  schema = schema.database
  engine = MergeTree
  ttl    = sql("time_ch + toIntervalHour(1)")
  settings = {
    index_granularity          = 8192
  }
  column "metadata" {
    null = true
    type = sql("Nullable(String)")
  }
  column "time_ch" {
    null    = false
    type    = sql("DateTime")
    default = sql("now()")
  }
}
```

however it generates the following command
```
│ CREATE TABLE `data_local` (
│   `metadata` Nullable(String),
│   `time_ch` DateTime DEFAULT now()
│ ) ENGINE = MergeTree
│  PRIMARY KEY tuple() TTL time_ch + toIntervalHour(1) SETTINGS index_granularity = 8192
```

And throws an error on apply.
```
Unable to apply changes, got error: Error: create "data_local" table: code: 450, message: TTL expression result column
│ should have DateTime or Date type, but has Nullable(DateTime)
```

How should I solve this problem? It requires to have NOT NULL clause on time_ch column.
I also have data_type_default_nullable set to 0, however it does not have any impact.

Best regards

**Comment by datdao** [comment]
Hi @justas200, which Atlas vs Clickhosue version are you using?

**Comment by justas200** [comment]
Atlas Terraform `version = "~> 0.8.4"` and Atlas itself is installed using `https://atlasgo.sh` and running `v0.24.1-4e0a13d-canary`. 
Clickhouse-driver is `0.2.8` and the clickhouse server is `clickhouse/clickhouse-server:23.8.14`.

**Comment by datdao** [comment]
Hi @justas200, I have reproduced your case, but I didn't see any errors.  I think there may have been some configuration change on your ClickHouse server. Let's spin up another container `clickhouse/clickhouse-server:23.8.14` locally to compare against

**Comment by justas200** [comment]
Nevermind, it actually does work without `NOT NULL` on  fresh locally running database. Thank you!

**Comment by justas200** [comment]
@datdao I found the issue. I had a global settings `data_type_default_nullable: 0` on the cluster. Having this setting it throws the error. Do you know if there is a workaround?
