### ISSUE TITLE
offer more verifiable installation methods

### ISSUE THREAD

**Issue by costela** [ariga/atlas#2888]
First of all, to make sure this doesn't come off too ungrateful: thanks for the awesome project! :innocent: 

Given the current prevalence of supply-chain attacks it would be great if we could have some more verifiable (e.g. reproducible) installation methods than piping arbitrary shellscripts.
Having community binaries that can be reproduced from code means there are considerably more audit possibilities, which makes it harder for any eventual mallicious tampering to go unnoticed.

I don't quite understand the reasoning behind [not supporting `go install`](https://github.com/ariga/atlas/issues/2659#issuecomment-2031189693), but even if that is out of the question, providing any way to reproduce the downloadable binaries would be a net win, even if we have to jump through some hoops to reproduce them.

This improved verifiability would also trickle down to other installation methods like the container images.

I understand there may be some specifics regarding enterprise builds which the community doesn't have access to, but I'd be willing to lend some time to implement this, if the maintainers agree with the premise :innocent:

**Comment by a8m** [comment]
Hey! Note, binaries can also be downloaded from our website: 
<img width="1114" alt="image" src="https://github.com/ariga/atlas/assets/7413593/8aca838a-be6c-409e-b52a-be2bbee0cb8f">
For example: https://release.ariga.io/atlas/atlas-darwin-amd64-v0.24.0 

---
Closing, as there is no action to take here, but feel free to join our Discord and continue the discussion there.
