### ISSUE TITLE
Consolidate Database Migrations Periodically?

### ISSUE THREAD

**Issue by solomonaboyeji** [ariga/atlas#2921]
We need a command to combine multiple database migration files into one. This could:

- Reduce the number of migration files
- Be run periodically to keep migrations manageable

What's the best way to implement this, and are there any risks to consider?

**Comment by rotemtam** [comment]
Hi @solomonaboyeji,

Thanks for reaching out. 

This is implemented via the [`migrate checkpoint`](https://atlasgo.io/versioned/checkpoint)
