### ISSUE TITLE
Feature Request: Support for Clickhouse Dictionary

### ISSUE THREAD

**Issue by RuiLoureiro** [ariga/atlas#2925]
Hi! Are there any plans to support [Clickhouse Dictionaries](https://clickhouse.com/blog/faster-queries-dictionaries-clickhouse)?

**Comment by datdao** [comment]
Hi @RuiLoureiro,

We released support for dictionary yesterday. You can find the documentation [here](https://atlasgo.io/hcl/clickhouse#dictionary).

Thank you for requesting this! Let us know if you encounter any issues.
