### ISSUE TITLE
What is the HCL standard library? Is this documented anywhere?

### ISSUE THREAD

**Issue by MorganR** [ariga/atlas#2958]
I have noticed that HCL has a [standard library](https://github.com/ariga/atlas/blob/master/schemahcl/stdlib.go) that seems to provide various functions, and I've seen examples of more advanced syntax such as the for loop in [this comment](https://github.com/ariga/atlas/issues/1743#issuecomment-1591034174), but I can't find this documented anywhere.

I apologise in advance if I'm just being a bit thick. Is there anywhere that these functions and basic syntax, like for loops and conditionals, are documented for HCL? I can find very few examples of this sort of dynamic functionality in the docs or guides.

I'm ultimately hoping that I can conditionally set some local variables based on the value of `atlas.env`.

**Comment by kav** [comment]
I don't know that everything here works in Atlas but this is my reference for things to try: https://developer.hashicorp.com/terraform/language

I do know for conditionals ternaries work as described here:
https://developer.hashicorp.com/terraform/language/expressions/conditionals

**Comment by MorganR** [comment]
Perfect, thanks! Had somehow not made the connection that this was the same HCL
