### ISSUE TITLE
Fix the URL parsing for special characters.

### ISSUE THREAD

**Issue by zelawat08** [ariga/atlas#3028]
## Outline of This Issue
Encountered error when using special characters in the password.

## Goal
- Modify the parsing method to add URL escape method.

## Reference
https://github.com/ariga/atlas/blob/0caf6b6ea20b624063f44de7bf1d9c124e7b0468/sql/sqlclient/client.go#L267

**Comment by a8m** [comment]
Hey @zelawat08,

You can use the `urlescape` function in `atlas.hcl`. See: Please see: https://atlasgo.io/concepts/url#non-alphanumeric-characters

---

For more info, please see @rotemtam [comment](https://github.com/ariga/atlas/issues/1034#issuecomment-1212003157) on this subject:

> As the command accepts a URL, the standard way for dealing with odd characters is using URL encoding, see IETF [RFC 1738](https://www.rfc-editor.org/rfc/rfc1738), (see section 2.2) which defines URLs formally. I don't think Atlas should encode the URL for the user as this is a one-time operation (e.g doesn't change unless the password itself changes).

**Comment by giautm** [comment]
You need encode the password before build the URL for atlas

https://atlasgo.io/concepts/url#non-alphanumeric-characters

**Comment by zelawat08** [comment]
> Hey @zelawat08,
> 
> You can use the `urlescape` function in `atlas.hcl`. See: Please see: https://atlasgo.io/concepts/url#non-alphanumeric-characters
> 
> For more info, please see @rotemtam [comment](https://github.com/ariga/atlas/issues/1034#issuecomment-1212003157) on this subject:
> 
> > As the command accepts a URL, the standard way for dealing with odd characters is using URL encoding, see IETF [RFC 1738](https://www.rfc-editor.org/rfc/rfc1738), (see section 2.2) which defines URLs formally. I don't think Atlas should encode the URL for the user as this is a one-time operation (e.g doesn't change unless the password itself changes).

I see, I didn't knew this thank you, is there a way when passing the password with special character when using -u option during the migrate apply command? 
Please help me with this. 🙇
