### ISSUE TITLE
Atlas HCL Syntax: String Not Recognized by Linter

### ISSUE THREAD

**Issue by whilsman-tmt** [ariga/atlas#3061]
More of a general annoyance I noticed this morning after installing the Atlas HCL Syntax package for VSCode. Started creating a new project configuration file and what I've started noticing is that when creating input variables with string types the HCL Syntax for some reason does not recognize strings. Shows up as an `Unexpected Keyword` for some reason.

This should be correct though based on what I am seeing on the [Atlas site](https://atlasgo.io/atlas-schema/projects#input-variables)?

```hcl
variable "user" {
  type    = string  # This for some reason fires an error.
  default = "whilsman"
}
```

**Comment by a8m** [comment]
Hey @whilsman-tmt 

What Atlas version are you using? (The extension communicates with Atlas using LSP).

**Comment by whilsman-tmt** [comment]
Currently on:
atlas version v0.25.1-a1b8c01-canary
https://github.com/ariga/atlas/releases/latest

**Comment by a8m** [comment]
Can you try to upgrade Atlas, restart the editor, and report if this solves the issue?

**Comment by whilsman-tmt** [comment]
Installed the latest version and still seeing it. No worries here! Just wanted to report what I was seeing. For the time being will just uninstall it.

Current Version:
carnegie-py3.11➜  unity git:(wh/atlas_image) ✗ atlas version
atlas version v0.26.1-99a6fcd-canary
https://github.com/ariga/atlas/releases/latest

**Comment by a8m** [comment]
Issue was fixed with the latest build:
<img width="647" alt="image" src="https://github.com/user-attachments/assets/fe46dc15-d253-49b9-88cb-f9d6f9785d8f">
<img width="559" alt="image" src="https://github.com/user-attachments/assets/39eaf407-6ca3-425d-a26d-72c3a2351f2f">


Thanks for reporting this.
