### ISSUE TITLE
[vsCode extension]: Do not require schema files to end in `.pg.hcl`

### ISSUE THREAD

**Issue by yannxaver** [ariga/atlas#3064]
Even if the vsCode file association is set to "Atlas PostgreSQL", the vsCode Atlas extension does not provide auto-complete if the schema file extension is not `.pg.hcl`. I could not find this specific schema file extension requirement documented and it also seemed arbitrary because the vsCode extension worked with the file extension `.hcl` previously. Was there a specific reason that required a change to a mandatory `.pg.hcl` file extension?

**Comment by a8m** [comment]
> Was there a specific reason that required a change to a mandatory .pg.hcl file extension?

Yes, each database (PostgreSQL, Redshift, SQLite, etc) has its own language options and file extension to auto-detect, suggest, and enforce the syntax. The default `.hcl` supported by the editor gives basic syntax highlighting and completion, but it's not grammar/database aware. 

Closing, as we do not have plans to change this in the near future.
