### ISSUE TITLE
Possible patch release 0.26.1

### ISSUE THREAD

**Issue by GAlexIHU** [ariga/atlas#3072]
Issue was resolved with ent@v0.14.1 and Atlas latest build.
              Please reopen if you face any issues with it.

_Originally posted by @a8m in https://github.com/ariga/atlas/issues/3068#issuecomment-2308428250_

I don't have access to reopen the previous issue, apologies for the potential spam. Is there a chance of a patch release happening with that above fix?

I can validate that it works as expected on the latest build, but we'd be weary to depend on the latest tag (which now differs from 0.26.0), and based on the release history it seems atlas is incremented by minor version bumps.

**Comment by a8m** [comment]
Branch was tagged and a new version was released. Binaries should be available to download.
