### ISSUE TITLE
 `Unknown variable; There is no variable named "PLpgSQL".` when creating Function

### ISSUE THREAD

**Issue by frixaco** [ariga/atlas#3075]
I'm logged in using `atlas login`.
Getting  `Unknown variable; There is no variable named "PLpgSQL".` when running `atlas schema apply -u "URL" -f abcd-schema.hcl`. Also tried using `PL` and `SQL` instead of PLpgSQL. Database is a MySQL database (PlanetScale).

Schema:
```

table "roomParticipant" {
  schema = schema.abcd

  column "id" {
    null           = false
    type           = bigint
    unsigned       = true
    auto_increment = true
  }

  column "updatedDate" {
    null = false
    default = sql("CURRENT_TIMESTAMP")
    type = datetime
  }

  primary_key {
    columns = [column.id]
  }
}

function "update_roomParticipant_updatedDate" {
  schema = schema.abcd
  lang   = PLpgSQL
  return = trigger
  as     = <<-SQL
  BEGIN
    UPDATE roomParticipant SET updatedDate = CURRENT_TIMESTAMP WHERE id = NEW.id;
    RETURN NEW;
  END;
  SQL
}
trigger "update_roomParticipant_updatedDate_trigger" {
  on = table.roomParticipant
  after {
    update = true
  }
  foreach = ROW
  execute {
    function = function.update_roomParticipant_updatedDate
  }
}
```

**Comment by a8m** [comment]
Hey! The pg in `PLpgSQL` stands for PostgreSQL. You can’t use this in MySQL-flavored database.

Please, use the MySQL examples from the website.

**Comment by frixaco** [comment]
Thanks for the reply @a8m. FYI, there isn't a single example (in HCL syntax) for functions and triggers for MySQL databases.

**Comment by a8m** [comment]
Click on the MySQL tab:
<img width="896" alt="image" src="https://github.com/user-attachments/assets/929f433b-c4dd-4910-8d22-ec75f2e0b5fa">

https://atlasgo.io/atlas-schema/hcl#function

**Comment by frixaco** [comment]
@a8m ok, I'm blind apparently. Sorry for wasting your time.
