### ISSUE TITLE
`atlas migrate lint` takes very long

### ISSUE THREAD

**Issue by nakamasato** [ariga/atlas#3077]
I'm using atlas with versioned migration.

When having many large sql files (e.g. manually created DML files with thousands of rows), `atlas migrate lint` takes very long.

Even though I use `atlas migrate set` to set the schema as latest as possible, `altas migrate lint` is very slow. It would be better if `atlas migrate lint` only checks for the new files to be applied.

**Comment by rotemtam** [comment]
Migrate lint always replays all migrations on an empty database, so it is expected to run any statement in these files. This is done to bring the db to the current state before applying any new migrations.

This can be somewhat circumvented using checkpoints, but I'm not certain it is applicable in your use case.

https://atlasgo.io/versioned/checkpoint

**Comment by nakamasato** [comment]
Thank you! I'll take a look at it.

**Comment by a8m** [comment]
@nakamasato, feel free to reopen if the issue is not solved with checkpoints.
