### ISSUE TITLE
Jetbrains IntelliJ Plugin and Code Folding

### ISSUE THREAD

**Issue by cajund** [ariga/atlas#3091]
Hi Folks,

I seem to recall this wasn't a problem before, but after upgrading both IntelliJ and the Atlas plugin, the code in my .hcl file no longer "folds" As this DB description gets longer, code folding becomes a significant part of the operation and management. 

Am I missing something on my end perhaps? This version of IntelliJ has crashed a few times, so maybe some preference file is corrupted (wouldn't be the first time).

So I was curious what you guys thought. I'm on a 2021 Apple M1 Pro. Latest of everything.

Thanks.

**Comment by a8m** [comment]
The issue was resolved by the previous version (v0.29). 

Please, feel free to join our Discord or reopen this issue if you need any help.
