### ISSUE TITLE
Incorrect migration DDL generated for simple views with `null as`

### ISSUE THREAD

**Issue by markalexander** [ariga/atlas#3096]
Hi,

For some reason, atlas seems to create incorrect DDL when generating migrations for a simple view containing `select null as x` syntax.

  - Atlas version: `v0.26.2-0db2f5c-canary`
  - Database: ClickHouse v24
  - Platform: OSX 15 (M2)

I'm doing this declaratively from a `.sql` file, although it's from an empty DB so these are simple `create` statements.

**MWE:**

In e.g. `schema.sql`:

```sql
create or replace view v1 as (
	select null as c1
);
````

Bring up target with e.g.:

    docker run -p 9000:9000 clickhouse/clickhouse-server:24

Then try to migrate:

    atlas \
	    schema apply \
	    -u "clickhouse://default:@localhost:9000" \
	    --dev-url "docker://clickhouse/24" \
	    --to "file:///[SCHEMA FILE]" \
	    --auto-approve

For me, this fails with:

    -- Planned Changes:
    -- Create "v1" view
    CREATE VIEW `default`.`v1` (
     
    ) AS SELECT NULL AS c1;

    Error: create "v1" view: code: 62, message: Syntax error: failed at position 32 (')') (line 3, col 1): ) AS SELECT NULL AS c1. Expected one of: columns or indices declaration list, list of elements, table property (column, index, constraint) declaration, INDEX, CONSTRAINT, PROJECTION, PRIMARY KEY, FOREIGN KEY, column declaration, identifier

It seems that the create view DDL generated is incorrect, with the empty parens before the select statement.

Running `schema.sql` above in a regular ClickHouse client seems to work fine.

**Comment by datdao** [comment]
Hi @markalexander, thanks for the detailed info. Creating a view without a dependent table is new to me. Let me check it again and fix it if needed. Btw, may I ask your usecase related to that view?  🤔

**Comment by datdao** [comment]
Hi @markalexander,  I've tried creating a view with `NULL AS` directly to Clickhouse instance, but the result was an empty column in view. This indicates that the issue is with ClickHouse's handling rather than Atlas. To resolve the problem, here's the correct approach:
```
CREATE VIEW `default`.`v1` (
    c1 String,
    c2 Nullable(Int8)
) AS SELECT t1.c1, NULL AS c2 FROM table1 AS t1;
```
or do it like you do `Nullable(Int8)` cast type for `null`
