### ISSUE TITLE
schema inspect can not parse url correctly with '#' in password

### ISSUE THREAD

**Issue by Jonwing** [ariga/atlas#3099]
Hello:

I'm using altas schema inspect command and encounter an error:

```shell
❯ docker run --rm arigaio/atlas schema inspect -u "mysql://test:within_psw@localhost:3306/test"
Error: mysql: query system variables: dial tcp 192.168.0.2:3306: connect: connection refused

//  # in password causes parse error
❯ docker run --rm arigaio/atlas schema inspect -u "mysql://test:with#in_psw@localhost:3306/test"
Error: invalid port ":with" after host

❯ docker run --rm arigaio/atlas schema inspect -u "mysql://test:with@in_psw@localhost:3306/test"
Error: mysql: query system variables: dial tcp 192.168.0.2:3306: connect: connection refused
```
'#'  in password is not supported?

**Comment by a8m** [comment]
Hey @Jonwing,

You need to encode the password before passing the URL to Atlas. You can use the `urlescape` function in `atlas.hcl`. See: Please see: https://atlasgo.io/concepts/url#non-alphanumeric-characters

---

For more info, please see @rotemtam [comment](https://github.com/ariga/atlas/issues/1034#issuecomment-1212003157) on this subject:

> As the command accepts a URL, the standard way for dealing with odd characters is using URL encoding, see IETF [RFC 1738](https://www.rfc-editor.org/rfc/rfc1738), (see section 2.2) which defines URLs formally. I don't think Atlas should encode the URL for the user as this is a one-time operation (e.g doesn't change unless the password itself changes).
