### ISSUE TITLE
Atlas generates versioned migrations that rename unique indexes

### ISSUE THREAD

**Issue by PetroPower** [ariga/atlas#3143]
I am attemping to upgrade atlas within our go project. We are using GORM as our ORM.

## Environment 

Updating *from* atlas version:
```shell
# atlas install
root@8f9a47b3ddf1:/project# go install -v ariga.io/atlas/cmd/atlas@latest

# atlas version information
root@8f9a47b3ddf1:/project# atlas version
atlas version - development
https://github.com/ariga/atlas/releases/latest

# atlas binary hash
root@8f9a47b3ddf1:/project# sha1sum `which atlas`
ad9d2c9ac663ae39f247a782d056474351770b67  /go/bin/atlas

# go mod file
root@8f9a47b3ddf1:/project# grep -E '(gorm|atlas)' go.mod
        ariga.io/atlas-go-sdk v0.1.0
        ariga.io/atlas-provider-gorm v0.1.0
        gorm.io/driver/mysql v1.5.1
        gorm.io/gorm v1.25.4
        gorm.io/driver/postgres v1.5.2 // indirect
        gorm.io/driver/sqlite v1.5.3 // indirect
```

Updating *to* atlas version:
```shell
# atlas install (no longer available via `go install` ....)
root@d130a4a0aa7b:/project# wget https://release.ariga.io/atlas/atlas-linux-amd64-v0.27.0 && \
root@d130a4a0aa7b:/project# install atlas-linux-amd64-v0.27.0 /usr/local/bin/atlas

# atlas version information
root@d130a4a0aa7b:/project# atlas version  
atlas version v0.27.0
https://github.com/ariga/atlas/releases/tag/v0.27.0

# atlas binary hash
root@d130a4a0aa7b:/project# sha1sum `which atlas`
ac43220a533ac7848255f20995b8e3fdfee7527d  /usr/local/bin/atlas

# update gorm provider
root@d130a4a0aa7b:/project# go get -u ariga.io/atlas-provider-gorm

# go mod file
root@d130a4a0aa7b:/project# grep -E '(gorm|atlas)' go.mod
        ariga.io/atlas-go-sdk v0.6.2
        ariga.io/atlas-provider-gorm v0.5.0
        gorm.io/driver/mysql v1.5.7
        gorm.io/gorm v1.25.12
        gorm.io/driver/postgres v1.5.9 // indirect
        gorm.io/driver/sqlite v1.5.6 // indirect
        gorm.io/driver/sqlserver v1.5.3 // indirect
```

## Observed Behavior
After the upgrade `atlas migrate diff` gives me the following prompt for every unique index in my schema:

```shell
root@d130a4a0aa7b:/project# atlas migrate diff --env local
? Did you rename "table_foo" index from "index_on_foo" to "uni_table_foo_index_on_foo": 
  ▸ Yes
    No
```

If I select *Yes* it alters my schema to rename the indexes: E.G.
```sql
ALTER TABLE `table_foo` RENAME INDEX `index_on_foo` TO `uni_table_foo_index_on_foo`;
-- ... lots of other ALTER statements ...
-- ... for every index in my schema ...
ALTER TABLE `table_bar` RENAME INDEX `index_on_bar` TO `uni_table_bar_index_on_bar`;
```

If I select *No* it alters my schema to drop and add the indexes: E.G.:
```sql
ALTER TABLE `table_foo` DROP INDEX `index_on_foo`, ADD UNIQUE INDEX `uni_table_foo_index_on_foo` (`column_on_foo`);
-- ... lots of other ALTER statements ...
-- ... for every index in my schema ...
ALTER TABLE `table_bar` DROP INDEX `index_on_bar`, ADD UNIQUE INDEX `uni_table_bar_index_on_bar` (`column_on_bar`);
```

I have not changed any GORM models in my code base. The only change is to upgrade the atlas CLI tool and corresponding
go integration library.

## Expected Behavior
I expect no changes to my schema if I have not updated my GORM models. Why is atlas choosing to rename all of my unique indexes?

What options do I have to prevent atlas from renaming these? I do not think it is reasonable to run such a migration.

**Comment by a8m** [comment]
Hey! Please, use the instructions in this link to install Atlas: https://atlasgo.io/docs#installation

Then, please report if you still face any issues with it.

**Comment by PetroPower** [comment]
Done. I removed `wget https://release.ariga.io/atlas/atlas-linux-amd64-v0.27.0` and replaced it with `curl -sSf https://atlasgo.sh | sh`

The issue persists. `atlas migrate diff` generates migrations that rename unique indexes when there are no changes to GORM models. The issue is identical to the original description above.

The install was done from a clean environment. I.E. from a fresh container without atlas installed.
```shell
root@18fda9d0c094:/project# curl -sSf https://atlasgo.sh | sh

root@18fda9d0c094:/project# atlas version
atlas version v0.27.0
https://github.com/ariga/atlas/releases/tag/v0.27.0

root@18fda9d0c094:/project# sha1sum `which atlas`
ac43220a533ac7848255f20995b8e3fdfee7527d  /usr/local/bin/atlas
```

As to your link to the install instructions: we included atlas in our project some time ago when installing via go was an acceptable method. We are in the process of upgrading the tooling now to the latest version.

We expect the latest version to gracefully handle an update from an older version. This expectation should not be surprising.

**Comment by a8m** [comment]
Can you provide an example that reproduce this issue? I'll try to reproduce. 

Regarding the index naming - I suspect this is not an issue on Atlas, but rather on the provider that generates these names (GORM), because Atlas has no preferences on object naming. Any chance you upgraded the GORM version at the same time? Either way, if you provide a simple example, I'll try to help. 

> As to your link to the install instructions: we included atlas in our project some time ago when installing via go was an acceptable method. We are in the process of upgrading the tooling now to the latest version.
> We expect the latest version to gracefully handle an update from an older version. This expectation should not be surprising.

We deprecated the Go installation more than a year a Go, so whenever someone reports an issue, I want to make sure they work on the latest stable version. That's why I ask for upgrade when I see unexpected behavior.

**Comment by PetroPower** [comment]
@a8m

You nailed it. The change is in GORM. We went from v1.25.4 to v1.25.12

https://github.com/go-gorm/gorm/commit/9fea15ae75fb9ff2bd86dcaa167673c8ed77394f#diff-a7a5f31f4c54e7b1e7d0ec3bea837cf3c887cc4f7dd7b37a320682ff485c52bcR93

Thank you for the nudge in the right direction. I guess GORM felt that a change to their unique index naming strategy was only a worthy of a bump to the micro ... 

--- 

> We deprecated the Go installation more than a year ago

As an aside -- I am sure there are plenty of other go users out there that still use `go install -v ariga.io/atlas/cmd/atlas@latest` to fetch atlas and falsely believe they're getting the latest version.

It would be extremely helpful to all these users if there was a final update to this `go install` version that included a loud banner pointing them over to the new install method.
