### ISSUE TITLE
question: store state in db

### ISSUE THREAD

**Issue by hofq** [ariga/atlas#3171]
Hi there,
just got my hands on using atlas in my first project.

What function can I use to store the current migration state in the DB itself, like with Liquibase and run Smart database updates?

I have a tiny app deployed in various environments, so putting some kind of operator or special argocd configuration there would be absolute overkill.

If I try to just apply the newest revision, I get an error which states `pq: relation "tablename" already exists`

**Comment by a8m** [comment]
Hey! I assume you use the versioned migration workflow, right? (`migrate diff/apply`).

Atlas maintains a revisions table in the database, so executing unapplied migrations should be handled seamlessly by Atlas. I assume you're trying to use Atlas on an existing database (with existing state/tables). In that case, you should use a baseline migration file, and configure Atlas to use it. See: https://atlasgo.io/versioned/apply#existing-databases

**Comment by a8m** [comment]
Closing, but please feel free to reopen or join our Discord server if you need more help.
