### ISSUE TITLE
MySQL CONSTRAINT CHECK does not update (ALTER)

### ISSUE THREAD

**Issue by craigmonson** [ariga/atlas#3206]
Trying to update a`CONSTRAINT CHECK` on a table and, when running `atlas migrate diff`, it reports that there's no differece.

original:
```hcl
  check "start_hour" {
    expr = "(`start_hour_ending` between 1 and 24)"
  }
```

updated (changed 24 to 25):
```hcl
  check "start_hour" {
    expr = "(`start_hour_ending` between 1 and 25)"
  }
```

atlas reports: `The migration directory is synced with the desired state, no changes to be made`

```sh
%> atlas version
atlas version v0.28.1
https://github.com/ariga/atlas/releases/tag/v0.28.1
```

**Comment by a8m** [comment]
Thanks for reporting this, @craigmonson. Issue was resolved with https://github.com/ariga/atlas/pull/3208.
