### ISSUE TITLE
atlas.hcl: enforce authenticated (atlas login) usage for CLI commands

### ISSUE THREAD

**Issue by torchsec-roni** [ariga/atlas#3214]
Hey, we recently encountered the following error when trying to run `atlas migrate diff`:

```sh
➜  atlas migrate --env local diff
Error: drop enum type "my_favorite_enum": pq: cannot drop type my_favorite_enum because other objects depend on it
```

This was resolved by running:

```sh
➜  atlas login
```

The error message was very confusing.

**Comment by a8m** [comment]
Hey! Thanks for the feedback, @torchsec-roni. 

That's because when you're not logged in, some [database features](https://atlasgo.io/community-edition#database-features) will not be managed by Atlas. We'll add an option in the `atlas.hcl` file to enforce login. I'll keep this issue open so you can track the progress of it.

**Comment by torchsec-roni** [comment]
Sounds great! This will be very helpful for our team, our engineers have been encountering this sporadically recently

**Comment by torchsec-roni** [comment]
This just happened again to someone new on the team who lost a couple hours trying to troubleshoot on his own. Is there any chance to prioritize this?

**Comment by a8m** [comment]
Sure, @torchsec-roni! I'll make sure it's added to the upcoming milestone. I'll let you know when it's out.

**Comment by torchsec-roni** [comment]
Thanks @a8m , appreciate it!

**Comment by a8m** [comment]
Hey @torchsec-roni,

This feature was added to our latest canary release and you can test it via this config: https://atlasgo.io/atlas-schema/projects#atlas-block

A new tagged version will be released in the upcoming days, but you are welcome to try it until then and report if you have any troubles with it.

Thanks again for the feedback, it's appreciated 🙏

**Comment by torchsec-roni** [comment]
Thanks for the hard work on this, looking forward to the new tagged version to try it out! 🥳
