### ISSUE TITLE
CONSTRAINT TRIGGER support

### ISSUE THREAD

**Issue by gebes** [ariga/atlas#3233]
@a8m as discussed in Discord

Hello! When I define a postgres constraint trigger, atlas just creates a regular one

input
```sql
CREATE CONSTRAINT TRIGGER trg
    AFTER INSERT
    ON table
    INITIALLY DEFERRED
    FOR EACH ROW
```

migration
```sql
CREATE TRIGGER trg
    AFTER INSERT
    ON table
    FOR EACH ROW
```

**Comment by a8m** [comment]
Closed with https://github.com/ariga/atlas/releases/tag/v0.29.0.

Thanks for reporting this 🙏
