### ISSUE TITLE
Add a `--desc` flag to `atlas migrate diff`

### ISSUE THREAD

**Issue by shitwolfymakes** [ariga/atlas#3235]
It'd be nice to append a description of the migration to the timestamp in the filename of the output SQL file, similar to how Prisma does it.

I can take a crack at adding this myself if there isn't enough interest in this feature.

**Comment by a8m** [comment]
Hey @shitwolfymakes 👋 

The [`migrate diff` command](https://atlasgo.io/cli-reference#atlas-migrate-diff) accepts an optional argument for this purpose. e.g., `atlas migrate diff add_users_name`.

Closing, but let me know if something is not clear or you need any help with this.

**Comment by shitwolfymakes** [comment]
Ah okay, I didn't see that anywhere when I was reading through the docs, but there are *a lot*. Can you point me to where in the docs it's mentioned?
