### ISSUE TITLE
SQLServer and Azure Workload Identities

### ISSUE THREAD

**Issue by perpective2410** [ariga/atlas#3254]
We would like to connect Atlas to Azure SQL server using Azure Workload Identities.

1. Is it currently supported?
2. I can see this https://github.com/ariga/atlas/issues/2590 but it looks like its only solving the Azure AD auth (Entra), but I dont think it solved the Workload Identity Auth.
3. There is also this https://github.com/ariga/atlas/issues/2343, but it looks like this is related to AzureAD auth. IMO, this issue can be closed as it's working using the following command, e.g
`atlas schema apply -u "azuresql://<hostname>.database.windows.net?fedauth=ActiveDirectoryDefault&database=<db>" -f schema.sql --dev-url "docker://sqlserver/2022-latest"`

In your documentation (https://atlasgo.io/concepts/url) tab SQLServer, you are pointing [go-mssqldb driver]. (https://github.com/microsoft/go-mssqldb?tab=readme-ov-file#azure-active-directory-authentication). It looks like we can potentially used "fedauth=ActiveDirectoryManagedIdentity"

```
apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasSchema
metadata:
  name: sql-migration-sample-service
spec:
  schema:
    sql: |
      create table users (
        id int not null auto_increment,
        primary key (id)
      );
  url: "azuresql://<hostname>.database.windows.net?fedauth=ActiveDirectoryManagedIdentity&user id=<msi_id>"
```

I can't test it because of https://github.com/ariga/atlas/issues/3250. The atlas-dev-db pod is not running using the right service account so I am getting the following error

```
To troubleshoot, visit https://aka.ms/azsdk/go/identity/troubleshoot#managed-id    {"type": "Warning", "object": {"kind │
│ 2024-12-11T15:16:34Z    DEBUG    events    Error: mssql: query server property: ManagedIdentityCredential authenticatio │
│ GET http://169.254.169.254/metadata/identity/oauth2/token                                                               │
│ --------------------------------------------------------------------------------                                        │
│ RESPONSE 400 Bad Request                                                                                                │
│ --------------------------------------------------------------------------------                                        │
│ {                                                                                                                       │
│   "error": "invalid_request",                                                                                           │
│   "error_description": "Identity not found"                                                                             │
│ }                                                                                                                       │
│ --------------------------------------------------
```

**Comment by giautm** [comment]
Hello @perpective2410, you can run the dev-database by yourself, then provide the URL for AtlasSchema resource. It should unblock your case. We're working on update for atlas-operator for custom the dev-database spec,

**Comment by perpective2410** [comment]
Thanks @giautm Could you please provide me with an example?
From what I understood, AtlasSchema is creating the dev pod for me

**Comment by giautm** [comment]
You can provide the dev database information via `devURL` or `devURLFrom` on the `AtlasSchema` spec. The operator won't bring up its own dev-db instance.

**Comment by perpective2410** [comment]
Ah I see thank you.
Which entity is doing the authentication with "azuresql://<hostname>.database.windows.net?fedauth=ActiveDirectoryManagedIdentity&user id=<msi_id>". Is it the Operator pod or the Dev pod?

**Comment by giautm** [comment]
It's the operator pod, you can control the service account via our helm chart.

**Comment by perpective2410** [comment]
Ok, I have been able to validate it using System Identity. It should also work for Workload Identity by providing `user id=<identity id>`. Example

` atlas schema inspect -u "azuresql://<hostname>.database.windows.net?fedauth=ActiveDirectoryManagedIdentity&database=<db>&user id=<identity id>"`
