### ISSUE TITLE
Postgres Comment Changes Do Not Generate Diff

### ISSUE THREAD

**Issue by awgneo** [ariga/atlas#3256]
I am aware that Atlas [doesn't officially support](https://atlasgo.io/features#database-features) Postgres comments, but they do make it from my desired SQL state file into my initial diff, which gave me hope, as my application relies heavily upon them.

**With a comment such as this:**

```
COMMENT ON FUNCTION agreego.punc IS '{
  "description": "Calls a punc",
  "public": false,
  "request": {
    "type": "object",
    "required": [ "name" ],
    "properties": {
      "name": { "type": "string" }
    }
  },
  "response": {
    "type": "object"
  }
}';
```

On any function, changing the comment itself, such as public from false to true, or anything in the comment string, will not generate a diff with `atlas migrate diff`.

Atlas should detect comment changes and apply them as such in diff calculations. I hope this is an easy change.

**Comment by a8m** [comment]
Hey @awgneo 👋 

What version are you using?

**Comment by awgneo** [comment]
@a8m apologies: atlas version v0.29.1-b71d911-canary

**Comment by awgneo** [comment]
I just tested in atlas version v0.29.1-7dbefb0-canary as well; still:

`The migration directory is synced with the desired state, no changes to be made`

**Comment by a8m** [comment]
Hey! The issue was fixed and a new version was pushed. Let us know if you have any more issues with it.

**Comment by awgneo** [comment]
@a8m That worked! Thank you ;)
