### ISSUE TITLE
Atlas migrate diff fails with `type "public.citext" does not exist`

### ISSUE THREAD

**Issue by vamshiaruru** [ariga/atlas#3268]
Hi everyone, we have been using atlas for a while now and we have not encounterted this error before. We have a multiple tables (> 100) in public schema of our postgres DB. We generate migrations by giving a path to the migrations directory and schema.sql file, like so:

```
atlas migrate diff MIGRATION_NAME --dir "file://remote/db/migrations" --to "file://remote/db/schema.sql" --dev-url 'postgres://username:password@localhost:5432/dev_db?sslmode=disable'
```

All of a sudden this started failing with all sorts of errors. First it failed with `database not clean` saying some table was found. We were on a quite old version of atlas, so we updated it to the latest version, and now it is failing with:

```
Error: pq: type "public.citext" does not exist
```

But we already have 

```
CREATE EXTENSION IF NOT EXISTS "citext";
```

and it hasn't failed so far. What do we do here? Any help is very appreciated.

Thanks in advance.

**Comment by a8m** [comment]
Hey @vamshiaruru 👋 

>  First it failed with database not clean saying some table was found

If you got this error on `migrate diff`, that means your local dev-database is "dirty": it has some resources exist on it. If you are unfamiliar with Atlas "Dev Database" concept, you can read this doc: https://atlasgo.io/concepts/dev-database

> Atlas uses the **dev database** to compute the state of the migrations directory and the desired state of the database schema. Therefore, before starting its work, Atlas ensures the dev database is clean and there are no leftovers from previous runs. Once done, Atlas cleans up after itself and the dev database is ready for future runs.

> CREATE EXTENSION IF NOT EXISTS "citext";

Where do you define this statement? the `schema.sql` or the migrations directory?

**Comment by vamshiaruru** [comment]
Thanks for the response!

I understand that the dev db has to be clean. I cleaned it up after updating the atlas version. So right now I've recreated it to be completely empty.

It is in `schema.sql` file.

**Comment by a8m** [comment]
Got it. Do you have an Atlas Pro license?

**Comment by vamshiaruru** [comment]
No, we don't have a pro license.

**Comment by a8m** [comment]
Managing extensions requires a Pro license: https://atlasgo.io/features#database-features

If you can't upgrade to Pro, you can create the dev-database manually and install the extension there. Then, add the `CREATE EXTENSION` manually to your migrations. 

BTW, extensions always required Pro license, so probably your issue was the local dev-database.

**Comment by vamshiaruru** [comment]
Oh, I didn't know it required a pro license :( 
I have installed the extension in the dev db and have added it to my migrations, but it doesn't seem to help. Should I take a free trial of the pro license and see if that helps? Do I have to make any changes to my commands after getting the license?

**Comment by a8m** [comment]
> Oh, I didn't know it required a pro license :(

**Comment by a8m** [comment]
> Oh, I didn't know it required a pro license :(

See this as an opportunity to support us :)

**Comment by vamshiaruru** [comment]
thank you, I will definitely talk to my higher ups and try to convince them to take a subscription. We have used atlas a lot, so it makes sense!

I have taken a trial account for pro subscription and I'm running the following command:
```
atlas migrate diff product_group \
  --dir "file://remote/db/migrations" \
  --to "file://remote/db/schema.sql" \
  --dev-url "docker://postgres/15.7/dev"
  ```
  But I'm still getting the same error:
  ```
  Error: pq: type "public.citext" does not exist
  ```

**Comment by a8m** [comment]
Do you have the extension installed on your migrations directory? Because if you was not logged in until now, Atlas never added it there.

**Comment by vamshiaruru** [comment]
So we added citext later on, and previous versions of atlas did not raise an error about this. So 
`CREATE EXTENSION IF NOT EXISTS citext;` is actually present in one of the later migrations (I was wrong when I said it is there only in schema.sql file). Should I add it to the first migration file and do a rehash and try again?

**Comment by a8m** [comment]
Yes.

**Comment by vamshiaruru** [comment]
I have done that, it still doesn't help. I went to the first migration file in `atlas.sum` and added the create extension statement at the very top. Then I ran `atlas migrate hash`, and then the atlas migrate diff command again. Same error.

**Comment by a8m** [comment]
This is how it should work:
![image](https://github.com/user-attachments/assets/5c4acee6-257f-4080-939e-0609b980b0e1)
![image](https://github.com/user-attachments/assets/e59e9352-2a96-46d9-bdc6-fd984f1fad04)

--

Try to run this and let me know if you see the extension there:
```
atlas schema inspect \
  --url "file://remote/db/schema.sql" \
  --dev-url "docker://postgres/15.7/dev"
```

**Comment by vamshiaruru** [comment]
Yes, I see the extension in response atlas schema inspect. This is at the end of the response:

```
extension "citext" {
  schema  = schema.public
  version = "1.6"
  comment = "data type for case-insensitive character strings"
}
schema "public" {
  comment = "standard public schema"
}
```

**Comment by a8m** [comment]
kk, and do you see it also in the directory? 

```
atlas schema inspect \
  --url "file://remote/db/migrations" \
  --dev-url "docker://postgres/15.7/dev"
```

Also, what's your Atlas version?

**Comment by vamshiaruru** [comment]
For this command, I see this
```
extension "citext" {
  schema  = schema.public
  version = "1.6"
  comment = "data type for case-insensitive character strings"
}
schema "public" {
  comment = "standard public schema"
}
```
at the end again. So citext seems to be there as well. And atlas version is v0.29
```
atlas version
atlas version v0.29.1-85cc973-canary
https://github.com/ariga/atlas/releases/latest
```

**Comment by a8m** [comment]
If that's the case, this should work, unless you use `citext` in the migration directory before it was installed. So make sure it's defined as the first command in the first migration file.

If this still does not work, you can feel free to send me your setup on our Discord (in private message) and I can give it a look.

**Comment by vamshiaruru** [comment]
Okay, thank you. I'll send you a DM on discord. I have checked that the `citext` is at the very top of the very first migration file  in atlas.su.

**Comment by a8m** [comment]
The issue was resolved with latest version. Please, reinstall Atlas and try again. 

Feel free to reopen the issue if it persists.
