### ISSUE TITLE
Incorrect syntax near '='.

### ISSUE THREAD

**Issue by AnielaN994** [ariga/atlas#3270]
Hello,

I have in Azure SQL Server a procedure like below:

CREATE  PROC test
	@RowsAffected INT = NULL OUTPUT AS
BEGIN
 ......
END 
GO

and when I run atlas inspect to generate the schema.sql,
in the schema.sql the proc is generated with a syntax error:

CREATE PROCEDURE test (@RowsAffected int OUTPUT = NULL) AS BEGIN
 .......
END
GO

![image](https://github.com/user-attachments/assets/f7ea4e0d-8e04-4328-84ec-5601d1561b46)

and this gives the error "Incorrect syntax near '='."

**Comment by giautm** [comment]
Thank you for report, I'll handle this ASAP.

**Comment by giautm** [comment]
Hello @AnielaN994 this issue was fixed in the latest version, please upgrade and verify.

**Comment by AnielaN994** [comment]
Hello, 

Not sure how to upgrade to the latest version, on GitHub I see this one as the latest:
![image](https://github.com/user-attachments/assets/b9d9d254-4f79-412a-8e14-d389417d090a)
In another ticket, you showed which was your version and I explicitly exported that one with 'export ATLAS_VERSION=v0.29.1-23dbf7d-canary && curl -sSf https://atlasgo.sh | sh', could you please let me know which is the version of this latest one ?

Thanks.

**Comment by AnielaN994** [comment]
I see it works now, thanks!

**Comment by giautm** [comment]
@AnielaN994 just run `curl -sSf https://atlasgo.sh/ | sh` it will download the latest version and install.
