### ISSUE TITLE
Unable to disable the PG110 lint

### ISSUE THREAD

**Issue by pylaligand** [ariga/atlas#3280]
See repro at https://github.com/pylaligand/atlas-samples?tab=readme-ov-file#unable-to-disable-the-pg110-lint.

**Comment by a8m** [comment]
Thanks for reporting this, @pylaligand. We submitted a patch to resolve this and a new version should be available in a few minutes.

**Comment by pylaligand** [comment]
Awesome! Out of curiosity, what was the patch?

**Comment by a8m** [comment]
The diagnostic was missing the statement position.
