### ISSUE TITLE
Postgres schema selection

### ISSUE THREAD

**Issue by cthackers** [ariga/atlas#457]
Hi, 
Is there a way to define what schema I want it to inspect/migrate ? 
From [here](https://github.com/ariga/atlas/blob/11ba264cfa606ce987375e0a08e7888e40711475/cmd/action/mux.go#L93) it seems is hardcoded to only use `public` schema. The project I'm working on uses 3 different schemas and `public` is not used at all. Running inspect on my database gives me an empty result.

**Comment by CGA1123** [comment]
@cthackers I wonder whether a patch like this fixes your issue? https://github.com/cga1123/atlas/commit/50991749f48dccbbd073c405dac91e4697f18a1a

**Comment by a8m** [comment]
CGA1123@5099174 looks great to me.

cc @rotemtam, @yonidavidson

**Comment by rotemtam** [comment]
hey @CGA1123 ,
that looks great, do you mind sending a PR so we can add it to the next version?

**Comment by CGA1123** [comment]
Yep can roll it into a PR this evening, unless you want to cherry pick yourself earlier?

**Comment by rotemtam** [comment]
No rush, when you have the time :-)
