### ISSUE TITLE
The version set does not quite work

### ISSUE THREAD

**Issue by chenrui333** [ariga/atlas#458]
I tried to build from the source, but could not get the version working.

### how to reproduce

- untar `https://github.com/ariga/atlas/archive/refs/tags/v0.3.1.tar.gz`
- run `go build -ldflags="ariga.io/atlas/cmd/action.version=0.3.1" ./cmd/atlas`
- got `-development` when running `atlas version`

### build log as below
```
$ go build -ldflags="-s -w -X ariga.io/atlas/cmd/action.version=0.3.1" ./cmd/atlas
$

$ ./atlas version
atlas CLI version - development
https://github.com/ariga/atlas/releases/tag/latest
```

**Comment by rotemtam** [comment]
hey @chenrui333 ,

Thanks for reaching out! 

Looking at the source code:
https://github.com/ariga/atlas/blob/819b96ff228bfcc095bc4798aa15e5a7642546fe/cmd/action/version.go#L31

The version command expects the version to be a valid semvar string (as defined by [the std lib semver package](https://cs.opensource.google/go/x/mod/+/refs/tags/v0.5.1:semver/semver.go;l=174)), meaning it should start with `v`

This should work:
```shell
go build -ldflags="-s -w -X ariga.io/atlas/cmd/action.version=v0.3.1" ./cmd/atlas
```

Closing this issue, please let me know if I can assist any further!

**Comment by chenrui333** [comment]
I see, let me give a shot.

**Comment by chenrui333** [comment]
Yeah, it works, thanks!
