### ISSUE TITLE
web super slow to spawn, no auto-retry, no progress bar?

### ISSUE THREAD

**Issue by kokizzu** [ariga/atlas#465]
version:
```shell
atlas CLI version v0.3.1
https://github.com/ariga/atlas/releases/tag/v0.3.1
```

because the database in RDS, it usually took 5s to execute any command from Indonesia (My PC) to US (RDS):

```shell
atlas schema inspect --dsn "postgres://ro_user:x@solo-x-db-x.x.us-west-2.rds.amazonaws.com:5432/x?sslmode=disable"  -w
Atlas UI available at: http://127.0.0.1:5800/projects/25769803777/schemas/1
Press Ctrl+C to stop
error checking schema sync status: context deadline exceeded
error checking schema sync status: postgres: querying "foo_items" indexes: context deadline exceeded
```

there's about only 50 tables there.

took a while (like 5 minutes?) before the web spawned, but after spawned, got loading for about a minute, then it shows:

```shell
details: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```

**Comment by rotemtam** [comment]
hi @kokizzu,

Thanks for reaching out. There's indeed a lot more we can do in cases where the connection is slow / inspection takes a long time. Is there any chance you can share you schema with us or help us reproduce this case otherwise? 

In case sharing it over GitHub is suboptimal, (and in any case) you are invited to join our [Discord server](https://discord.com/invite/QhsmBAWzrC)

**Comment by kokizzu** [comment]
i think this one just slow, can't share the schema because it's my office's work NDA

**Comment by rotemtam** [comment]
Sure, I completely understand. Still if you want to join our discord channel and try to help me reproduce the issue you will be very welcome, we're building a great community here :-)

**Comment by yonidavidson** [comment]
Hi @kokizzu , have you tried a newer Atlas version? many improvements were made around performance. 

Thanks.

**Comment by masseelch** [comment]
Closing, as the UI is no longer part of the CLI but now a service you can reach here: https://atlasgo.cloud/
