### ISSUE TITLE
Support schema apply for Mysql table with column "Timestamp/Datetime default with on update"

### ISSUE THREAD

**Issue by mindbergh** [ariga/atlas#472]
The `schema apply` doesn't seem to support datetime/timestamp columns that have default and on update with SQL expression:

For example, with the following schema hcl:

```hcl
schema "foo" {}

table "bar" {
  schema    = schema.foo
  column "id" {
    null = false
    type = int
  }
  column "create_time" {
    null    = false
    type    = datetime
    default = "CURRENT_TIMESTAMP(6)"
  }
  column "update_time" {
    null    = false
    type    = datetime
    default = "CURRENT_TIMESTAMP(6)"
    on_update = "CURRENT_TIMESTAMP(6)"
  }
  primary_key {
    columns = [table.bar.column.id, ]
  }
}
```

```bash
❯ atlas schema apply -d "mysql://root:secret@tcp(localhost:55237)/foo" -f ./foo.hcl
-- Planned Changes:
-- Create "bar" table
CREATE TABLE `foo`.`bar` (`id` int NOT NULL, `create_time` datetime NOT NULL DEFAULT "CURRENT_TIMESTAMP(6)", `update_time` datetime NOT NULL DEFAULT "CURRENT_TIMESTAMP(6)", PRIMARY KEY (`id`))
✔ Apply
Error: create "bar" table: Error 1067: Invalid default value for 'create_time'
```

There are two problems:
1. `CURRENT_TIMESTAMP(6)` shouldn't be quoted as a string.
2. OnUpdate part shouldn't be omitted

If this is actually supported, what's the correct way to define it in hcl? The document doesn't seem to mention this use case.

Mysql version: 5.7.35

Atlas version: 
```
atlas CLI version v0.3.1
https://github.com/ariga/atlas/releases/tag/v0.3.1
```

**Comment by masseelch** [comment]
Hey @mindbergh, thanks for reaching out to us.

> If this is actually supported, what's the correct way to define it in hcl?

This is not supported right now, but I will add it. Inspection should already work.

**Comment by masseelch** [comment]
Hey @mindbergh, me again :smile: 

You can now define timestamp types with default values and on update behavior like this:

```hcl
column "col" {
  null      = false
  type      = timestamp(6)
  default   = sql("current_timestamp(6)")
  on_update = sql("current_timestamp(6)")
}
```

Please let me know if this fixes the issue for you and don't hesitate to contact us again if you have further questions or problems. Feel also free to join our [discord](https://discord.com/invite/QhsmBAWzrC).

**Comment by mindbergh** [comment]
The on_update works well. However, timestamp/datetime precision is omitted in the generated plan. i.e. even if I specify `type = datetime(6)` or `type = datetime(6)`. The generated SQL DDL statement only has `timestamp` or `datetime` as the type (the expected behavior should be `timestamp(6)` or `datetime(6)`.

```
schema "bar" {}

table "foo" {
  schema    = schema.bar
  charset   = "utf8"
  collation = "utf8_general_ci"
  column "id" {
    null = false
    type = char(36)
  }
  column "create_time" {
    null    = false
    type    = timestamp(6)
    default = sql("CURRENT_TIMESTAMP(6)")
  }
  column "update_time" {
    null    = false
    type    = datetime(6)
    default = sql("CURRENT_TIMESTAMP(6)")
    on_update = sql("CURRENT_TIMESTAMP(6)")
  }
  primary_key {
    columns = [table.foo.column.id, ]
  }
}
```

```
-- Planned Changes:
-- Create "foo" table
CREATE TABLE `bar`.`foo` (`id` char(36) NOT NULL, `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (`id`))
```
