### ISSUE TITLE
Support for Covering Indexes

### ISSUE THREAD

**Issue by jezell** [ariga/atlas#500]
The docs seem to imply that indexes can include columns, but I don't see a way to use covering indexes, which we use a lot.

Maybe the DDL for indexes could be extended with a second column list "storing" or something of the sort?

Atlas looks great.

**Comment by a8m** [comment]
Hey (again) @jezell 😃 
Do you mean PostgreSQL "Covering Indexes"? https://www.postgresql.org/docs/current/indexes-index-only-scans.html
Specifically, the `INCLUDE` clause. If so, it can be added to the new form suggested in https://github.com/ariga/atlas/issues/501#issuecomment-1023156681.

If not, can you elaborate or provide some links?

**Comment by jezell** [comment]
Yep. That's it :)

**Comment by crossworth** [comment]
Hello @jezell, I think this feature was added a few days back:
Please, check https://github.com/ariga/atlas/pull/1133 and https://atlasgo.io/guides/postgres/included-columns

**Comment by a8m** [comment]
I think we can close it then. Thanks, @crossworth.
