### ISSUE TITLE
Support for Inverted Indexes

### ISSUE THREAD

**Issue by jezell** [ariga/atlas#501]
Don't see a way to create something like an inverted index in the docs, perhaps the DDL could be extended with an optional index type?

**Comment by a8m** [comment]
Hey @jezell and thanks for opening this issue. Descending indexes are almost done, and I plan to add this to the documentation soon. I added a new form to allow defining more complex indexes.

```hcl
table "users" {
    ...
    index "columns_only" {
        unique = true
        column = [
            table.users.column.a,
            table.users.column.b,
        ]
    }
    index "idx1" {
        on {
            column = table.users.column.a
            desc = true
        }
        on {
            expr = "lower(b)"
        }
    }
    // PostgreSQL only.
    index "idx2" {
        on {
            column = table.users.column.b
            desc = true
            nulls_last = true
        }
        where = "..."
    }
}
```

**Comment by a8m** [comment]
Thanks for opening this issue @jezell. The `DESC` option was added. See https://atlasgo.io/ddl/sql#index
