### ISSUE TITLE
Capture database extensions (e.g. pgcrypto) with `inspect`

### ISSUE THREAD

**Issue by ericyd** [ariga/atlas#520]
**Type**

Bug

**System**

OS: Mac OSX 11.6.3
DB: Postgres 12.8

**Details**

`atlas schema inspect` does not capture database extensions. These are necessary for accurate replication of the database state. (Note: I'm not sure if non-Postgres DBs call these features "extensions" but hopefully the example below makes it clear)

Example: `pgcrypto` is a database extension which exposes various cryptographic functions. Importantly, it is required for any columns that use a UUID as the default value with the `gen_random_uuid()` function.

In standard SQL, a user would create the extension like this:

```sql
create extension if not exists "pgcrypto";
```

**Encapsulated steps to reproduce**

```
# create database and log in
createdb atlas_test -U postgres
psql atlas_test -U postgres

# create extension, then create DB with a default column value of a random UUID
atlas_test=# create extension if not exists "pgcrypto";
atlas_test=# create table test_uuid (id text default gen_random_uuid(), name text);

# insert a record and query it to verify the UUID gen worked
atlas_test=# insert into test_uuid (name) values ('test');
atlas_test=# select * from test_uuid;
atlas_test=# exit

# inspect schema and save to file
atlas schema inspect -d "postgres://postgres@localhost/atlas_test?sslmode=disable" > atlas_test.hcl

# drop DB so the schema can be applied with Atlas
dropdb atlas_test -U postgres
createdb atlas_test -U postgres

atlas schema apply -d "postgres://postgres@localhost/atlas_test?sslmode=disable" -f atlas_test.hcl

Error: create "test_uuid" table: pq: function gen_random_uuid() does not exist
```

The required default function does not exist because the extension was not saved to the schema and therefore not re-applied

**Comment by rotemtam** [comment]
hey @ericyd,
Thanks for taking the time to document this issue thoroughly!
It's definitely something we want to support in the coming versions. 

Out of curiosity, do you have an idea of what the HCL API should look like for this?

**Comment by ericyd** [comment]
I don't have any immediate ideas. Extensions (at least in Postgres) are global to the database, not specific to a schema. So, perhaps it will be necessary to add a new key to the HCL file named `realm` or `database` perhaps. 

Based on my (very limited) knowledge of HCL and the existing structure of Atlas, I think the most concise and simple syntax would be to add an "extensions" attribution at the top of the HCL file, which holds an array of extensions that have been created/enabled for the given database. e.g.:

```
// atlas.hcl
extensions = [
  "pgcrypto"
]

schema "public" {
  ...
}

table "members" {
  schema = "public"
  ...
}
```

I'm not completely sure if that's valid HCL, I haven't studied the spec too much.

**Comment by ericyd** [comment]
old issue and not sure I'll ever get around to submitting a PR for it, but wanted to mention that I learned that in Postgres at least, extensions **are** actually tied to a schema. My above comment was incorrect, and I think that would greatly simplify the HCL as `extensions` could just become a property on the appropriate schema. I still think an array/list/set is probably the simplest option for the property definition, as multiple extensions can be created on a schema

**Comment by rijnhard** [comment]
This is also relevant to Timescale DB where the extension needs to be loaded.

There are additional complexities with creating/converting a hypertable though.

**Comment by slaskis** [comment]
i was just trying out converting out goose migrations into an atlas schema with postgres extensions so stumbled on to this. and i just wanted to clarify something i had issues with regarding extensions per database/schemas and it's that the extensions can be attached to a schema but they are still unique per database (unsure why this is how it works...):

Like this example:

```
CREATE SCHEMA a;
CREATE SCHEMA b;
CREATE EXTENSION pgcrypto SCHEMA a;
CREATE EXTENSION pgcrypto SCHEMA b;

-- =>
--CREATE SCHEMA
--CREATE SCHEMA
--CREATE EXTENSION
--ERROR:  extension "pgcrypto" already exists
```

It makes me think that pg extensions might not really "belong" in an _application_-migration but more of the _infra, setting up the database_-kind of migration.

**Comment by oxilor** [comment]
Are there plans to support extensions in the near future in the schema?

Another use case: I often use the `pg_trgm` extension for text search using trigrams, and if I add `CREATE EXTENSION IF NOT EXISTS pg_trgm;` to the schema, it isn't executed :(

**Comment by ericyd** [comment]
I still think this would be an extremely useful feature.

That said, if anyone is new to using Atlas and wondering about a workaround for this, I believe you could use atlas migrations to solve this problem. I'm not looking at their docs right now but something like

```
atlas migration new create_extension
```

As long as it's the "first" migration in your migrations directory, it should be run before any table creation.

The one workflow that still isn't addressed by this is using `atlas schema apply` to initialize a brand new DB. I guess in that case, migrations are the only option 🤷🏻

**Comment by Nikola-Milovic** [comment]
@ericyd Have you seen? https://atlasgo.io/concepts/dev-database#baseline-schema, not sure if it addresses the problem, but in theory it should?

But for me it hasn't been applying the extensions properly when using `atlas schema apply` if anyone can verify

**Comment by ericyd** [comment]
@Nikola-Milovic I had not seen that. It looks like an interesting solution, though I'm not convinced it solves the core problem for me. My ideal would be that Atlas can apply a schema to **any** new database with all the relevant configuration, including production, or arbitrary new environments (e.g. a test DB instance which is dynamically spun up for integration tests). It looks to me like the baseline schema option is only for local DBs. Definitely useful, but I still think a migration would be needed for production.

I haven't tried this option myself though, and maybe I'm misunderstanding how it is used.

**Comment by a8m** [comment]
Hey all! I just want to share that extensions will be included in the upcoming version. We deliver releases every few weeks, so it's not too far from now.

**Comment by a8m** [comment]
Hey! FYI, this was added in the latest release. Please, see the doc for more info: https://atlasgo.io/atlas-schema/hcl#extension

**Comment by Southclaws** [comment]
Nice, thanks for adding extension support!

One issue I've run into which I'm not sure how to get around is when using Timescale as my database and dev-database, because the extension is already enabled by default, this causes any operation involving the dev-database to fail. However, if I remove the `extension` section from my schema, this generates a "drop extension" migration which disables timescale.

I can get around this manually but I'm aiming to get an automated CI run setup with Atlas. Any pointers?
