### ISSUE TITLE
Support for partial indexes?

### ISSUE THREAD

**Issue by ivanvanderbyl** [ariga/atlas#527]
We have a use case (Using Ent) where we have two optional edges which are mutually exclusive, yet need unique indexes. We are currently creating these indexes using custom SQL migrations in with https://github.com/rubenv/sql-migrate, but we'd like to move to Atlas.

Example:

```go
func (TravelPinnedSegment) Fields() []ent.Field {
	return []ent.Field{
		...
		field.String("from_country_id").MaxLen(3).NotEmpty().Comment("from country edge field").Optional().Nillable(),
		field.String("to_country_id").MaxLen(3).NotEmpty().Comment("to country edge field").Optional().Nillable(),
		field.String("from_region_id").MaxLen(6).NotEmpty().Comment("to country edge field").Optional().Nillable(),
		field.String("to_region_id").MaxLen(6).NotEmpty().Comment("to country edge field").Optional().Nillable(),
	}
}
```

Indexes that we want to handle in Atlas:

```sql
Indexes:
    "travel_pinned_segments_country_edges" UNIQUE, btree (from_country_id, to_country_id, (from_region_id IS NULL AND to_region_id IS NULL)) WHERE to_region_id IS NULL AND from_region_id IS NULL
    "travel_pinned_segments_region_edges" UNIQUE, btree (from_region_id, to_region_id, (from_country_id IS NULL AND to_country_id IS NULL)) WHERE to_country_id IS NULL AND from_country_id IS NULL
```

**Comment by a8m** [comment]
Hey @ivanvanderbyl 👋, I'm glad to see you here. 

Partial indexes are going to be supported soon. In addition to that, we also plan to allow passing custom `CREATE TABLE ..` to unblock users from using features that are not yet supported by atlas. e.g.

```hcl
table "users" {
	ddl = <<EOT
CREATE TABLE "users" (
	...
)
EOT
}
```

**Comment by ivanvanderbyl** [comment]
Thanks @a8m, that would be really useful. Is there a roadmap I can potentially help contribute to?

**Comment by a8m** [comment]
Hey @ivanvanderbyl 👋 

Partial indexes were added in the latest version, and you can see its docs [here](https://atlasgo.io/ddl/sql#partial-indexes). However, it was not added yet to ent (it's a new annotation), so you're welcome to contribute it, or wait a few days until I'll add it 😃 

> Is there a roadmap I can potentially help contribute to?

I'll be happy to discuss this on our Discord. Feel free to ping me there.

**Comment by ivanvanderbyl** [comment]
Neat! thanks @a8m
