### ISSUE TITLE
MySQL - Atlas fails to inpect schema when a column is specified as an unsigned float

### ISSUE THREAD

**Issue by megalan247** [ariga/atlas#545]
It seems that when you create a column in mysql with an unsigned float, Atlas cannot parse its precision in sql/mysql/convert.go and throws a lovely error message like below:

Error: mysql: parse precision "unsigned"

**Comment by rotemtam** [comment]
hey @megalan247 ,
thanks for reporting this! 
note that [MySQL docs](https://dev.mysql.com/doc/refman/8.0/en/numeric-type-syntax.html) state:
> As of MySQL 8.0.17, the UNSIGNED attribute is deprecated for columns of type [FLOAT](https://dev.mysql.com/doc/refman/8.0/en/floating-point-types.html), [DOUBLE](https://dev.mysql.com/doc/refman/8.0/en/floating-point-types.html), and [DECIMAL](https://dev.mysql.com/doc/refman/8.0/en/fixed-point-types.html) (and any synonyms); you should expect support for it to be removed in a future version of MySQL. Consider using a simple CHECK constraint instead for such columns.

However, Atlas should definitely support this for the versions that do. We will work on a fix and update here.

**Comment by masseelch** [comment]
Hey @megalan247, I just merged a PR to fix this. Please try again with the latest master. 

Don't hesitate to reach out to us, if you have any more questions.
