### ISSUE TITLE
Generate SQL for schema alterations

### ISSUE THREAD

**Issue by localhosted** [ariga/atlas#571]
How can we get the generated SQL for each schema change?

I want to use Atlas for merging/diffing diffrent schemas, but not applying the changes directly to the DB. I want the generated migration SQL

**Comment by rotemtam** [comment]
Hey @localhosted 
Thanks for reaching out!
Sure, look at the --dry-run flag on the apply command:

https://atlasgo.io/cli/reference#atlas-schema-apply

Alternatively if you want to see the diff between two databases in SQL, use the schema diff command:

https://atlasgo.io/cli/reference#atlas-schema-diff

HTH
