### ISSUE TITLE
Confusing mixture of CLI --schema flag and DSN

### ISSUE THREAD

**Issue by marxus** [ariga/atlas#573]
Hey folks.

came across this behavior (which IMO is confusing) while trying to create a new Schema(DB) using the Atlas CLI

 given my Realm(MariaDB Instance) already contains other schemas and the new schema hcl is
 ```hcl
table "table" {
  schema = schema.example
  column "column_1" { type = text }
  column "column_2" { type = text  }
}
schema "example" {}
```

while doing:
```sh
❯ atlas schema apply -d 'mysql://root:root@tcp(localhost:3306)/example' -f example.hcl
Error: mysql: query system variables: Error 1049: Unknown database 'example'
```
we receive an error from mysql, this makes sense since the first thing atlas does it to try and connect to the realm using the DSN. example scheme doesn't exists so we get an error.

so I went and tried using the following (apply change on the realm level)
```sh
❯ atlas schema apply -d 'mysql://root:root@tcp(localhost:3306)/' -f example.hcl
-- Planned Changes:
-- Drop schema named "some_db_1"
DROP DATABASE `some_db_1`
-- Drop schema named "some_db_2"
DROP DATABASE `some_db_2`
-- Add new schema named "example"
CREATE DATABASE `example`
-- Create "table" table
CREATE TABLE `example`.`table` (`column_1` text NOT NULL, `column_2` text NOT NULL)
```
this is clearly not what I intended as a user. yet makes sense since atlas was instructed to apply on the realm level, and my example.hcl contains nothing regarding some_db_*
this is also potentially dangerous because users _can_ make mistakes like this

in order to successfully apply and create I decided to work on the realm level and scope the operation using the --schema flag.
```sh
❯ atlas schema apply -d 'mysql://root:root@tcp(localhost:3306)/' -s example -f example.hcl
-- Planned Changes:
-- Add new schema named "example"
CREATE DATABASE `example`
-- Create "table" table
CREATE TABLE `example`.`table` (`column_1` text NOT NULL, `column_2` text NOT NULL)
```
Bazinga! this is what I, as a user, intended to do. 

some thoughts
1. I'm accustomed to other tools like mysql/psql CLIs which usually works like `mysql -hlocalhost -uroot -dDBNAME`
2. IMO schema should be not part of the DSN, as a user, I will probably always decide to use DSN without schema name and explicitly using the schema flag if scoping is needed. feels safer and explicit
3. but, if schema is part of the DSN then the CLI shouldn't allow mixing with with the schema flag.
```sh
# allow these:
atlas schema apply -d 'mysql://root:root@tcp(localhost:3306)/db1'             # one schema
atlas schema apply -d 'mysql://root:root@tcp(localhost:3306)/' -s db1,db2,db3 # multiple schemas
atlas schema apply -d 'mysql://root:root@tcp(localhost:3306)/'                # entire realm
# but not this:
atlas schema apply -d 'mysql://root:root@tcp(localhost:3306)/db1' -s db2,db3  # which can also throw an error if db1 does not exists, even if db2/3 does.
 ```
4. mabye add a --i-acknowledge-im-doing-stuff-on-the-entire-realm flag when no schema is provided and/or change the confirm order
```sh
? Are you sure?:
▸ Abort  # make abort the default. or even change it to terraform style to an explicit "apply" input is required
  Apply
```

when all those said, user errors will still happen. :) yet, the CLI can be a bit more protective and less implicit behavior 

Opinons?

**Comment by masseelch** [comment]
This is now solved using [Diff  Policies](https://atlasgo.io/declarative/apply#diff-policy).
