### ISSUE TITLE
Support for PostgreSQL 9

### ISSUE THREAD

**Issue by lealhugui** [ariga/atlas#578]
Hey all!

Is there any chance to add support for older versions of PostgreSQL (like 9.x)?

I'm willing to send a PR if the possibility exists :)

And keep up the good work!

**Comment by a8m** [comment]
Hey @lealhugui 👋 

PostgreSQL 9.x got to its end of life 3 months ago, and I'm not how common it is. Do you use it? 

> I'm willing to send a PR if the possibility exists :)

I can support you with that. Please, feel free to join our [Discord server](https://discord.com/invite/QhsmBAWzrC) and ping me there.

**Comment by masseelch** [comment]
PostgreSQL is now EOL, therefore I am closing this issue. Don't hesitate to re-open if this is still an issue for you.
