### ISSUE TITLE
Unsupported MySQL 8 Virtual Generated Columns

### ISSUE THREAD

**Issue by tonybolzan** [ariga/atlas#584]
In a MySQL 8 database schema with a table that contains following:
```sql
CREATE DATABASE example;

CREATE TABLE example.test (
  id int unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
  test_a varchar(64) NOT NULL,
  test_b varchar(64) NOT NULL,
  test_c varchar(131) GENERATED ALWAYS AS (concat(test_a, ' - ', test_b)) VIRTUAL
) ENGINE=InnoDB;
```
On running schema inspect
```sh
atlas schema inspect -d "mysql://root:root@tcp(localhost:3306)/example" > example.hcl
```
I receive following error:
```
Error: mysql: unknown attribute "VIRTUAL GENERATED"
```

**Comment by a8m** [comment]
Hey @tonybolzan 👋 

Thanks for reporting this. I'm actually working on it and will come up with a design for the HCL syntax and post it here soon.

**Comment by a8m** [comment]
Hey, I want to get your thoughts on the 2 options:
```hcl
table "t" {
  // ...
  column "c" {
    type = int
    as = "a * abs(b)"
    stored = true
  }
}
```

```hcl
table "t" {
  // ...
  column "d" {
    type = int
    generated {
      as = "a * abs(b)"
      stored  = true
    }
  }
}
```
Note that if the `stored` attribute is omitted, it defaults to `VIRTUAL`. 

I prefer the second option as it's more explicit and groups the 2 attributes for generated/computed columns in one block.

**Comment by yonidavidson** [comment]
I agree that the second option is better since it explicitly differed generated from non-generated columns.

**Comment by masseelch** [comment]
Yes. Second. But `as = "sql(blablabla)", no?

**Comment by a8m** [comment]
> Yes. Second. But `as = "sql(blablabla)", no?

The `check` clause also uses strings without `sql`. We use the `sql` option only in types to skip type-checking.

**Comment by a8m** [comment]
Hey @tonybolzan and thanks again for opening this issue 🙏 

The issue was addressed and was added to our website. Please, update to the latest version to get this feature.
See docs for more info - https://atlasgo.io/ddl/sql#generated-columns
