### ISSUE TITLE
arm64 builds for linux/mac

### ISSUE THREAD

**Issue by andyli** [ariga/atlas#623]
It would be great to have arm64 builds for linux/mac since arm64 machines are getting popular.

**Comment by rotemtam** [comment]
Hi @andyli !
Thanks for writing. I completely agree, arm64 builds are on our bucket list for the near term. We are constantly adding support to more platforms in our build. For example, you can expect an announcement on an official Docker image in the next release!

R

**Comment by Akshay-Thakare** [comment]
+1

**Comment by rotemtam** [comment]
Hey @andyli , @Akshay-Thakare ,

`arm` builds for linux have been available for a while:
![Screen Shot 2023-05-20 at 1 19 56](https://github.com/ariga/atlas/assets/1522681/f5eed881-cc4b-43f6-a687-2ecf04d25a26)

Closing.
