### ISSUE TITLE
add --result-file=./test.hcl argument into inspect

### ISSUE THREAD

**Issue by calvin2021y** [ariga/atlas#689]
It is hard to use pipe when deal with some bash script with docker, add mysqldump like `--result-file=` argument fix the problem.

**Comment by rotemtam** [comment]
Hey @calvin2021y ,

Thanks for reaching out.

In general, I prefer using the OS API for writing to a file. This is more in line with the spirit of orthogonality that we're trying to build this project upon.

However, engineering is a balancing act between principles and constraints. Do you mind sharing more about your use case? What hardship specifically are you running into ?

Thanks

**Comment by calvin2021y** [comment]
for example, a script like this will quit and print error if atlas return error.

```sh
#!/usr/bin/env bash
e(){
        echo " >>>: $*"
        $*
        return $?
}

e docker exec -t mysql mysqldump -d --skip-add-drop-table test --result-file=/tmp/test.sql || exit $?
e docker exec -t atlas atlas schema inspect -u mysql://... -s test --out-file=/tmp/test.hcl || exit $?
echo all task finished without error
```

If you use `docker exec -t atlas atlas schema inspect -u mysql://... -s test > test.hcl`,  the result will end at host dir(not container dir).

It also hard to know if there is some error, because the message not show at console but save into `/tmp/test.hcl`. with `--result-file=/tmp/test.sql` you will see error message from mysqldump in your console.

**Comment by calvin2021y** [comment]
any comment ?
