### ISSUE TITLE
is AWS Redshift supported?

### ISSUE THREAD

**Issue by jccguimaraes** [ariga/atlas#691]
Hi 👋🏼 

I was just wondering if AWS Redshift is supposed to work with Atlas since if I run

```bash
psql "postgresql://USER:PASSWORD@HOST:PORT/DBNAME"
```

the connection is made

but doing 

```bash
atlas schema inspect --url "postgres://USER:PASSWORD@HOST:PORT/DBNAME?sslmode=disable"
```

throws the following error `Error: postgres: unexpected number of rows: 0`

Any thoughts? Thanks

**Comment by rotemtam** [comment]
Hi @jccguimaraes 

Thanks for reaching out. Currently Redshift is not supported by Atlas. Atlas should be able to initiate a connection since iirc Redshift supports the pg wire format, but my guess is that the information schema tables are structured differently which is probably why you're seeing that error.

Support for many more databases will come to Atlas this year, can you share information about your use case for using Atlas
with Redshift?

Thanks

**Comment by jccguimaraes** [comment]
Hi @rotemtam,

Thank you for the reply, so bottom line I was keen on using Atlas to manage our AWS Redshift databases through GitHub Actions or other ways.
We're constantly changing the cluster due to the nature of the project and deploying through Terraform so it would be ideal to have Atlas implemented to being able to manage instead of using a TF provider to do that 😓 .

Hope it clears what is my use case for Atlas.

> Do you plan to manage users and migrations as well? or just schemas?

**Comment by rotemtam** [comment]
Thanks for the reply. That sounds really cool. Do you mind joining our Discord server? we have some cool things coming this quarter that might be interesting to you.

https://discord.gg/zZ6sWVg6NT

And yes Atlas will be used to manage users and grant permissions and support more traditional "versioned migrations". A terraform integration is also in the works

**Comment by jccguimaraes** [comment]
of course. thanks

**Comment by fabricef-p** [comment]
I may be interested also by RedShift support. Looking forward to it

**Comment by dnascimento** [comment]
I'm also interested on the support for Redshift

**Comment by alexlobanov** [comment]
And we are also really interested for Redshift support :)

**Comment by JianTray** [comment]
Would love to see this for Redshift! :)

**Comment by rotemtam** [comment]
Hey @jccguimaraes @alexlobanov @dnascimento @fabricef-p @JianTray ,

@a8m and I are looking to interview some Redshift users about your expectations and problems that Atlas can solve. Feel free to schedule some time with us here, if this is still relevant: 

https://calendly.com/rotemtam-ariga/atlas-redshift-users

**Comment by a8m** [comment]
Hey all! 
Redshift support was added in Atlas 0.23. See: https://atlasgo.io/blog/2024/05/21/atlas-v-0-23

Please give it a try and share your feedback with us here or on our [Discord server](https://discord.com/invite/zZ6sWVg6NT).
