### ISSUE TITLE
mysql binary type error

### ISSUE THREAD

**Issue by calvin2021y** [ariga/atlas#751]
varbinary is work
```hcl
table "test" {
	schema  = schema.test
	column "bin" {
		type = varbinary(32)
		null = false
	}
}
schema "test" {
	charset = "utf8mb4"
	collate = "utf8mb4_unicode_ci"
}
```

```sql
CREATE TABLE `test`.`test` (`bin` varbinary(32) NOT NULL)
```

binary is not work
```hcl
table "test" {
	schema  = schema.test
	column "bin" {
		type = binary(32)
		null = false
	}
}
schema "test" {
	charset = "utf8mb4"
	collate = "utf8mb4_unicode_ci"
}
```

```sql
CREATE TABLE `test`.`test` (`bin` binary NOT NULL)
```

there is no fixed size 32 in SQL.

Test on today master branch.

**Comment by a8m** [comment]
Hey @calvin2021y 👋 
Thanks for reporting this issue. The fix should be simple.

Would you like to contribute this fix to Atlas? I can support you on our [Discord server](https://discord.gg/zZ6sWVg6NT), but if not that's also fine, I can handle this later today or tomorrow.

**Comment by calvin2021y** [comment]
hi @a8m 
Sorry for not to attend to discord server, I still don't have discord account.

Can you give some tips here how to fix this ?

**Comment by calvin2021y** [comment]
confirm fixed.
