### ISSUE TITLE
v0.3.7 does not contain sqltools

### ISSUE THREAD

**Issue by aleyrizvi** [ariga/atlas#755]
Hi,
Apologies for stupid question. I am new.

I am trying to follow entgo versioned migration : https://entgo.io/docs/versioned-migrations/#use-a-custom-formatter

However, it is looking for ariga.io/atlas/sql/sqltool for `sqltool.GolangMigrateFormatter`

My code is unable to find this sqltool as it is not available in the recent. 

Am I doing something wrong?

**Comment by aleyrizvi** [comment]
I am able to use it somehow with go get ariga.io/atlas@master that fetched 0.3.8 version but funny I do not see it on github :(

**Comment by masseelch** [comment]
Hey @aleyrizvi, thanks for your question, they are not stupid!

Atlas (and Ent) can always be used from master branch. If you do `go get <pkg>@master` in Go, it will generate a version number for master from the commit hash, that is why you see v0.3.8 even though we haven't released it yet. 

Also, 0.3.7 was released before there was `sqltool` package. You did everything right by fetching master.
