### ISSUE TITLE
Support for `CockroachDB`?

### ISSUE THREAD

**Issue by achew22** [ariga/atlas#785]
When I attempt to connect to CockroachDB, I get the error:

```
Error: pq: unknown function: to_regclass()
```

I presume this is because `to_regclass()` is unsupported by Cockroach at this time. Is there any plan to support CockroachDB?

**Comment by hilakashai** [comment]
Hey @achew22, thanks for reaching out!
Currently CockroachDB is unsupported, but @hedwigz is working on it as we speak and should be coming out soon.

**Comment by hedwigz** [comment]
I'll be sharing live progress updates and insights if you guys want to follow along or help :)
https://discord.gg/KvxFZGY2mu (`cockroach-wg` channel)

**Comment by hedwigz** [comment]
Hey @matdehaast @achew22 :wave:   
The master branch now supports CockroachDB - please give it a go and let us know how it works out for you :)

**Comment by StevenACoffman** [comment]
Hey, quick question, the https://github.com/ariga/atlas#supported-databases currently do not list CockroachDB. Does that indicate support is still in beta, or that it is ready for production use?
