### ISSUE TITLE
Support for BRIN index

### ISSUE THREAD

**Issue by statushub-piotr** [ariga/atlas#787]
Hi,
To start I'll say that Atlas looks like a great tool!
However we are using BRIN in few places and it looks like it's not yet supported by Atlas:
```
recovering from panic atlasschema: invalid schema definition: schemahcl: failed decoding: :1677,15-19: Unknown variable; There is no variable named "BRIN". Did you mean "GIN"? goroutine 1 [running]:
```
Are there any plans to add support for BRIN indices ?

**Comment by a8m** [comment]
Hey @statushub-piotr 👋 

I can add support for it today and update you when it's ready here or on our [Discord server](https://discord.gg/zZ6sWVg6NT).

**Comment by statushub-piotr** [comment]
Thanks for super fast response!
Response here is fine.

**Comment by a8m** [comment]
Closed with https://github.com/ariga/atlas/pull/788.

Please, feel free to reopen the issue if you have any troubles. Thanks 🙏
