### ISSUE TITLE
Feature: generate DDL from schema.hcl without an active database connection

### ISSUE THREAD

**Issue by tux21b** [ariga/atlas#821]
We would like to diff a ``schema.hcl`` with an empty state and generate the DDL statements (create table, create index, alter table add foreign key, etc.) assuming an empty MySQL/PostgreSQL/sqlite database.

This would currently solve two use cases for us:

A) We would like to generate the current schema (in SQL syntax) before calling [sqlc](https://github.com/kyleconroy/sqlc) - a static query parser and Go type / function generator which requires the current schema as input. Since sqlc does not require an active database, it would be great if atlas would not require an active database either.

B) Our team is used to the SQL syntax but not so much to Atlas schema.hcl. Having the ability to review the atlas.hcl in the well known DDL syntax by converting it via the altas CLI would be great. The operation should also work without a database, since creating an empty database before executing this command is also a bit tiresome.

Ideally the output of the offline DDL plan generation is exactly the same as diffing against an empty database. I can not think about any edge case leading to a different output when applied to a real empty database at the moment, but even if there are some minor differences, the output would be fine for the use cases described above.

**Comment by masseelch** [comment]
Hey @tux21b,

there is one thing to consider before we add something like this: Atlas does validate the input HCL against the database before creating the DDL. If not working with a dev database will render this step impossible. 

Also I wonder, are you aware of the special docker syntax for the dev database? Atlas can spin up an ephemeral docker to use as dev database which will be removed when the command finishes.

`atlas migrate diff --dev-url docker://mysql/8 --to file://atlas.hcl`

This will start a local `mysql:8` container, use it (empty) as current state and print the DDL on screen.

More information: https://atlasgo.io/cli/url in the `docker` tab.

**Comment by masseelch** [comment]
@tux21b I will close this issue as I answered why we need a connection and that there is a docker driver for this purpose.
