### ISSUE TITLE
atlas: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by atlas)

### ISSUE THREAD

**Issue by CuteSmartTiger** [ariga/atlas#870]
it is very complicate to upgrade  linux system from CLIBC_2.27 to CLIBC_2.28. 
cloud you support CLIBC  verison  lower than 2.28.
this question make less people use this tool，if can solve this problem,more and more people will use this tool

**Comment by masseelch** [comment]
Hey @CuteSmartTiger, what OS are you using? 

Also please, did you try to run of our distributed builds or did you try to compile by yourself? (I guess the former, but I better ask before).

**Comment by blocka** [comment]
Same issue. I'm using ubuntu 14.04

**Comment by masseelch** [comment]
Hey @CuteSmartTiger and @blocka. Our distributed builds are compiled on Ubuntu 20.04, which has a new version of `GLIBC` than the distros you use. 
You can either compile the binary yourself from GitHub or update your distribution.

In the meantime I will evaluate, if we can support prior versions of Linux.

**Comment by masseelch** [comment]
As a workaround, please use our docker image instead of the distributed binary. You can alias the command like this `alias atlas="docker run --rm arigaio/atlas:latest"` and then simply use the docker like you would use the atlas binary `atlas schema inspect -u sqlite://file.db`
