### ISSUE TITLE
Support for PostgreSQL arrays in HCL schema definition

### ISSUE THREAD

**Issue by ndrpnt** [ariga/atlas#901]
Hi, is it currently possible to define a table with an [array type](https://www.postgresql.org/docs/current/arrays.html) column? If not, do you plan on supporting it? Thanks

**Comment by rotemtam** [comment]
Hi @ndrpnt 
Thanks for reaching out.

Running this on PostgreSQL:
```sql
create table ndrpnt ( arr_col text[] );
```

Inspecting the table with atlas:
```
atlas schema inspect -u 'postgres://postgres:pass@localhost:5432/?sslmode=disable'
```
I get:
```hcl
table "ndrpnt" {
  schema = schema.public
  column "arr_col" {
    null = true
    type = sql("text[]")
  }
}
schema "public" {
}
```
As you can see, you can use the `sql()` escape-hatch function for working with types that aren't currently natively supported by Atlas HCL. 

HTH
