### ISSUE TITLE
`go run ariga.io/atlas/cmd/atlas@master` fails

### ISSUE THREAD

**Issue by achew22** [ariga/atlas#928]
When trying to run atlas from master it fails out with the following error.

```
$ go run ariga.io/atlas/cmd/atlas@master
go: ariga.io/atlas/cmd/atlas@master: module ariga.io/atlas@master found (v0.4.3-0.20220708180314-c4867b18d9f8), but does not contain package ariga.io/atlas/cmd/atlas
```

Looking at the commit history it looks like you've been messing with that package but I can't figure out how to do a bisect to figure out what commit did it.

**Comment by achew22** [comment]
I think I figured out a bisect route:

```sh
git bisect start
git bisect bad c4867b18d9f89239e0e29de8df8e2cdf3a747f0e
git bisect good c4867b18d9f89239e0e29de8df8e2cdf3a747f0e~100
echo 'exec go run ariga.io/atlas/cmd/atlas@$(git log --pretty=tformat:"%H" -1)' > run.sh
chmod +x run.sh
git bisect run ./run.sh
```

Looks like it broke in https://github.com/ariga/atlas/pull/909

```sh
➜  atlas git:(master) ✗ go run ariga.io/atlas/cmd/atlas@ba866843e931efb801b2eb93157d3c00dc73daa0
go: ariga.io/atlas/cmd/atlas@ba866843e931efb801b2eb93157d3c00dc73daa0: module ariga.io/atlas@ba866843e931efb801b2eb93157d3c00dc73daa0 found (v0.4.3-0.20220706104906-ba866843e931), but does not contain package ariga.io/atlas/cmd/atlas
➜  atlas git:(07822e4) ✗ go run ariga.io/atlas/cmd/atlas@07822e42422ffad9a39e84f13f1731fdfb838157
A database toolkit.

Usage:
  atlas [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  env         Print atlas environment variables.
  help        Help about any command
  migrate     Manage versioned migration files
  schema      Work with atlas schemas.
  version     Prints this Atlas CLI version information.

Flags:
  -h, --help   help for atlas

Use "atlas [command] --help" for more information about a command.
```

**Comment by a8m** [comment]
> I think I figured out a bisect route:
> git bisect start
git bisect bad c4867b18d9f89239e0e29de8df8e2cdf3a747f0e
git bisect good c4867b18d9f89239e0e29de8df8e2cdf3a747f0e~100
echo 'exec go run ariga.io/atlas/cmd/atlas@$(git log --pretty=tformat:"%H" -1)' > run.sh
chmod +x run.sh
git bisect run ./run.sh
> Looks like it broke in https://github.com/ariga/atlas/pull/909

Beast! 💪 
Thanks for reporting this @achew22. I fixed the issue (I added another index.html file to ariga.io to support it). Can you give it another try?

The reason for https://github.com/ariga/atlas/pull/909 was to keep the `ariga.io/atlas` package (imported by [ent](https://github.com/ent/ent)) more lightweight in terms of dependencies (see https://github.com/ariga/atlas/issues/684).

**Comment by rotemtam** [comment]
@achew22 can we close this one?

**Comment by achew22** [comment]
I think it's good. Thanks for following up
