### ISSUE TITLE
CRDB Schema Create error

### ISSUE THREAD

**Issue by chenjpu** [ariga/atlas#990]
CRDB version 22.1.5
ent  0.11.1

```
ALTER TABLE "attachment" ALTER COLUMN "id" SET GENERATED BY DEFAULT SET START WITH 1 SET INCREMENT BY 1
```

```
ERROR:  at or near "generated": syntax error
```

**Comment by masseelch** [comment]
I was not able to reproduce this issue, so I assume it was solved. @chenjpu If it is still happening for you, can you provide us with a little more info how you encountered this?
