### ISSUE TITLE
How to Install atlas on Debian

### ISSUE THREAD

**Issue by bichanna** [ariga/atlas#999]
Hi,

I'm trying to install atlas CLI on a Debian (x86_64) computer. However, there's no instruction on how to do so.

Thanks.

**Comment by rotemtam** [comment]
hey @bichanna 
I see you closed the issue so perhaps you found a solution. In any case, for future searches, our [Getting Started](https://atlasgo.io/cli/getting-started/setting-up#install-the-cli) section has instructions on how to install Atlas on different OSs.

In addition, if you want to use Atlas from within a Docker image, use:
```sh
docker run arigaio/atlas:latest
```
